jevois::GUIeditor Class Reference
#include <jevois/GPU/GUIeditor.H>
Editor panel for JeVois-Pro GUI.
This panel allows one to select one of several files, and to edit it.
Definition at line 46 of file GUIeditor.H.
Public Member Functions
GUIeditor (GUIhelper *helper, std::string const &imguiid, std::vector< EditorItem > &&fixeditems, std::string const &scanpath, std::string const &prefix, std::set< std::string > &&extensions)
Constructor.
virtual ~GUIeditor ()
Destructor.
void draw ()
Draw the editor into ImGui.
void loadFile (std::filesystem::path const &fn)
Load a file and set it as the current file.
const std::filesystem::path & getLoadedFilePath () const
Get path of file last loaded with loadFile(), may be empty.
void refresh ()
Refresh list of files.
Protected Member Functions
void saveFile ()
Save a file.
Related Functions
(Note that these are not member functions.)
enum EditorSaveAction
Helper enum for actions to execute after saving a config file.
Constructor & Destructor Documentation
GUIeditor()
jevois::GUIeditor::GUIeditor (GUIhelper * helper, std::string const & imguiid, std::vector< EditorItem > && fixeditems, std::string const & scanpath, std::string const & prefix, std::set< std::string > && extensions)
Constructor.
Definition at line 31 of file GUIeditor.C.
References JEVOIS_SHARE_PATH, and saveFile().
 GUIeditor()
jevois::GUIeditor::~GUIeditor () [virtual]
Destructor.
Definition at line 46 of file GUIeditor.C.
Member Function Documentation
draw()
void jevois::GUIeditor::draw ()
Draw the editor into ImGui.
Definition at line 112 of file GUIeditor.C.
getLoadedFilePath()
const std::filesystem::path & jevois::GUIeditor::getLoadedFilePath () const
Get path of file last loaded with loadFile(), may be empty.
Definition at line 494 of file GUIeditor.C.
loadFile()
void jevois::GUIeditor::loadFile (std::filesystem::path const & fn)
Load a file and set it as the current file.
Definition at line 361 of file GUIeditor.C.
refresh()
void jevois::GUIeditor::refresh ()
Refresh list of files.
Definition at line 50 of file GUIeditor.C.
References jevois::VideoMapping::cmakepath(), and jevois::VideoMapping::path().
saveFile()
void jevois::GUIeditor::saveFile () [protected]
Save a file.
Definition at line 498 of file GUIeditor.C.
References LINFO.
Referenced by GUIeditor().
Friends And Related Function Documentation
EditorSaveAction
enum EditorSaveAction [related]
Helper enum for actions to execute after saving a config file.
Definition at line 34 of file GUIeditor.H.
The documentation for this class was generated from the following files:
include/jevois/GPU/GUIeditor.H
src/jevois/GPU/GUIeditor.C