jevois::GUIserial Class Reference
#include <jevois/GPU/GUIserial.H>
Simple class to monitor a serial port in the JeVois-Pro GUI.
This class opens a window and displays traffic on a given serial port. Its interface is the same as a regular Serial (or its parent, UserInterface), with the addition of a draw() function to render into a window managed by the caller.
Definition at line 33 of file GUIserial.H.
Public Member Functions
virtual ~GUIserial ()
Virtual destructor for safe inheritance.
bool readSome (std::string &str) override
Read some bytes if available, and return true and a string when one is complete.
void writeString (std::string const &str) override
Write a string, using the line termination convention of serial::linestyle.
void draw ()
Render into ImGui.
Serial (std::string const &instance, UserInterface::Type type)
Inherited constructor ok.
Protected Member Functions
void clear ()
Clear the contents of the window.
Additional Inherited Members
Constructor & Destructor Documentation
 GUIserial()
jevois::GUIserial::~GUIserial () [virtual]
Virtual destructor for safe inheritance.
Definition at line 23 of file GUIserial.C.
Member Function Documentation
clear()
void jevois::GUIserial::clear () [protected]
Clear the contents of the window.
Definition at line 126 of file GUIserial.C.
draw()
void jevois::GUIserial::draw ()
Render into ImGui.
Render into a window that was already opened and will be closed by the caller.
Definition at line 56 of file GUIserial.C.
References jevois::stringStartsWith().
readSome()
bool jevois::GUIserial::readSome (std::string & str) [override], [virtual]
Read some bytes if available, and return true and a string when one is complete.
If the monitor window is open, anything read will also be displayed in the window.
Reimplemented from jevois::Serial.
Definition at line 27 of file GUIserial.C.
References jevois::Serial::readSome().
Serial()
jevois::Serial::Serial
Inherited constructor ok.
Definition at line 61 of file Serial.C.
writeString()
void jevois::GUIserial::writeString (std::string const & str) [override], [virtual]
Write a string, using the line termination convention of serial::linestyle.
No line terminator should be included in the string, writeString() will add one. If the monitor window is open, anything written will also be displayed in the window.
Reimplemented from jevois::Serial.
Definition at line 42 of file GUIserial.C.
References jevois::Serial::writeString().
The documentation for this class was generated from the following files:
include/jevois/GPU/GUIserial.H
src/jevois/GPU/GUIserial.C