jevois::dnn::NetworkONNX Class Reference
#include <jevois/DNN/NetworkONNX.H>
围绕 ONNX-Runtime 神经网络的包装器
Definition at line 33 of file NetworkONNX.H.
Public Member Functions
NetworkONNX (std::string const &instance)
Inherited constructor ok.
virtual ~NetworkONNX ()
Destructor.
void freeze (bool doit) override
冻结/解冻参数，用户在运行时不应更改
virtual std::vector< vsi_nn_tensor_attr_t > inputShapes () override
Get shapes of all input tensors.
virtual std::vector< vsi_nn_tensor_attr_t > outputShapes () override
Get shapes of all output tensors.
Protected Member Functions
void load () override
Load from disk.
std::vector< cv::Mat > doprocess (std::vector< cv::Mat > const &blobs, std::vector< std::string > &info) override
Process input blobs and obtain output blobs.
Additional Inherited Members
Constructor & Destructor Documentation
NetworkONNX()
jevois::dnn::NetworkONNX::NetworkONNX (std::string const & instance)
Inherited constructor ok.
Definition at line 25 of file NetworkONNX.C.
 NetworkONNX()
jevois::dnn::NetworkONNX::~NetworkONNX () [virtual]
Destructor.
Definition at line 34 of file NetworkONNX.C.
Member Function Documentation
doprocess()
std::vector< cv::Mat > jevois::dnn::NetworkONNX::doprocess (std::vector< cv::Mat > const & blobs, std::vector< std::string > & info) [override], [protected], [virtual]
Process input blobs and obtain output blobs.
Implements jevois::dnn::Network.
Definition at line 109 of file NetworkONNX.C.
References jevois::dnn::attrmat(), jevois::dnn::attrstr(), jevois::cvBytesPerPix(), jevois::cvtypestr(), LFATAL, jevois::dnn::shapestr(), and jevois::dnn::vsi2cv().
freeze()
void jevois::dnn::NetworkONNX::freeze (bool doit) [override], [virtual]
冻结/解冻参数，用户在运行时不应更改
Reimplemented from jevois::dnn::Network.
Definition at line 38 of file NetworkONNX.C.
References jevois::dnn::Network::freeze().
inputShapes()
std::vector< vsi_nn_tensor_attr_t > jevois::dnn::NetworkONNX::inputShapes () [override], [virtual]
Get shapes of all input tensors.
Implements jevois::dnn::Network.
Definition at line 46 of file NetworkONNX.C.
References LFATAL.
load()
void jevois::dnn::NetworkONNX::load () [override], [protected], [virtual]
Load from disk.
Implements jevois::dnn::Network.
Definition at line 60 of file NetworkONNX.C.
References jevois::absolutePath(), LINFO, jevois::dnn::shapestr(), and jevois::dnn::tensorattr().
outputShapes()
std::vector< vsi_nn_tensor_attr_t > jevois::dnn::NetworkONNX::outputShapes () [override], [virtual]
Get shapes of all output tensors.
Implements jevois::dnn::Network.
Definition at line 53 of file NetworkONNX.C.
References LFATAL.
The documentation for this class was generated from the following files:
include/jevois/DNN/NetworkONNX.H
src/jevois/DNN/NetworkONNX.C