jevois::GPUprogram Class Reference
#include <jevois/GPU/GPUprogram.H>
Simple class to load and compile some OpenGL-ES program.
Definition at line 25 of file GPUprogram.H.
Public Member Functions
GPUprogram (char const *vertex_shader, char const *fragment_shader)
Constructor, loads and compiles the program, assigns it a program ID.
~GPUprogram ()
Destructor, deletes the program from OpenGL and frees up the ID.
GLuint id () const
Get the program ID so we can tell OpenGL to use this program.
Constructor & Destructor Documentation
GPUprogram()
jevois::GPUprogram::GPUprogram (char const * vertex_shader, char const * fragment_shader)
Constructor, loads and compiles the program, assigns it a program ID.
If shader names start with a #, assume they are code, otherwise filenames.
Definition at line 21 of file GPUprogram.C.
References GL_CHECK, jevois::GPUshader::id(), LDEBUG, jevois::GPUshader::load(), and jevois::GPUshader::set().
 GPUprogram()
jevois::GPUprogram::~GPUprogram ()
Destructor, deletes the program from OpenGL and frees up the ID.
Definition at line 45 of file GPUprogram.C.
Member Function Documentation
id()
GLuint jevois::GPUprogram::id () const
Get the program ID so we can tell OpenGL to use this program.
Definition at line 57 of file GPUprogram.C.
The documentation for this class was generated from the following files:
include/jevois/GPU/GPUprogram.H
src/jevois/GPU/GPUprogram.C