jevois::dnn::NetworkTPU Class Reference
#include <jevois/DNN/NetworkTPU.H>
围绕 Coral TPU 神经网络的包装器
Definition at line 31 of file NetworkTPU.H.
Public Member Functions
virtual ~NetworkTPU ()
Destructor.
void freeze (bool doit) override
冻结/解冻参数，用户在运行时不应更改
virtual std::vector< vsi_nn_tensor_attr_t > inputShapes () override
Get shapes of all input tensors.
virtual std::vector< vsi_nn_tensor_attr_t > outputShapes () override
Get shapes of all output tensors.
Protected Member Functions
void load () override
Load from disk.
std::vector< cv::Mat > doprocess (std::vector< cv::Mat > const &blobs, std::vector< std::string > &info) override
Process input blobs and obtain output blobs.
Additional Inherited Members
Constructor & Destructor Documentation
 NetworkTPU()
jevois::dnn::NetworkTPU::~NetworkTPU () [virtual]
Destructor.
Definition at line 40 of file NetworkTPU.C.
References jevois::dnn::Network::waitBeforeDestroy().
Member Function Documentation
doprocess()
std::vector< cv::Mat > jevois::dnn::NetworkTPU::doprocess (std::vector< cv::Mat > const & blobs, std::vector< std::string > & info) [override], [protected], [virtual]
Process input blobs and obtain output blobs.
Implements jevois::dnn::Network.
Definition at line 167 of file NetworkTPU.C.
References jevois::cvBytesPerPix(), jevois::getFileString(), LFATAL, o, jevois::sformat(), jevois::dnn::shapestr(), jevois::dnn::tf2cv(), and jevois::to_string().
freeze()
void jevois::dnn::NetworkTPU::freeze (bool doit) [override], [virtual]
冻结/解冻参数，用户在运行时不应更改
Reimplemented from jevois::dnn::Network.
Definition at line 44 of file NetworkTPU.C.
References jevois::dnn::Network::freeze().
inputShapes()
std::vector< vsi_nn_tensor_attr_t > jevois::dnn::NetworkTPU::inputShapes () [override], [virtual]
Get shapes of all input tensors.
Implements jevois::dnn::Network.
Definition at line 56 of file NetworkTPU.C.
References jevois::dnn::attrstr(), LFATAL, LINFO, jevois::dnn::parseTensorSpecs(), and jevois::dnn::tensorattr().
load()
void jevois::dnn::NetworkTPU::load () [override], [protected], [virtual]
Load from disk.
Implements jevois::dnn::Network.
Definition at line 102 of file NetworkTPU.C.
References jevois::absolutePath(), LFATAL, LINFO, and jevois::dnn::shapestr().
outputShapes()
std::vector< vsi_nn_tensor_attr_t > jevois::dnn::NetworkTPU::outputShapes () [override], [virtual]
Get shapes of all output tensors.
Implements jevois::dnn::Network.
Definition at line 79 of file NetworkTPU.C.
References jevois::dnn::attrstr(), LFATAL, LINFO, jevois::dnn::parseTensorSpecs(), and jevois::dnn::tensorattr().
The documentation for this class was generated from the following files:
include/jevois/DNN/NetworkTPU.H
src/jevois/DNN/NetworkTPU.C