jevois::dnn::PostProcessorSegment Class Reference
#include <jevois/DNN/PostProcessorSegment.H>
神经网络管道的后处理器
这是深度神经网络处理管道的最后一步。
Definition at line 28 of file PostProcessorSegment.H.
Public Member Functions
virtual ~PostProcessorSegment ()
Destructor.
void freeze (bool doit) override
冻结/解冻用户在运行时不应更改的参数
void process (std::vector< cv::Mat > const &outs, PreProcessor *preproc) override
处理输出并绘制/发送一些结果
void report (jevois::StdModule *mod, jevois::RawImage *outimg=nullptr, jevois::OptGUIhelper *helper=nullptr, bool overlay=true, bool idle=false) override
将上一个 process() 中发生的事情报告给控制台/输出视频/GUI
Protected Member Functions
void postInit () override
在 postInit() 中创建 colormap
Protected Attributes
std::array< uint32_t, 256 > itsColor
Colors for our drawings, as RGBA with zero alpha value.
Related Functions
(Note that these are not member functions.)
JEVOIS_DECLARE_PARAMETER (bgid, unsigned char, `Class ID for the background, will show as fully transparent in ` `semantic segmentation overlays`, 0, ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (SegType,(ClassesHWC)(ClassesCHW)(ArgMax))
Enum.
JEVOIS_DECLARE_PARAMETER (segtype, SegType, `Type of segmentation network output. ClassesHWC: output is 1xHxWxC ` `for C classes and we get one score per class we will show ` `the top scoring class for each pixel (e.g., UNet-MobileNet on TPU). ClassesCHW: ` `output is 1xCxHxW and the rest is as for ClassesHWC (e.g., DeepLabV3 OpenCV). ArgMax: ` `output is HxW, 1xHxW, or 1xHxWx1 and contains the class ID for each pixel ` `(e.g., DeepLabV3 on TPU).`, SegType::ClassesHWC, SegType_Values, ParamCateg)
Parameter.
Constructor & Destructor Documentation
 PostProcessorSegment()
jevois::dnn::PostProcessorSegment::~PostProcessorSegment () [virtual]
Destructor.
Definition at line 29 of file PostProcessorSegment.C.
References jevois::GUIhelper::releaseImage().
Member Function Documentation
freeze()
void jevois::dnn::PostProcessorSegment::freeze (bool doit) [override], [virtual]
冻结/解冻用户在运行时不应更改的参数
Implements jevois::dnn::PostProcessor.
Definition at line 37 of file PostProcessorSegment.C.
postInit()
void jevois::dnn::PostProcessorSegment::postInit () [override], [protected], [virtual]
在 postInit() 中创建 colormap
Reimplemented from jevois::Component.
Definition at line 43 of file PostProcessorSegment.C.
process()
void jevois::dnn::PostProcessorSegment::process (std::vector< cv::Mat > const & outs, PreProcessor * preproc) [override], [virtual]
处理输出并绘制/发送一些结果
Implements jevois::dnn::PostProcessor.
Definition at line 147 of file PostProcessorSegment.C.
References jevois::dnn::PreProcessor::getUnscaledCropRect(), LFATAL, LTHROW, and jevois::dnn::shapestr().
report()
void jevois::dnn::PostProcessorSegment::report (jevois::StdModule * mod, jevois::RawImage * outimg = nullptr, jevois::OptGUIhelper * helper = nullptr, bool overlay = true, bool idle = false) [override], [virtual]
将上一个 process() 中发生的事情报告给控制台/输出视频/GUI
Implements jevois::dnn::PostProcessor.
Definition at line 184 of file PostProcessorSegment.C.
References jevois::GUIhelper::drawImage(), and jevois::GUIhelper::i2d().
Friends And Related Function Documentation
JEVOIS_DECLARE_PARAMETER() [1/2]
JEVOIS_DECLARE_PARAMETER (bgid , unsigned char , `Class ID for the background, will show as fully transparent in ` `semantic segmentation overlays` , 0 , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [2/2]
JEVOIS_DECLARE_PARAMETER (segtype , SegType , `Type of segmentation network output. ClassesHWC: output is 1xHxWxC ` `for C classes and we get one score per class we will show ` `the top scoring class for each pixel (e.g., UNet-MobileNet on TPU). ClassesCHW: ` `output is 1xCxHxW and the rest is as for ClassesHWC (e.g., DeepLabV3 OpenCV). ArgMax: ` `output is HxW, 1xHxW , or 1xHxWx1 and contains the class ID for each pixel ` `(e.g., DeepLabV3 on TPU).` , SegType::ClassesHWC , SegType_Values , ParamCateg) [related]
Parameter.
JEVOIS_DEFINE_ENUM_CLASS()
JEVOIS_DEFINE_ENUM_CLASS (SegType , (ClassesHWC)(ClassesCHW)(ArgMax)) [related]
Enum.
Member Data Documentation
itsColor
std::array<uint32_t, 256> jevois::dnn::PostProcessorSegment::itsColor [protected]
Colors for our drawings, as RGBA with zero alpha value.
Definition at line 52 of file PostProcessorSegment.H.
The documentation for this class was generated from the following files:
include/jevois/DNN/PostProcessorSegment.H
include/jevois/DNN/PostProcessor.H
src/jevois/DNN/PostProcessorSegment.C