jevois::IMUspi Class Reference
#include <jevois/Core/IMUspi.H>
具有 SPI 接口的 IMU，例如 JeVois-Pro IMX290 摄像头传感器板上的 ICM20948 IMU
Definition at line 29 of file IMUspi.H.
Public Member Functions
IMUspi (std::string const &devname)
Constructor.
virtual ~IMUspi ()
Destructor.
virtual bool isSPI () const override
如果我们使用 SPI 进行传输，则返回 true。当 ICM20948_REG_USER_CTRL 写入时使用；
 IMU 寄存器的访问函数
void writeRegister (unsigned short reg, unsigned char val) override
将值写入 IMU 寄存器之一
unsigned char readRegister (unsigned short reg) override
从相机的 IMU 寄存器之一读取一个值
void writeRegisterArray (unsigned short reg, unsigned char const *vals, size_t num) override
将值数组写入相机的 IMU 寄存器
void readRegisterArray (unsigned short reg, unsigned char *vals, size_t num) override
从相机的 IMU 寄存器读取值数组
Protected Member Functions
void selectBank (unsigned short reg)
void spi_xfer (unsigned char addr, unsigned char dir, size_t siz, unsigned char *datain, unsigned char const *dataout)
Protected Attributes
const std::string itsDevName
int itsFd
uint8_t itsIMUbank
Constructor & Destructor Documentation
IMUspi()
jevois::IMUspi::IMUspi (std::string const & devname)
Constructor.
Definition at line 33 of file IMUspi.C.
References itsFd, LERROR, LFATAL, LINFO, jevois::IMU::loadDMPfirmware(), readRegister(), writeRegister(), and XIOCTL.
 IMUspi()
jevois::IMUspi::~IMUspi () [virtual]
Destructor.
Definition at line 96 of file IMUspi.C.
Member Function Documentation
isSPI()
bool jevois::IMUspi::isSPI () const [override], [virtual]
如果我们使用 SPI 进行传输，则返回 true。当 ICM20948_REG_USER_CTRL 写入时使用；
Implements jevois::IMU.
Definition at line 102 of file IMUspi.C.
readRegister()
unsigned char jevois::IMUspi::readRegister (unsigned short reg) [override], [virtual]
从相机的 IMU 寄存器之一读取一个值
请参阅基类 jevois::IMU 以获取完整文档。
Implements jevois::IMU.
Definition at line 210 of file IMUspi.C.
References ICM20948_SPI_READ, and LDEBUG.
Referenced by IMUspi().
readRegisterArray()
void jevois::IMUspi::readRegisterArray (unsigned short reg, unsigned char * vals, size_t num) [override], [virtual]
从相机的 IMU 寄存器读取值数组
Implements jevois::IMU.
Definition at line 229 of file IMUspi.C.
References ICM20948_SPI_READ, LDEBUG, and LFATAL.
selectBank()
void jevois::IMUspi::selectBank (unsigned short reg) [protected]
Definition at line 146 of file IMUspi.C.
References ICM20948_SPI_WRITE, and LDEBUG.
spi_xfer()
void jevois::IMUspi::spi_xfer (unsigned char addr, unsigned char dir, size_t siz, unsigned char * datain, unsigned char const * dataout) [protected]
Definition at line 106 of file IMUspi.C.
References XIOCTL.
writeRegister()
void jevois::IMUspi::writeRegister (unsigned short reg, unsigned char val) [override], [virtual]
将值写入 IMU 寄存器之一
Implements jevois::IMU.
Definition at line 158 of file IMUspi.C.
References ICM20948_SPI_WRITE, LDEBUG, and LERROR.
Referenced by IMUspi().
writeRegisterArray()
void jevois::IMUspi::writeRegisterArray (unsigned short reg, unsigned char const * vals, size_t num) [override], [virtual]
将值数组写入相机的 IMU 寄存器
Implements jevois::IMU.
Definition at line 220 of file IMUspi.C.
References ICM20948_SPI_WRITE, LDEBUG, and LFATAL.
Member Data Documentation
itsDevName
const std::string jevois::IMUspi::itsDevName [protected]
Definition at line 63 of file IMUspi.H.
itsFd
int jevois::IMUspi::itsFd [protected]
Definition at line 64 of file IMUspi.H.
Referenced by IMUspi().
itsIMUbank
uint8_t jevois::IMUspi::itsIMUbank [protected]
Definition at line 66 of file IMUspi.H.
The documentation for this class was generated from the following files:
include/jevois/Core/IMUspi.H
src/jevois/Core/IMUspi.C