jevois::Serial Class Reference
#include <jevois/Core/Serial.H>
串行端口接口
此类是线程安全的。并发读取和写入（似乎不受操作系统或硬件支持）通过在 Serial 类中使用互斥锁进行序列化。
Definition at line 85 of file Serial.H.
Public Member Functions
Serial (std::string const &instance, UserInterface::Type type)
Constructor.
virtual ~Serial ()
destructor
void setBlocking (bool blocking, std::chrono::milliseconds const &timeout)
设置是否阻塞访问
void toggleDTR (std::chrono::milliseconds const &dur)
暂时关闭 DTR 模式。
void sendBreak (void)
在特定持续时间内传输连续的零值位流。
bool readSome (std::string &str) override
如果可用，则读取一些字节，并在完成时返回 true 和一个字符串
void writeString (std::string const &str) override
使用 serial::linestyle 的行终止约定写入字符串
void fileGet (std::string const &abspath)
将文件从本地 microSD 发送到主机
void filePut (std::string const &abspath)
从主机接收文件并将其写入本地 microSD
void flush (void)
Flush all inputs.
UserInterface::Type type () const override
返回我们的端口类型，这里是 Hard 或 USB
Protected Member Functions
void postInit () override
Called after all sub-Components are init()ed.
void postUninit () override
Called after all sub-Components are uninit()ed.
Related Functions
(Note that these are not member functions.)
JEVOIS_DECLARE_PARAMETER (devname, std::string, `Device file name`, ``, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (baudrate, unsigned int, `Baudrate`, 115200, { 110, 300, 600, 1200, 2400, 4800, 9600, 14400, 19200, 38400, 57600, 115200, 230400, 460800, 921600, 1000000, 1152000, 1500000, 2000000, 2500000, 3000000, 3500000, 4000000 }, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (format, std::string, `Data format`, `8N1`, boost::regex(`^[5-8][NEO][12]$`), ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (flowsoft, bool, `Use soft (XON/XOFF) flow control`, false, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (flowhard, bool, `Use hard (RTS/CTS) flow control`, false, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (drop, bool, `Silently drop write data when write buffer is full. Useful to ` `avoid blocking when writing messages to serial-over-USB port and the host is ` `not listening to it. Note that even when drop is false, we will still drop ` `data after repeated attempts to send it, and will report an error (as opposed to ` `silently dropping when drop is true).`, true, ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (LineStyle,(LF)(CR)(CRLF)(Zero)(Sloppy))
Enum for Parameter.
JEVOIS_DECLARE_PARAMETER (linestyle, LineStyle, `End of line style: LF is for 0x0a [\\n] CR is for 0x0d [\\r] ` `CRLF is for 0x0d 0x0a [\\r\\n] Zero is for 0x00 [\\0] Sloppy accepts any of ` `CR, LF, CRLF, 0xd0 (issued by some keyboards instead of Return), and Zero as input ` `and issues CRLF in outputs.`, LineStyle::Sloppy, LineStyle_Values, ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (TerminalMode,(Plain)(VT100))
Enum for Parameter.
JEVOIS_DECLARE_PARAMETER (mode, TerminalMode, `Terminal emulation mode for input`, TerminalMode::Plain, TerminalMode_Values, ParamCateg)
Parameter.
Additional Inherited Members
Constructor & Destructor Documentation
Serial()
jevois::Serial::Serial (std::string const & instance, UserInterface::Type type)
Constructor.
Definition at line 61 of file Serial.C.
 Serial()
jevois::Serial::~Serial () [virtual]
destructor
Definition at line 410 of file Serial.C.
Member Function Documentation
fileGet()
void jevois::Serial::fileGet (std::string const & abspath)
将文件从本地 microSD 发送到主机
abspath 应为文件的完整绝对路径。 在整个交易期间，端口将被锁定。
Definition at line 418 of file Serial.C.
References jevois::to_string().
Referenced by jevois::Engine::parseCommand().
filePut()
void jevois::Serial::filePut (std::string const & abspath)
从主机接收文件并将其写入本地 microSD
abspath 应为文件的完整绝对路径。整个交易期间端口将被锁定。
Definition at line 442 of file Serial.C.
References jevois::split(), and jevois::stringStartsWith().
Referenced by jevois::Engine::parseCommand().
flush()
void jevois::Serial::flush (void)
Flush all inputs.
Definition at line 400 of file Serial.C.
References LDEBUG.
postInit()
void jevois::Serial::postInit () [override], [protected], [virtual]
Called after all sub-Components are init()ed.
Reimplemented from jevois::Component.
Definition at line 66 of file Serial.C.
postUninit()
void jevois::Serial::postUninit () [override], [protected], [virtual]
Called after all sub-Components are uninit()ed.
Reimplemented from jevois::Component.
Definition at line 200 of file Serial.C.
References LERROR.
readSome()
bool jevois::Serial::readSome (std::string & str) [override], [virtual]
如果可用，则读取一些字节，并在完成时返回 true 和一个字符串
Implements jevois::UserInterface.
Reimplemented in jevois::GUIserial.
Definition at line 262 of file Serial.C.
References SERFATAL.
Referenced by jevois::GUIserial::readSome().
sendBreak()
void jevois::Serial::sendBreak (void)
在特定持续时间内传输连续的零值位流。
Definition at line 253 of file Serial.C.
setBlocking()
void jevois::Serial::setBlocking (bool blocking, std::chrono::milliseconds const & timeout)
设置是否阻塞访问
默认为非阻塞。如果阻塞，也可以指定超时（四舍五入到十分之一秒）
Definition at line 213 of file Serial.C.
References SERFATAL.
toggleDTR()
void jevois::Serial::toggleDTR (std::chrono::milliseconds const & dur)
暂时关闭 DTR 模式。
Definition at line 234 of file Serial.C.
References SERFATAL.
type()
jevois::UserInterface::Type jevois::Serial::type () const [override], [virtual]
返回我们的端口类型，这里是 Hard 或 USB
Implements jevois::UserInterface.
Definition at line 414 of file Serial.C.
writeString()
void jevois::Serial::writeString (std::string const & str) [override], [virtual]
使用 serial::linestyle 的行终止约定写入字符串
字符串中不应包含行终止符，writeString() 将添加一个。
Implements jevois::UserInterface.
Reimplemented in jevois::GUIserial.
Definition at line 316 of file Serial.C.
Referenced by jevois::GUIserial::writeString().
Friends And Related Function Documentation
JEVOIS_DECLARE_PARAMETER() [1/8]
JEVOIS_DECLARE_PARAMETER (baudrate , unsigned int , `Baudrate` , 115200 , { 110, 300, 600, 1200, 2400, 4800, 9600, 14400, 19200, 38400, 57600, 115200, 230400, 460800, 921600, 1000000, 1152000, 1500000, 2000000, 2500000, 3000000, 3500000, 4000000 } , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [2/8]
JEVOIS_DECLARE_PARAMETER (devname , std::string , `Device file name` , `` , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [3/8]
JEVOIS_DECLARE_PARAMETER (drop , bool , `Silently drop write data when write buffer is full. Useful to ` `avoid blocking when writing messages to serial-over-USB port and the host is ` `not listening to it. Note that even when drop is false, we will still drop ` `data after repeated attempts to send it, and will report an error(as opposed to ` `silently dropping when drop is true).` , true , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [4/8]
JEVOIS_DECLARE_PARAMETER (flowhard , bool , `Use hard (RTS/CTS) flow control` , false , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [5/8]
JEVOIS_DECLARE_PARAMETER (flowsoft , bool , `Use soft (XON/XOFF) flow control` , false , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [6/8]
JEVOIS_DECLARE_PARAMETER (format , std::string , `Data format` , `8N1` , boost::regex(`^[5-8][NEO][12]$`) , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [7/8]
JEVOIS_DECLARE_PARAMETER (linestyle , LineStyle , `End of line style: LF is for 0x0a CR is for 0x0d ` `CRLF is for 0x0d 0x0a Zero is for 0x00 Sloppy accepts any of ` ` CR[\\n][\\r][\\r\\n][\\0], LF , CRLF , 0xd0(issued by some keyboards instead of Return) , and Zero as input ` `and issues CRLF in outputs.` , LineStyle::Sloppy , LineStyle_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [8/8]
JEVOIS_DECLARE_PARAMETER (mode , TerminalMode , `Terminal emulation mode for input` , TerminalMode::Plain , TerminalMode_Values , ParamCateg) [related]
Parameter.
JEVOIS_DEFINE_ENUM_CLASS() [1/2]
JEVOIS_DEFINE_ENUM_CLASS (LineStyle , (LF)(CR)(CRLF)(Zero)(Sloppy)) [related]
Enum for Parameter.
JEVOIS_DEFINE_ENUM_CLASS() [2/2]
JEVOIS_DEFINE_ENUM_CLASS (TerminalMode , (Plain)(VT100)) [related]
Enum for Parameter.
The documentation for this class was generated from the following files:
include/jevois/Core/Serial.H
src/jevois/Core/Serial.C