jevois::dnn::NetworkOpenCV Class Reference
#include <jevois/DNN/NetworkOpenCV.H>
围绕 OpenCV DNN 神经网络的包装器
Definition at line 31 of file NetworkOpenCV.H.
Public Member Functions
virtual ~NetworkOpenCV ()
Destructor.
void freeze (bool doit) override
冻结/解冻参数，用户在运行时不应更改
virtual std::vector< vsi_nn_tensor_attr_t > inputShapes () override
Get shapes of all input tensors.
virtual std::vector< vsi_nn_tensor_attr_t > outputShapes () override
Get shapes of all output tensors.
Protected Member Functions
void load () override
Load from disk.
std::vector< cv::Mat > doprocess (std::vector< cv::Mat > const &blobs, std::vector< std::string > &info) override
Process input blobs and obtain output blobs.
Additional Inherited Members
Constructor & Destructor Documentation
 NetworkOpenCV()
jevois::dnn::NetworkOpenCV::~NetworkOpenCV () [virtual]
Destructor.
Definition at line 22 of file NetworkOpenCV.C.
References jevois::dnn::Network::waitBeforeDestroy().
Member Function Documentation
doprocess()
std::vector< cv::Mat > jevois::dnn::NetworkOpenCV::doprocess (std::vector< cv::Mat > const & blobs, std::vector< std::string > & info) [override], [protected], [virtual]
Process input blobs and obtain output blobs.
Implements jevois::dnn::Network.
Definition at line 94 of file NetworkOpenCV.C.
References LFATAL, and jevois::num2str().
freeze()
void jevois::dnn::NetworkOpenCV::freeze (bool doit) [override], [virtual]
冻结/解冻参数，用户在运行时不应更改
Reimplemented from jevois::dnn::Network.
Definition at line 26 of file NetworkOpenCV.C.
References jevois::dnn::Network::freeze().
inputShapes()
std::vector< vsi_nn_tensor_attr_t > jevois::dnn::NetworkOpenCV::inputShapes () [override], [virtual]
Get shapes of all input tensors.
Implements jevois::dnn::Network.
Definition at line 39 of file NetworkOpenCV.C.
References jevois::dnn::parseTensorSpecs().
load()
void jevois::dnn::NetworkOpenCV::load () [override], [protected], [virtual]
Load from disk.
Implements jevois::dnn::Network.
Definition at line 51 of file NetworkOpenCV.C.
References jevois::absolutePath(), and LINFO.
outputShapes()
std::vector< vsi_nn_tensor_attr_t > jevois::dnn::NetworkOpenCV::outputShapes () [override], [virtual]
Get shapes of all output tensors.
Implements jevois::dnn::Network.
Definition at line 45 of file NetworkOpenCV.C.
References jevois::dnn::parseTensorSpecs().
The documentation for this class was generated from the following files:
include/jevois/DNN/NetworkOpenCV.H
src/jevois/DNN/NetworkOpenCV.C