jevois::dnn::PostProcessorDetect Class Reference
#include <jevois/DNN/PostProcessorDetect.H>
神经网络管道的后处理器
Definition at line 31 of file PostProcessorDetect.H.
Public Member Functions
virtual ~PostProcessorDetect ()
Destructor.
void freeze (bool doit) override
冻结/解冻用户在运行时不应更改的参数
void process (std::vector< cv::Mat > const &outs, PreProcessor *preproc) override
处理输出并绘制/发送一些结果
void report (jevois::StdModule *mod, jevois::RawImage *outimg=nullptr, jevois::OptGUIhelper *helper=nullptr, bool overlay=true, bool idle=false) override
将上一个 process() 中发生的事情报告给控制台/输出视频/GUI
Protected Member Functions
void onParamChange (postprocessor::detecttype const &param, postprocessor::DetectType const &val) override
void onParamChange (postprocessor::classes const &param, std::string const &val) override
Protected Attributes
std::map< int, std::string > itsLabels
从对象 ID 映射到类名
std::vector< ObjDetect > itsDetections
cv::Size itsImageSize
std::shared_ptr< PostProcessorDetectYOLO > itsYOLO
Related Functions
(Note that these are not member functions.)
JEVOIS_DECLARE_PARAMETER (maxnbox, unsigned int, `Max number of top-scoring boxes to report (for YOLO flavors, ` `this is the max for each scale)`, 500, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (dthresh, float, `Detection box threshold (in percent confidence) above which ` `predictions will be reported. Not all networks use a separate box threshold, ` `many only use one threshold confidence threshold (cthresh parameter). The YOLO ` `family is an example that uses both box and classification confidences`, 15.0F, jevois::Range< float >(0.0F, 100.0F), ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (DetectType,(FasterRCNN)(YOLO)(SSD)(TPUSSD)(RAWYOLO)(YOLOv10)(YOLOv10pp))
Enum.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (detecttype, DetectType, `Type of detection output format`, DetectType::YOLO, DetectType_Values, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (nms, float, `Non-maximum suppression intersection-over-union threshold in percent`, 45.0F, jevois::Range< float >(0.0F, 100.0F), ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (anchors, std::string, `For YOLO-type detection models with raw outputs, ` `list of anchors. Should be formatted as: w1, h1, w2, h2, ... ww1, hh1, ww2, hh2, ` `... ... where individual entries for a given YOLO layer are separated by commas, ` `and successive YOLO layers (from large to small, e.g., first the anchors for 52x52, ` `then for 26x26, then for 13x13) are separated by semicolons. Leave empty ` `for other models.`, ``, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (alpha, unsigned char, `Alpha channel value for drawn results`, 64, ParamCateg)
Parameter.
Constructor & Destructor Documentation
 PostProcessorDetect()
jevois::dnn::PostProcessorDetect::~PostProcessorDetect () [virtual]
Destructor.
Definition at line 31 of file PostProcessorDetect.C.
Member Function Documentation
freeze()
void jevois::dnn::PostProcessorDetect::freeze (bool doit) [override], [virtual]
冻结/解冻用户在运行时不应更改的参数
Implements jevois::dnn::PostProcessor.
Definition at line 35 of file PostProcessorDetect.C.
onParamChange() [1/2]
void jevois::dnn::PostProcessorDetect::onParamChange (postprocessor::classes const & param, std::string const & val) [override], [protected]
Definition at line 43 of file PostProcessorDetect.C.
References jevois::Component::descriptor(), and jevois::split().
onParamChange() [2/2]
void jevois::dnn::PostProcessorDetect::onParamChange (postprocessor::detecttype const & param, postprocessor::DetectType const & val) [override], [protected]
Definition at line 55 of file PostProcessorDetect.C.
process()
void jevois::dnn::PostProcessorDetect::process (std::vector< cv::Mat > const & outs, PreProcessor * preproc) [override], [virtual]
处理输出并绘制/发送一些结果
Implements jevois::dnn::PostProcessor.
Definition at line 68 of file PostProcessorDetect.C.
References jevois::dnn::PreProcessor::b2i(), jevois::dnn::PreProcessor::blobsize(), jevois::dnn::clamp(), jevois::dnn::getLabel(), jevois::dnn::PreProcessor::imagesize(), LFATAL, LTHROW, o, and jevois::dnn::shapestr().
report()
void jevois::dnn::PostProcessorDetect::report (jevois::StdModule * mod, jevois::RawImage * outimg = nullptr, jevois::OptGUIhelper * helper = nullptr, bool overlay = true, bool idle = false) [override], [virtual]
将上一个 process() 中发生的事情报告给控制台/输出视频/GUI
Implements jevois::dnn::PostProcessor.
Definition at line 393 of file PostProcessorDetect.C.
References jevois::rawimage::drawRect(), jevois::GUIhelper::drawRect(), jevois::GUIhelper::drawText(), jevois::rawimage::Font10x20, jevois::yuyv::LightGreen, o, jevois::StdModule::sendSerialObjDetImg2D(), jevois::sformat(), jevois::dnn::stringToRGBA(), and jevois::rawimage::writeText().
Friends And Related Function Documentation
JEVOIS_DECLARE_PARAMETER() [1/4]
JEVOIS_DECLARE_PARAMETER (alpha , unsigned char , `Alpha channel value for drawn results` , 64 , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [2/4]
JEVOIS_DECLARE_PARAMETER (dthresh , float , `Detection box threshold (in percent confidence) above which ` `predictions will be reported. Not all networks use a separate box threshold, ` `many only use one threshold confidence threshold(cthresh parameter). The YOLO ` `family is an example that uses both box and classification confidences` , 15. 0F, jevois::Range< float > 0.0F, 100.0F, ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [3/4]
JEVOIS_DECLARE_PARAMETER (maxnbox , unsigned int , `Max number of top-scoring boxes to report (for YOLO flavors, ` `this is the max for each scale)` , 500 , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [4/4]
JEVOIS_DECLARE_PARAMETER (nms , float , `Non-maximum suppression intersection-over-union threshold in percent` , 45. 0F, jevois::Range< float > 0.0F, 100.0F, ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [1/2]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (anchors , std::string , `For YOLO-type detection models with raw outputs, ` `list of anchors. Should be formatted as:w1 , h1 , w2 , h2 , ww1, hh1 , ww2 , hh2 , ` `... ... where individual entries for a given YOLO layer are separated by commas, ` `and successive YOLO layers(from large to small, e.g., first the anchors for 52x52, ` `then for 26x26, then for 13x13) are separated by semicolons. Leave empty ` `for other models.` , `` , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [2/2]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (detecttype , DetectType , `Type of detection output format` , DetectType::YOLO , DetectType_Values , ParamCateg) [related]
Parameter.
JEVOIS_DEFINE_ENUM_CLASS()
JEVOIS_DEFINE_ENUM_CLASS (DetectType , (FasterRCNN)(YOLO)(SSD)(TPUSSD)(RAWYOLO)(YOLOv10)(YOLOv10pp)) [related]
Enum.
Member Data Documentation
itsDetections
std::vector<ObjDetect> jevois::dnn::PostProcessorDetect::itsDetections [protected]
Definition at line 58 of file PostProcessorDetect.H.
itsImageSize
cv::Size jevois::dnn::PostProcessorDetect::itsImageSize [protected]
Definition at line 59 of file PostProcessorDetect.H.
itsLabels
std::map<int, std::string> jevois::dnn::PostProcessorDetect::itsLabels [protected]
从对象 ID 映射到类名
Definition at line 57 of file PostProcessorDetect.H.
itsYOLO
std::shared_ptr<PostProcessorDetectYOLO> jevois::dnn::PostProcessorDetect::itsYOLO [protected]
Definition at line 60 of file PostProcessorDetect.H.
The documentation for this class was generated from the following files:
include/jevois/DNN/PostProcessorDetect.H
include/jevois/DNN/PostProcessor.H
src/jevois/DNN/PostProcessorDetect.C