jevois::dnn::PostProcessorClassify Class Reference
#include <jevois/DNN/PostProcessorClassify.H>
神经网络管道的后处理器
这是深度神经网络处理管道的最后一步。
Definition at line 29 of file PostProcessorClassify.H.
Public Member Functions
virtual ~PostProcessorClassify ()
Destructor.
void freeze (bool doit) override
冻结/解冻用户在运行时不应更改的参数
void process (std::vector< cv::Mat > const &outs, PreProcessor *preproc) override
处理输出并绘制/发送一些结果
void report (jevois::StdModule *mod, jevois::RawImage *outimg=nullptr, jevois::OptGUIhelper *helper=nullptr, bool overlay=true, bool idle=false) override
将上一个 process() 中发生的事情报告给控制台/输出视频/GUI
Protected Member Functions
void onParamChange (postprocessor::classes const &param, std::string const &val) override
Protected Attributes
std::map< int, std::string > itsLabels
从对象 ID 映射到类名
Related Functions
(Note that these are not member functions.)
JEVOIS_DECLARE_PARAMETER (classoffset, int, `Offset added to model output when looking up class name. Useful if ` `your model uses a background class but your class file does not (use -1), or if your ` `model does not use a background class but your class file has one (use 1). If unsure, ` `use 0 and check whether reported class names are off.`, 0, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (classes, std::string, `Path to text file with names of object classes`, ``, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (top, unsigned int, `Max number of top-scoring predictions that score above ` `threshold to report`, 5, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (cthresh, float, `Classification threshold (in percent confidence) above which ` `predictions will be reported`, 20.0F, jevois::Range< float >(0.0F, 100.0F), ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (softmax, bool, `Apply a softmax to classification outputs`, false, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (scorescale, float, `Scaling factors applied to recognition scores. Mainly ` `for debugging if your scores seem too high or too low. If too high, usually ` `that means that you should turn on parameter softmax instead.`, 1.0F, ParamCateg)
Parameter.
Constructor & Destructor Documentation
 PostProcessorClassify()
jevois::dnn::PostProcessorClassify::~PostProcessorClassify () [virtual]
Destructor.
Definition at line 27 of file PostProcessorClassify.C.
Member Function Documentation
freeze()
void jevois::dnn::PostProcessorClassify::freeze (bool doit) [override], [virtual]
冻结/解冻用户在运行时不应更改的参数
Implements jevois::dnn::PostProcessor.
Definition at line 31 of file PostProcessorClassify.C.
onParamChange()
void jevois::dnn::PostProcessorClassify::onParamChange (postprocessor::classes const & param, std::string const & val) [override], [protected]
Definition at line 37 of file PostProcessorClassify.C.
References jevois::Component::descriptor(), and jevois::split().
process()
void jevois::dnn::PostProcessorClassify::process (std::vector< cv::Mat > const & outs, PreProcessor * preproc) [override], [virtual]
处理输出并绘制/发送一些结果
Implements jevois::dnn::PostProcessor.
Definition at line 50 of file PostProcessorClassify.C.
References jevois::dnn::getLabel(), LERROR, LFATAL, o, jevois::dnn::softmax(), and jevois::dnn::topK().
report()
void jevois::dnn::PostProcessorClassify::report (jevois::StdModule * mod, jevois::RawImage * outimg = nullptr, jevois::OptGUIhelper * helper = nullptr, bool overlay = true, bool idle = false) [override], [virtual]
将上一个 process() 中发生的事情报告给控制台/输出视频/GUI
Implements jevois::dnn::PostProcessor.
Definition at line 85 of file PostProcessorClassify.C.
References jevois::GUIhelper::itext(), o, jevois::StdModule::sendSerialObjReco(), jevois::sformat(), jevois::yuyv::White, and jevois::rawimage::writeText().
Friends And Related Function Documentation
JEVOIS_DECLARE_PARAMETER() [1/5]
JEVOIS_DECLARE_PARAMETER (classoffset , int , `Offset added to model output when looking up class name. Useful if ` `your model uses a background class but your class file does not use -1, or if your ` `model does not use a background class but your class file has one(use 1). If unsure, ` `use 0 and check whether reported class names are off.` , 0 , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [2/5]
JEVOIS_DECLARE_PARAMETER (cthresh , float , `Classification threshold (in percent confidence) above which ` `predictions will be reported` , 20. 0F, jevois::Range< float > 0.0F, 100.0F, ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [3/5]
JEVOIS_DECLARE_PARAMETER (scorescale , float , `Scaling factors applied to recognition scores. Mainly ` `for debugging if your scores seem too high or too low. If too high, usually ` `that means that you should turn on parameter softmax instead.` , 1. 0F, ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [4/5]
JEVOIS_DECLARE_PARAMETER (softmax , bool , `Apply a softmax to classification outputs` , false , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [5/5]
JEVOIS_DECLARE_PARAMETER (top , unsigned int , `Max number of top-scoring predictions that score above ` `threshold to report` , 5 , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK()
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (classes , std::string , `Path to text file with names of object classes` , `` , ParamCateg) [related]
Parameter.
Member Data Documentation
itsLabels
std::map<int, std::string> jevois::dnn::PostProcessorClassify::itsLabels [protected]
从对象 ID 映射到类名
Definition at line 54 of file PostProcessorClassify.H.
The documentation for this class was generated from the following files:
include/jevois/DNN/PostProcessorClassify.H
include/jevois/DNN/PostProcessor.H
src/jevois/DNN/PostProcessorClassify.C