jevois::InputFrame Class Reference
#include <jevois/Core/InputFrame.H>
原始相机输入帧周围的异常安全包装器
此包装器的操作与标准 C++11 中的 std:future 非常相似。用户可以通过调用 get() 获取相机捕获的下一张图像，如果捕获尚 未完成，则可能会阻塞，如果捕获由于某种原因（例如，相机未流式传输）失败，则可能会抛出异常。图像大小和像素类型由当 前 VideoMapping、相机部分定义。此外，还提供了一个 done() 函数，用户可以在完成通过 get() 获取的图像中的像素数据后 立即使用该函数，以允许相机驱动程序再次设置底层内存缓冲区以进行捕获。如果在 InputFrame 被销毁时尚未调用 done()， 则如果已调用 get()，它将被自动调用。在某些情况下，尽早手动调用 done() 可能会提高帧速率，而不是让 InputFrame 析构 函数执行此操作。
InputFrame 实现对输入视频帧的零拷贝、零等待访问，即：
您通过 get() 获取的图像的像素数据直接是内存映射的像素缓冲区，JeVois 芯片上的硅硬件通过直接内存访问 (DMA) 使用 该缓冲区将像素数据从相机芯片传输到处理器内存；
一旦相机硬件捕获图像，get() 就会解除阻塞并返回该图像（而不是以固定的、有规律的间隔来获取图像）。相机有多个图 像缓冲区，允许捕获一个图像缓冲区，同时将另一个图像缓冲区通过 get() 交由处理。这些缓冲区会被回收，即一旦调用 done()，底层缓冲区就会被发送回相机硬件以供将来捕获。
Definition at line 47 of file InputFrame.H.
Public Member Functions
InputFrame (InputFrame &&other)=default
移动构造函数
! 获取下一个捕获的相机图像 const RawImage & get (bool casync=false) const
bool hasScaledImage () const
检查是否有 JeVoisPro 平台 ISP 缩放的第二个输入图像可用
const RawImage & get2 (bool casync=false) const
获取下一个捕获的相机图像，ISP 缩放的第二帧
const RawImage & getp (bool casync=false) const
获取下一个要处理的捕获的相机图像
int getDmaFd (bool casync=false) const
来自传感器的原始帧，2 由 ISP 缩放。此函数用于访问 ISP 缩放的帧。如果不是 JeVois Pro 平台或摄像头流类型不是 jevois::StreamType::RawAndScaled，则抛出。此文件描述符可用于在支持 DMA BUF 的接口之间共享像素缓冲区。JeVois 核 心使用它来创建从摄像头传感器到 JeVois Pro 上的硬件加速 OpenGL 显示器的零拷贝管道。如果不支持 DMA BUF（在主机上 和 JeVois A33 平台上），则返回 get () ，则会调用它，它会阻塞直到下一个摄像头帧可用。可以多次 调用 getDmaFd() ，但总是返回相同的 fd（参见 get2() ）。 */int getDmaFd2(bool casync
获取 ISP 缩放的第二个摄像头帧的 DMA-BUF 文件描述符 /*! 仅在 JeVois-Pro 平台上，摄像头 ISP 可以输出 2 个帧：1)
void done () const
指示用户处理已完成，先前已通过 get() 获取的图像
void done2 () const
表示用户处理已完成，并且已通过 get2() 先前获取了 ISP 缩放图像
cv::Mat getCvGRAY (bool casync=false) const
cv::Mat getCvBGR (bool casync=false) const
cv::Mat getCvRGB (bool casync=false) const
cv::Mat getCvRGBA (bool casync=false) const
cv::Mat getCvGRAYp (bool casync=false) const
cv::Mat getCvBGRp (bool casync=false) const
cv::Mat getCvRGBp (bool casync=false) const
cv::Mat getCvRGBAp (bool casync=false) const
~InputFrame ()
析构函数，根据需要将缓冲区返回给驱动程序
Friends
class Engine
Constructor & Destructor Documentation
InputFrame()
jevois::InputFrame::InputFrame (InputFrame && other) [default]
移动构造函数
 InputFrame()
jevois::InputFrame::~InputFrame ()
析构函数，根据需要将缓冲区返回给驱动程序
Definition at line 31 of file InputFrame.C.
Member Function Documentation
done()
void jevois::InputFrame::done () const
指示用户处理已完成，先前已通过 get() 获取的图像
处理完 RawImage 数据后，应尽快在 get() 之后调用此函数，以便可以回收该数据并将其发送回相机驱动程序进行视频捕获 。
Definition at line 102 of file InputFrame.C.
done2()
void jevois::InputFrame::done2 () const
表示用户处理已完成，并且已通过 get2() 先前获取了 ISP 缩放图像
处理完 RawImage 数据后，应在 get() 之后尽快调用此函数，以便可以回收该数据并将其发送回相机驱动程序进行视频捕获 。
Definition at line 109 of file InputFrame.C.
get() [1/2]
来自传感器的原始帧，2 由 ISP 缩放。此函数用于访问 ISP 缩放的帧。如果不是 JeVois Pro 平台或摄像头流类型不是 jevois::StreamType::RawAndScaled，则抛出。此文件描述符可用于在支持 DMA BUF 的接口之间共享像素缓冲区。JeVois 核 心使用它来创建从摄像头传感器到 JeVois Pro 上的硬件加速 OpenGL 显示器的零拷贝管道。如果不支持 DMA BUF（在主机上 和 JeVois A33 平台上），则返回 jevois::InputFrame::get ()
获取 ISP 缩放的第二个摄像头帧的 DMA-BUF 文件描述符 /*! 仅在 JeVois-Pro 平台上，摄像头 ISP 可以输出 2 个帧：1)
get() [2/2]
const jevois::RawImage & jevois::InputFrame::get (bool casync = false) const
如果相机未流式传输或阻塞直到图像可用（已捕获），则抛出。 可以多次调用 get()，但始终会返回相同的图像。 要从相 机获取连续的帧，必须由 JeVois Engine 向您提供连续的 InputFrame 包装器。
Definition at line 50 of file InputFrame.C.
Referenced by jevois::GUIhelper::drawInputFrame(), jevois::GUIhelper::iinfo(), and jevois::GPUimage::set().
get2()
const jevois::RawImage & jevois::InputFrame::get2 (bool casync = false) const
获取下一个捕获的相机图像，ISP 缩放的第二帧
仅在 JeVois-Pro 平台上，相机 ISP 可以输出 2 帧：1) 来自传感器的原始帧，2) 由 ISP 缩放。此函数用于访问 ISP 缩放 的帧。如果不是 JeVois-Pro 平台或相机流类型不是 jevois::StreamType::RawAndScaled，则抛出。如果相机没有流式传输 或阻塞直到图像可用（已捕获），则抛出。可以多次调用 get2()，但始终会返回相同的图像。要从相机获取连续的帧， JeVois Engine 必须向您提供连续的 InputFrame 包装器。
Definition at line 67 of file InputFrame.C.
References jevois::RawImage::buf.
Referenced by jevois::GUIhelper::drawInputFrame(), jevois::GUIhelper::drawInputFrame2(), jevois::GUIhelper::iinfo(), and jevois::GPUimage::set2().
getCvBGR()
cv::Mat jevois::InputFrame::getCvBGR (bool casync = false) const
Definition at line 125 of file InputFrame.C.
References jevois::rawimage::convertToCvBGR().
getCvBGRp()
cv::Mat jevois::InputFrame::getCvBGRp (bool casync = false) const
Definition at line 161 of file InputFrame.C.
References jevois::rawimage::convertToCvBGR().
getCvGRAY()
cv::Mat jevois::InputFrame::getCvGRAY (bool casync = false) const
Definition at line 116 of file InputFrame.C.
References jevois::rawimage::convertToCvGray().
getCvGRAYp()
cv::Mat jevois::InputFrame::getCvGRAYp (bool casync = false) const
Definition at line 152 of file InputFrame.C.
References jevois::rawimage::convertToCvGray().
getCvRGB()
cv::Mat jevois::InputFrame::getCvRGB (bool casync = false) const
Definition at line 134 of file InputFrame.C.
References jevois::rawimage::convertToCvRGB().
getCvRGBA()
cv::Mat jevois::InputFrame::getCvRGBA (bool casync = false) const
Definition at line 143 of file InputFrame.C.
References jevois::rawimage::convertToCvRGBA().
getCvRGBAp()
cv::Mat jevois::InputFrame::getCvRGBAp (bool casync = false) const
Definition at line 179 of file InputFrame.C.
References jevois::rawimage::convertToCvRGBA().
getCvRGBp()
cv::Mat jevois::InputFrame::getCvRGBp (bool casync = false) const
Definition at line 170 of file InputFrame.C.
References jevois::rawimage::convertToCvRGB().
getDmaFd()
int jevois::InputFrame::getDmaFd (bool casync = false) const
Definition at line 86 of file InputFrame.C.
getp()
const jevois::RawImage & jevois::InputFrame::getp (bool casync = false) const
获取下一个要处理的捕获的相机图像
如果 hasScaledImage() 为 false，则与 get() 相同，如果 hasScaledImage() 为 true，则与 get2() 相同。
Definition at line 79 of file InputFrame.C.
hasScaledImage()
bool jevois::InputFrame::hasScaledImage () const
检查是否有 JeVoisPro 平台 ISP 缩放的第二个输入图像可用
除非我们在 JeVois-Pro 平台上并且相机格式修饰符 jevois::CropType::CropScale 当前正在使用中，否则返回 false。
Definition at line 61 of file InputFrame.C.
Referenced by jevois::GUIhelper::drawInputFrame(), and jevois::GUIhelper::iinfo().
Friends And Related Function Documentation
Engine
friend class Engine [friend]
Definition at line 162 of file InputFrame.H.
The documentation for this class was generated from the following files:
include/jevois/Core/InputFrame.H
src/jevois/Core/InputFrame.C