jevois::dnn::PostProcessorYuNet Class Reference
#include <jevois/DNN/PostProcessorYuNet.H>
YuNet 人脸特征点检测器的后处理器
这是深度神经网络处理管道中的最后一步。代码源自 https://github.com/khadas/OpenCV_NPU_Demo.git
Definition at line 56 of file PostProcessorYuNet.H.
Public Member Functions
virtual ~PostProcessorYuNet ()
Destructor.
virtual void freeze (bool doit) override
冻结/解冻用户在运行时不应更改的参数
void process (std::vector< cv::Mat > const &outs, PreProcessor *preproc) override
处理输出并绘制/发送一些结果
void report (jevois::StdModule *mod, jevois::RawImage *outimg=nullptr, jevois::OptGUIhelper *helper=nullptr, bool overlay=true, bool idle=false) override
将上一个 process() 中发生的事情报告给控制台/输出视频/GUI
Protected Attributes
std::vector< yunet::Face > itsDetections
cv::Size itsImageSize
std::shared_ptr< yunet::PriorBox > itsPriorBox
Additional Inherited Members
Constructor & Destructor Documentation
 PostProcessorYuNet()
jevois::dnn::PostProcessorYuNet::~PostProcessorYuNet () [virtual]
Destructor.
Definition at line 169 of file PostProcessorYuNet.C.
Member Function Documentation
freeze()
void jevois::dnn::PostProcessorYuNet::freeze (bool doit) [override], [virtual]
冻结/解冻用户在运行时不应更改的参数
Implements jevois::dnn::PostProcessor.
Definition at line 173 of file PostProcessorYuNet.C.
process()
void jevois::dnn::PostProcessorYuNet::process (std::vector< cv::Mat > const & outs, PreProcessor * preproc) [override], [virtual]
处理输出并绘制/发送一些结果
Implements jevois::dnn::PostProcessor.
Definition at line 177 of file PostProcessorYuNet.C.
References jevois::dnn::PreProcessor::b2i(), jevois::dnn::PreProcessor::blobsize(), jevois::dnn::clamp(), jevois::dnn::PreProcessor::imagesize(), and LFATAL.
report()
void jevois::dnn::PostProcessorYuNet::report (jevois::StdModule * mod, jevois::RawImage * outimg = nullptr, jevois::OptGUIhelper * helper = nullptr, bool overlay = true, bool idle = false) [override], [virtual]
将上一个 process() 中发生的事情报告给控制台/输出视频/GUI
Implements jevois::dnn::PostProcessor.
Definition at line 234 of file PostProcessorYuNet.C.
References jevois::rawimage::drawCircle(), jevois::GUIhelper::drawCircle(), jevois::rawimage::drawLine(), jevois::GUIhelper::drawLine(), jevois::rawimage::drawRect(), jevois::GUIhelper::drawRect(), jevois::GUIhelper::drawText(), jevois::rawimage::Font10x20, jevois::yuyv::LightGreen, jevois::sformat(), jevois::RawImage::width, and jevois::rawimage::writeText().
Member Data Documentation
itsDetections
std::vector<yunet::Face> jevois::dnn::PostProcessorYuNet::itsDetections [protected]
Definition at line 79 of file PostProcessorYuNet.H.
itsImageSize
cv::Size jevois::dnn::PostProcessorYuNet::itsImageSize [protected]
Definition at line 80 of file PostProcessorYuNet.H.
itsPriorBox
std::shared_ptr<yunet::PriorBox> jevois::dnn::PostProcessorYuNet::itsPriorBox [protected]
Definition at line 81 of file PostProcessorYuNet.H.
The documentation for this class was generated from the following files:
include/jevois/DNN/PostProcessorYuNet.H
src/jevois/DNN/PostProcessorYuNet.C