jevois::Camera Class Reference
#include <jevois/Core/Camera.H>
JeVois camera driver class - 从 Video4Linux 相机传感器抓取帧
在平台硬件上，Camera 类提供对并行相机总线 (CSI-DVP) 上的相机传感器的访问。在其他硬件上，它可以提供对任何 Video4Linux2 相机（例如，USB 网络摄像头）的访问，但有一些限制，例如：
无法读取/写入原始相机寄存器。
通常无法选择任何帧/秒，而是限制为几个固定值，如 15fps、30fps。
通常限制为最大 30fps（没有 60fps 或 120fps 模式）
通常可用的控件数量有限（曝光、增益等）。
相机运行一个线程来自动处理帧的捕获。用户可以使用 get() 访问下一个抓取的帧，这可能会阻塞，直到帧被完全捕获。 一旦他们完成了通过 get() 获得的帧，用户应该通过调用 done() 将其交还给相机。当使用 JeVois Engine 和 Module 时， 通过使用 InputFrame 类，get() 和 done() 会以异常安全的方式自动调用。实际上，视频抓取使用一组固定的图像缓冲区， 这些缓冲区由 Linux 内核在配置视频格式时分配，然后相机硬件循环通过缓冲区。在平台上，相机图像缓冲区分配在 ION carveout 内存区域中，这是在 Linux 内核中配置的保留内存区域，USB 输出缓冲区也分配在该区域中。为了避免保留 太多不会使用的内存，ION carveout 保留默认很小，但足以容纳 3 个 1280x1024 YUYV 缓冲区。
相机实现了对输入视频帧的零复制、零等待访问，即：
您通过 get() 获取的图像的像素数据直接是内存映射的像素缓冲区，JeVois 芯片上的硅硬件通过直接内存访问 (DMA) 使 用该缓冲区将像素数据从相机芯片传输到处理器内存；
一旦相机硬件捕获图像，get() 就会解除阻塞并返回该图像（而不是以固定的、有规律的间隔来获取图像）。相机有多个 图像缓冲区，允许捕获一个图像缓冲区，同时将另一个图像缓冲区通过 get() 交由其处理。这些缓冲区会被回收，即一旦 调用 done()，底层缓冲区就会被发送回相机硬件以供将来捕获。
如果用户代码处理帧的速度不够快，相机就会丢帧。也就是说，如果所有缓冲区都已抓取但尚未通过 get() 移交并由 done() 返回，则下一个相机传感器帧将被丢弃。
大多数程序员永远不会直接使用 Camera，而是使用 Engine 和 InputFrame。
Definition at line 54 of file Camera.H.
Public Member Functions
Camera (std::string const &devname, jevois::CameraSensor s=jevois::CameraSensor::any, unsigned int const nbufs=0)
构造并打开设备
~Camera ()
关闭设备并释放所有资源
void streamOn () override
Start streaming.
void abortStream () override
Abort streaming.
void streamOff () override
Stop streaming.
void get (RawImage &img) override
获取下一个捕获的缓冲区
bool hasScaledImage () const override
void get2 (RawImage &img) override
void done (RawImage &img) override
void done2 (RawImage &img) override
void queryControl (struct v4l2_queryctrl &qc) const override
void queryMenu (struct v4l2_querymenu &qm) const override
获取菜单类型控件的可用菜单项名称，如果硬件不支持则抛出
void getControl (struct v4l2_control &ctrl) const
获取 control 的当前值，如果硬件不支持则抛出
void setControl (struct v4l2_control const &ctrl) override
设置 control，如果 control 不受支持或硬件拒绝该值则抛出
void setFormat (VideoMapping const &m) override
设置视频格式和帧率
void writeRegister (unsigned short reg, unsigned short val)
将值写入相机的某个寄存器
unsigned short readRegister (unsigned short reg)
从相机的一个寄存器读取一个值
int lock ()
锁定相机并返回其文件描述符
void unlock ()
解锁先前通过 lock() 锁定的相机
Protected Types
enum Flags { JEVOIS_SENSOR_COLOR = 0x00,
JEVOIS_SENSOR_MONO = 0x01,
JEVOIS_SENSOR_ICM20948 = 0x02
 }
Sensor flags.
Protected Member Functions
Flags readFlags ()
Get the sensor flags.
Additional Inherited Members
Member Enumeration Documentation
Flags
enum jevois::Camera::Flags [protected]
Sensor flags.
Keep this in sync with jevois-sdk/linux-3.4/drivers/media/video/sunxi-vfe/device/camera.h
Enumerator
JEVOIS_SENSOR_COLOR
JEVOIS_SENSOR_MONO
JEVOIS_SENSOR_ICM20948
Definition at line 143 of file Camera.H.
Constructor & Destructor Documentation
Camera()
jevois::Camera::Camera (std::string const & devname, jevois::CameraSensor s = jevois::CameraSensor::any, unsigned int const nbufs = 0)
构造并打开设备
Parameters
devname 设备名称，例如 /dev/video0
s 当前安装的摄像头传感器
nbufs 视频抓取缓冲区的数量，或 0 表示自动。
Definition at line 34 of file Camera.C.
References JEVOIS_SENSOR_ICM20948, JEVOIS_SENSOR_MONO, JEVOIS_TRACE, LDEBUG, and readFlags().
 Camera()
jevois::Camera::~Camera ()
关闭设备并释放所有资源
Definition at line 150 of file Camera.C.
References JEVOIS_TRACE, and jevois::warnAndIgnoreException().
Member Function Documentation
abortStream()
void jevois::Camera::abortStream () [override], [virtual]
Abort streaming.
这只会取消未来的 get() 和 done() 调用，仍应调用 streamOff() 来关闭流式传输。
Implements jevois::VideoInput.
Definition at line 171 of file Camera.C.
References JEVOIS_TIMED_LOCK, JEVOIS_TRACE, and jevois::warnAndIgnoreException().
done()
void jevois::Camera::done (jevois::RawImage & img) [override], [virtual]
Implements jevois::VideoInput.
Definition at line 214 of file Camera.C.
References JEVOIS_TIMED_LOCK, JEVOIS_TRACE, and LFATAL.
Referenced by main().
done2()
void jevois::Camera::done2 (jevois::RawImage & img) [override], [virtual]
Reimplemented from jevois::VideoInput.
Definition at line 223 of file Camera.C.
References JEVOIS_TIMED_LOCK, JEVOIS_TRACE, and LFATAL.
get()
void jevois::Camera::get (RawImage & img) [override], [virtual]
获取下一个捕获的缓冲区
如果我们未进行流式传输或阻塞直到图像可用（已捕获），则抛出。图像 img 应该由调用者分配，并将由我们从此处的设 备接收到的内容填充。
Implements jevois::VideoInput.
Definition at line 189 of file Camera.C.
References JEVOIS_TIMED_LOCK, JEVOIS_TRACE, and LFATAL.
Referenced by main().
get2()
void jevois::Camera::get2 (jevois::RawImage & img) [override], [virtual]
Reimplemented from jevois::VideoInput.
Definition at line 204 of file Camera.C.
References JEVOIS_TIMED_LOCK, JEVOIS_TRACE, and LFATAL.
getControl()
void jevois::Camera::getControl (struct v4l2_control & ctrl) const [virtual]
获取 control 的当前值，如果硬件不支持则抛出
这只是传递到 VIDIOC_G_CTRL，用户应将 ctrl 清零，然后在 ctrl.id 中设置所需的控件 ID。
Implements jevois::VideoInput.
Definition at line 248 of file Camera.C.
References JEVOIS_TIMED_LOCK, LFATAL, and XIOCTL_QUIET.
hasScaledImage()
bool jevois::Camera::hasScaledImage () const [override], [virtual]
Reimplemented from jevois::VideoInput.
Definition at line 198 of file Camera.C.
lock()
int jevois::Camera::lock ()
锁定相机并返回其文件描述符
由 IMUi2c 使用，通过与相机传感器共享的 I2C 总线访问 IMU 寄存器。请谨慎使用并确保捕获异常，这样您就可以保证调用 unlock()， 否则您的相机将卡住并启用流式传输。
Definition at line 309 of file Camera.C.
References LFATAL.
queryControl()
void jevois::Camera::queryControl (struct v4l2_queryctrl & qc) const [override], [virtual]
Implements jevois::VideoInput.
Definition at line 232 of file Camera.C.
References JEVOIS_TIMED_LOCK, LFATAL, and XIOCTL_QUIET.
queryMenu()
void jevois::Camera::queryMenu (struct v4l2_querymenu & qm) const [override], [virtual]
获取菜单类型控件的可用菜单项名称，如果硬件不支持则抛出
调用者应将 qm 清零，然后将 id 和 index 字段设置为所需的控件 id 和菜单项索引。有关更多信息，请参阅 VIDIOC_QUERYMENU。
Implements jevois::VideoInput.
Definition at line 240 of file Camera.C.
References JEVOIS_TIMED_LOCK, LFATAL, and XIOCTL_QUIET.
readFlags()
jevois::Camera::Flags jevois::Camera::readFlags () [protected]
Get the sensor flags.
Definition at line 323 of file Camera.C.
References JEVOIS_SENSOR_COLOR, LERROR, and XIOCTL.
Referenced by Camera().
readRegister()
unsigned short jevois::Camera::readRegister (unsigned short reg)
从相机的一个寄存器读取一个值
这种非常低级的访问仅用于开发最佳相机设置，不应在正常操作中使用，否则可能会导致系统崩溃。
Definition at line 288 of file Camera.C.
References JEVOIS_TIMED_LOCK, LDEBUG, LFATAL, jevois::sformat(), and XIOCTL.
setControl()
void jevois::Camera::setControl (struct v4l2_control const & ctrl) [override], [virtual]
设置 control，如果 control 不受支持或硬件拒绝该值则抛出
这只是传递到 VIDIOC_S_CTRL
Implements jevois::VideoInput.
Definition at line 260 of file Camera.C.
References JEVOIS_TIMED_LOCK, LFATAL, and XIOCTL_QUIET.
setFormat()
void jevois::Camera::setFormat (jevois::VideoMapping const & m) [override], [virtual]
设置视频格式和帧率
Implements jevois::VideoInput.
Definition at line 49 of file Camera.C.
References jevois::VideoMapping::c2fmt, jevois::VideoMapping::c2h, jevois::VideoMapping::c2w, jevois::VideoMapping::cfmt, jevois::VideoMapping::cfps, jevois::VideoMapping::ch, jevois::VideoMapping::crop, jevois::VideoMapping::cw, ISP_META_HEIGHT, ISP_META_WIDTH, ISP_V4L2_PIX_FMT_META, JEVOIS_TIMED_LOCK, JEVOIS_TRACE, LFATAL, LINFO, jevois::sensorPrepareSetFormat(), and jevois::to_string().
Referenced by main().
streamOff()
void jevois::Camera::streamOff () [override], [virtual]
Stop streaming.
Implements jevois::VideoInput.
Definition at line 180 of file Camera.C.
References JEVOIS_TIMED_LOCK, JEVOIS_TRACE, and jevois::warnAndIgnoreException().
Referenced by main().
streamOn()
void jevois::Camera::streamOn () [override], [virtual]
Start streaming.
Implements jevois::VideoInput.
Definition at line 162 of file Camera.C.
References JEVOIS_TIMED_LOCK, JEVOIS_TRACE, and jevois::warnAndIgnoreException().
Referenced by main().
unlock()
void jevois::Camera::unlock ()
解锁先前通过 lock() 锁定的相机
Definition at line 317 of file Camera.C.
writeRegister()
void jevois::Camera::writeRegister (unsigned short reg, unsigned short val)
将值写入相机的某个寄存器
这种非常低级的访问仅用于开发最佳相机设置，不应在正常操作中使用，否则可能会导致系统崩溃。
Definition at line 272 of file Camera.C.
References JEVOIS_TIMED_LOCK, LDEBUG, LFATAL, jevois::sformat(), and XIOCTL.
The documentation for this class was generated from the following files:
include/jevois/Core/Camera.H
src/jevois/Core/Camera.C