jevois::CameraDevice Class Reference
#include <jevois/Core/CameraDevice.H>
附件类，用于保存与 V4L2 相机设备相关的所有数据
此类由 jevois::Camera 内部使用，对最终用户用处不大。
Definition at line 32 of file CameraDevice.H.
Public Member Functions
CameraDevice (std::string const &devname, unsigned int const nbufs, bool dummy)
构造函数打开设备，检查其功能，启动运行线程
~CameraDevice ()
析构函数释放所有缓冲区并关闭设备
int getFd () const
获取我们的 fd；由 Camera 用来访问 controls
void streamOn ()
Start streaming.
void abortStream ()
Abort streaming.
void streamOff ()
Stop streaming.
void get (RawImage &img)
获取下一个捕获的缓冲区
void done (RawImage &img)
表示用户已完成先前通过 get() 获取的图像处理
void setFormat (unsigned int const fmt, unsigned int const capw, unsigned int const caph, float const fps, unsigned int const cropw, unsigned int const croph, int preset=-1)
设置视频格式和帧率
Constructor & Destructor Documentation
CameraDevice()
jevois::CameraDevice::CameraDevice (std::string const & devname, unsigned int const nbufs, bool dummy)
构造函数打开设备，检查其功能，启动运行线程
当 dummy 为 true 时，我们将仅出队并重新排队缓冲区而不进行任何处理。
Definition at line 76 of file CameraDevice.C.
References jevois::async_little(), jevois::fccstr(), FDLDEBUG, FDLFATAL, FDLINFO, JEVOIS_TRACE, LFATAL, jevois::to_string(), XIOCTL, and XIOCTL_QUIET.
 CameraDevice()
jevois::CameraDevice::~CameraDevice ()
析构函数释放所有缓冲区并关闭设备
Definition at line 172 of file CameraDevice.C.
References FDLERROR, JEVOIS_TRACE, JEVOIS_WAIT_GET_FUTURE, and jevois::warnAndIgnoreException().
Member Function Documentation
abortStream()
void jevois::CameraDevice::abortStream ()
Abort streaming.
Definition at line 365 of file CameraDevice.C.
References JEVOIS_TRACE.
done()
void jevois::CameraDevice::done (jevois::RawImage & img)
表示用户已完成先前通过 get() 获取的图像处理
Definition at line 471 of file CameraDevice.C.
References jevois::RawImage::bufindex, JEVOIS_TIMED_LOCK, JEVOIS_TRACE, and LDEBUG.
get()
void jevois::CameraDevice::get (jevois::RawImage & img)
获取下一个捕获的缓冲区
Definition at line 418 of file CameraDevice.C.
References jevois::RawImage::bufindex, jevois::rawimage::convertBayerToYUYV(), jevois::rawimage::convertGreyToYUYV(), FDLFATAL, jevois::RawImage::invalidate(), JEVOIS_TRACE, and LDEBUG.
getFd()
int jevois::CameraDevice::getFd () const
获取我们的 fd；由 Camera 用来访问 controls
Definition at line 195 of file CameraDevice.C.
setFormat()
void jevois::CameraDevice::setFormat (unsigned int const fmt, unsigned int const capw, unsigned int const caph, float const fps, unsigned int const cropw, unsigned int const croph, int preset = -1)
设置视频格式和帧率
Definition at line 486 of file CameraDevice.C.
References jevois::fccstr(), FDLDEBUG, FDLERROR, FDLFATAL, FDLINFO, jevois::VideoMapping::fpsToV4l2(), JEVOIS_TIMED_LOCK, JEVOIS_TRACE, V4L2_COLORSPACE_DEFAULT, V4L2_MODE_VIDEO, XIOCTL, and XIOCTL_QUIET.
streamOff()
void jevois::CameraDevice::streamOff ()
Stop streaming.
Definition at line 377 of file CameraDevice.C.
References FDLDEBUG, JEVOIS_TRACE, LDEBUG, jevois::warnAndIgnoreException(), and XIOCTL_QUIET.
streamOn()
void jevois::CameraDevice::streamOn ()
Start streaming.
Definition at line 314 of file CameraDevice.C.
References FDLDEBUG, FDLERROR, FDLFATAL, FDLINFO, JEVOIS_TIMED_LOCK, JEVOIS_TRACE, LDEBUG, jevois::v4l2ImageSize(), and XIOCTL.
The documentation for this class was generated from the following files:
include/jevois/Core/CameraDevice.H
src/jevois/Core/CameraDevice.C