jevois::ParameterBase Class Reference
#include <jevois/Component/Parameter.H>
Base class for Parameter.
将字符串接口公开给 Parameter，而派生模板类将公开 value-based 接口。
Definition at line 113 of file Parameter.H.
Public Member Functions
ParameterBase ()
Constructor.
virtual ~ParameterBase ()
Destructor, 将从其所有者组件中删除参数
virtual const std::string & name () const =0
Get the parameter name.
virtual std::string descriptor () const =0
获取参数完全限定名称，也称为描述符，包括拥有 Component 和所有父组件的名称
virtual void strset (std::string const &valstring)=0
从其字符串表示形式设置值
virtual const std::string strget () const =0
Get the value as a string.
virtual const ParameterSummary summary () const =0
Get summary info about this parameter.
void freeze (bool doit)
冻结或取消冻结一个参数；冻结的参数不能被 set()，但是仍然允许 get()
bool frozen () const
Returns whether parameter is frozen.
virtual void reset ()=0
Reset this parameter to its default value.
Protected Attributes
boost::shared_mutex itsMutex
用于保护参数值的互斥锁
volatile bool itsFrozen
为 true 时，参数被冻结（只读，不会显示在帮助消息中）
bool itsVirgin
参数尚未明确设置，需要在初始化时调用回调（如果有）
Friends
class ParameterRegistry
Constructor & Destructor Documentation
ParameterBase()
jevois::ParameterBase::ParameterBase ()
Constructor.
 ParameterBase()
virtual jevois::ParameterBase::~ParameterBase () [virtual]
Destructor, 将从其所有者组件中删除参数
Member Function Documentation
descriptor()
virtual std::string jevois::ParameterBase::descriptor () const [pure virtual]
获取参数完全限定名称，也称为描述符，包括拥有 Component 和所有父组件的名称
Implemented in jevois::ParameterCore< T >.
freeze()
void jevois::ParameterBase::freeze (bool doit)
冻结或取消冻结一个参数；冻结的参数不能被 set()，但是仍然允许 get()
Referenced by jevois::Component::freezeParam().
frozen()
bool jevois::ParameterBase::frozen () const
Returns whether parameter is frozen.
name()
virtual const std::string& jevois::ParameterBase::name () const [pure virtual]
Get the parameter name.
Implemented in jevois::ParameterCore< T >.
Referenced by jevois::ParameterRegistry::addParameter(), and jevois::ParameterRegistry::removeParameter().
reset()
virtual void jevois::ParameterBase::reset () [pure virtual]
Reset this parameter to its default value.
Implemented in jevois::ParameterCore< T >.
strget()
virtual const std::string jevois::ParameterBase::strget () const [pure virtual]
Get the value as a string.
Implemented in jevois::ParameterCore< T >.
Referenced by jevois::Component::getParamString().
strset()
virtual void jevois::ParameterBase::strset (std::string const & valstring) [pure virtual]
从其字符串表示形式设置值
如果给定的字符串不能转换为 Parameter 值，或者该值根据我们的有效值规范无效或被 Parameter 的回调拒绝（如果有）， 则
Exceptions
std::range_error。
Implemented in jevois::ParameterCore< T >.
Referenced by jevois::Component::setParamString().
summary()
virtual const ParameterSummary jevois::ParameterBase::summary () const [pure virtual]
Get summary info about this parameter.
Implemented in jevois::ParameterCore< T >.
Friends And Related Function Documentation
ParameterRegistry
friend class ParameterRegistry [friend]
Definition at line 154 of file Parameter.H.
Member Data Documentation
itsFrozen
volatile bool jevois::ParameterBase::itsFrozen [protected]
为 true 时，参数被冻结（只读，不会显示在帮助消息中）
Definition at line 150 of file Parameter.H.
itsMutex
boost::shared_mutex jevois::ParameterBase::itsMutex [mutable], [protected]
用于保护参数值的互斥锁
Definition at line 149 of file Parameter.H.
itsVirgin
bool jevois::ParameterBase::itsVirgin [protected]
参数尚未明确设置，需要在初始化时调用回调（如果有）
Definition at line 151 of file Parameter.H.
The documentation for this class was generated from the following file:
include/jevois/Component/Parameter.H