jevois::PythonModule Class Reference
#include <jevois/Core/PythonModule.H>
包装器模块允许用户开发用 Python 编写的新模块
此包装器模块在每一帧上调用用 Python 编写的处理函数。请注意，在定义 python 类后，sendSerial() 是如何动态添加的，作为该 类的新成员函数。
Definition at line 357 of file PythonModule.H.
Public Member Functions
PythonModule (VideoMapping const &m)
构造函数需要 Python 源代码文件的完整路径
void preInit () override
加载 python 代码并可选择调用 init() python 模块函数（如果已实现）
virtual ~PythonModule ()
Virtual destructor for safe inheritance.
virtual void process (InputFrame &&inframe, OutputFrame &&outframe) override
Processing function, version that receives a frame from camera and sends a frame out over USB.
virtual void process (InputFrame &&inframe) override
Processing function, version that receives a frame from camera and does not use USB.
virtual void process (InputFrame &&inframe, GUIhelper &helper)
Processing function, version that receives a frame from camera, no USB, but GUI output on JeVois-Pro.
virtual void parseSerial (std::string const &str, std::shared_ptr< UserInterface > s) override
Receive a string from a serial port which contains a user command.
virtual void supportedCommands (std::ostream &os) override
Human-readable description of this Module's supported custom commands.
void postUninit () override
Optionally call uninit() python module function, if implemented.
Additional Inherited Members
Constructor & Destructor Documentation
PythonModule()
jevois::PythonModule::PythonModule (jevois::VideoMapping const & m)
构造函数需要 Python 源代码文件的完整路径
请注意，与 C++ 模块相反，构造不会抛出。这样，模块始终有效且已初始化，并且其模块路径可以由 Engine 设置，这对于允许从 JeVois Inventor 保存源代码是必要的。相反，任何构造错误都存储在这个类内部，并且在访问 process()、parfseSerial() 等 时会重新抛出。
Definition at line 504 of file PythonModule.C.
References jevois::VideoMapping::ispython, and LFATAL.
 PythonModule()
jevois::PythonModule::~PythonModule () [virtual]
Virtual destructor for safe inheritance.
Definition at line 528 of file PythonModule.C.
Member Function Documentation
parseSerial()
void jevois::PythonModule::parseSerial (std::string const & str, std::shared_ptr< UserInterface > s) [override], [virtual]
Receive a string from a serial port which contains a user command.
Reimplemented from jevois::Module.
Definition at line 559 of file PythonModule.C.
References jevois::python::hasattr(), jevois::Module::parseSerial(), jevois::PythonWrapper::pyinst(), and jevois::UserInterface::writeString().
postUninit()
void jevois::PythonModule::postUninit () [override], [virtual]
Optionally call uninit() python module function, if implemented.
Reimplemented from jevois::Component.
Definition at line 521 of file PythonModule.C.
References jevois::python::hasattr(), and jevois::PythonWrapper::pyinst().
preInit()
void jevois::PythonModule::preInit () [override], [virtual]
加载 python 代码并可选择调用 init() python 模块函数（如果已实现）
Reimplemented from jevois::Component.
Definition at line 511 of file PythonModule.C.
References jevois::python::hasattr(), jevois::PythonWrapper::pyinst(), and jevois::PythonWrapper::pythonload().
process() [1/3]
void jevois::PythonModule::process (InputFrame && inframe) [override], [virtual]
Processing function, version that receives a frame from camera and does not use USB.
Reimplemented from jevois::Module.
Definition at line 540 of file PythonModule.C.
References jevois::PythonWrapper::pyinst().
process() [2/3]
void jevois::PythonModule::process (InputFrame && inframe, GUIhelper & helper) [virtual]
Processing function, version that receives a frame from camera, no USB, but GUI output on JeVois-Pro.
Reimplemented from jevois::Module.
Definition at line 549 of file PythonModule.C.
References jevois::PythonWrapper::pyinst().
process() [3/3]
void jevois::PythonModule::process (InputFrame && inframe, OutputFrame && outframe) [override], [virtual]
Processing function, version that receives a frame from camera and sends a frame out over USB.
Reimplemented from jevois::Module.
Definition at line 532 of file PythonModule.C.
References jevois::PythonWrapper::pyinst().
supportedCommands()
void jevois::PythonModule::supportedCommands (std::ostream & os) [override], [virtual]
Human-readable description of this Module's supported custom commands.
Reimplemented from jevois::Module.
Definition at line 571 of file PythonModule.C.
References jevois::python::hasattr(), jevois::PythonWrapper::pyinst(), and jevois::Module::supportedCommands().
The documentation for this class was generated from the following files:
include/jevois/Core/PythonModule.H
src/jevois/Core/PythonModule.C