jevois::Gadget Class Reference
#include <jevois/Core/Gadget.H>
JeVois 小工具驱动程序 - 向通过 USB 连接的主机计算机公开 uvcvideo 接口
Gadget 是 JeVois 实现的 Linux 内核小工具驱动程序的用户空间接口。USB 小工具驱动程序是在设备上运行的 USB 驱动程序， 而不是在主机计算机上运行的 USB 驱动程序。小工具驱动程序实现 USB 功能，例如 USB 打印机、USB 调制解调器或 USB 摄像 头。在 JeVois 中，Gadget 驱动程序使 JeVois 硬件平台显示为 UVC（USB 视频类）摄像头。由于 UVC 已经标准化，因此主机 计算机上不需要特殊驱动程序即可开始使用 UVC 设备，因为几乎所有现代操作系统都已为符合 UVC 标准的摄像头提供了内置驱 动程序。
Gadget 的内部操作相当复杂，尤其是由于它与内核端 UVC 小工具驱动程序的紧密交互。然而，对于用户来说，Gadget 只是另一 个 VideoOutput 设备：可以设置其格式，使用 get() 从中获取空白图像缓冲区，将结果绘制到这些缓冲区中，并在完成后使用 send() 将它们发送到主机。
Gadget 实现了对输出视频帧的零拷贝、零等待访问，即：
您通过 get() 获取的图像的像素数据直接是内存映射像素缓冲区，JeVois 芯片上的硅硬件将通过直接内存访问 (DMA) 使用该 缓冲区通过 USB 链路流出数据；
只要您调用 send()，该缓冲区就会排队等待通过 USB 发送（而不是以固定的、有规律的间隔流出图像）。Gadget 有多个图像 缓冲区，允许一个缓冲区通过 USB 流出，而另一个缓冲区则通过 get() 由您的应用程序填充。这些缓冲区是可回收的，即一旦 调用 send()，底层缓冲区就会通过 USB 流出，然后发送回 Gadget 以供您的代码将来访问。
大多数程序员永远不会直接使用 Gadget，而是使用 Engine 和 OutputFrame。
Definition at line 60 of file Gadget.H.
Public Member Functions
Gadget (std::string const &devname, VideoInput *camera, Engine *engine, size_t const nbufs=0, bool multicam=false)
构造并打开设备
virtual ~Gadget ()
关闭设备并释放所有资源
void setFormat (jevois::VideoMapping const &m) override
设置视频格式和帧速率
void get (RawImage &img) override
获取预分配的图像，以便我们可以填充像素数据，然后使用 send() 通过 USB 发送出去
void send (RawImage const &img) override
通过 USB 将图像发送到主机
void streamOn () override
Start streaming.
void abortStream () override
中止流式传输
void streamOff () override
Stop streaming.
Constructor & Destructor Documentation
Gadget()
jevois::Gadget::Gadget (std::string const & devname, jevois::VideoInput * camera, jevois::Engine * engine, size_t const nbufs = 0, bool multicam = false)
构造并打开设备
此小工具需要有效的非空摄像头才能工作。 为了避免在小工具的每次操作中测试非空摄像头，我们只在构造时测试一次，然 后假设摄像头将在小工具的整个生命周期内保持运行。 使用 0 作为 nbufs 以自动设置它。
Definition at line 139 of file Gadget.C.
 Gadget()
jevois::Gadget::~Gadget () [virtual]
关闭设备并释放所有资源
Definition at line 185 of file Gadget.C.
References JEVOIS_TRACE, PLERROR, and jevois::warnAndIgnoreException().
Member Function Documentation
abortStream()
void jevois::Gadget::abortStream () [override], [virtual]
中止流式传输
这只会取消未来的 get() 和 done() 调用，仍应调用 streamOff() 来关闭流式传输。
Implements jevois::VideoOutput.
Definition at line 772 of file Gadget.C.
References JEVOIS_TRACE.
get()
void jevois::Gadget::get (jevois::RawImage & img) [override], [virtual]
获取预分配的图像，以便我们可以填充像素数据，然后使用 send() 通过 USB 发送出去
Implements jevois::VideoOutput.
Definition at line 806 of file Gadget.C.
References jevois::RawImage::bufindex, JEVOIS_TRACE, LDEBUG, and LFATAL.
send()
void jevois::Gadget::send (jevois::RawImage const & img) [override], [virtual]
通过 USB 将图像发送到主机
Implements jevois::VideoOutput.
Definition at line 849 of file Gadget.C.
References jevois::RawImage::bufindex, jevois::RawImage::fmt, jevois::RawImage::height, JEVOIS_TRACE, LDEBUG, LFATAL, and jevois::RawImage::width.
setFormat()
void jevois::Gadget::setFormat (jevois::VideoMapping const & m) [override], [virtual]
设置视频格式和帧速率
Implements jevois::VideoOutput.
Definition at line 201 of file Gadget.C.
References jevois::fccstr(), jevois::VideoMapping::fpsToV4l2(), JEVOIS_TIMED_LOCK, JEVOIS_TRACE, LINFO, jevois::VideoMapping::ofmt, jevois::VideoMapping::ofps, jevois::VideoMapping::oh, jevois::VideoMapping::osize(), jevois::VideoMapping::ow, XIOCTL, and XIOCTL_QUIET.
streamOff()
void jevois::Gadget::streamOff () [override], [virtual]
Stop streaming.
Implements jevois::VideoOutput.
Definition at line 780 of file Gadget.C.
References JEVOIS_TIMED_LOCK, JEVOIS_TRACE, LDEBUG, and XIOCTL_QUIET.
streamOn()
void jevois::Gadget::streamOn () [override], [virtual]
Start streaming.
Implements jevois::VideoOutput.
Definition at line 716 of file Gadget.C.
References jevois::RawImage::buf, jevois::RawImage::bufindex, jevois::RawImage::fmt, jevois::RawImage::fps, jevois::RawImage::height, JEVOIS_TIMED_LOCK, JEVOIS_TRACE, LDEBUG, LERROR, LINFO, jevois::v4l2ImageSize(), jevois::RawImage::width, and XIOCTL.
The documentation for this class was generated from the following files:
include/jevois/Core/Gadget.H
src/jevois/Core/Gadget.C