jevois::StdModule Class Reference
#include <jevois/Core/Module.H>
支持标准化串行消息的模块的基类
可以输出标准化串行消息的模块应该从 StdModule 而不是 Module 派生。StdModule 引入了额外的参数来设置串行消息样式和精度， 以及额外的成员函数来组装、格式化和发送标准化串行消息。StdModule 函数的 process()、sendSerial()、parseSerial()、 supportedCommands() 等直接从 Module 继承。有关标准化串行消息，请参阅 标准化串行消息格式 。
Definition at line 197 of file Module.H.
Public Member Functions
StdModule (std::string const &instance)
Constructor.
virtual ~StdModule ()
用于安全继承的虚拟析构函数
void sendSerialImg1Dx (unsigned int camw, float x, float size=0.0F, std::string const &id=``, std::string const &extra=``)
发送标准化 1D 消息以获取图像 X 坐标
void sendSerialStd1Dx (float x, float size=0.0F, std::string const &id=``, std::string const &extra=``)
发送标准化 1D 消息以获取标准化 X 坐标
void sendSerialImg1Dy (unsigned int camh, float y, float size=0.0F, std::string const &id=``, std::string const &extra=``)
发送 Y 图像坐标的标准化 1D 消息
void sendSerialStd1Dy (float y, float size=0.0F, std::string const &id=``, std::string const &extra=``)
发送标准化 1D 消息以获取标准化 Y 坐标
void sendSerialImg2D (unsigned int camw, unsigned int camh, float x, float y, float w=0.0F, float h=0.0F, std::string const &id=``, std::string const &extra=``)
发送标准化的 2D 图像坐标消息
void sendSerialStd2D (float x, float y, float w=0.0F, float h=0.0F, std::string const &id=``, std::string const &extra=``)
发送标准化的 2D 标准化坐标消息
template<typename T = int>
void sendSerialContour2D (unsigned int camw, unsigned int camh, std::vector< cv::Point_< T > > points, std::string const &id=``, std::string const &extra=``)
发送图像坐标中多边形的标准化 2D 消息
void sendSerialStd3D (float x, float y, float z, float w=0.0F, float h=0.0F, float d=0.0F, float q1=0.0F, float q2=0.0F, float q3=0.0f, float q4=0.0F, std::string const &id=``, std::string const &extra=``)
发送标准化 3D 消息
void sendSerialStd3D (std::vector< cv::Point3f > points, std::string const &id=``, std::string const &extra=``)
发送标准化 3D 消息
void sendSerialObjReco (std::vector< ObjReco > const &res)
发送标准化对象识别消息
void sendSerialObjDetImg2D (unsigned int camw, unsigned int camh, float x, float y, float w, float h, std::vector< ObjReco > const &res)
发送标准化对象检测 + 识别消息
void sendSerialObjDetImg2D (unsigned int camw, unsigned int camh, ObjDetect const &det)
发送标准化的对象检测 + 识别消息
Protected Member Functions
void sendSerialMarkStart ()
发送消息 MARK START 以指示处理的开始
void sendSerialMarkStop ()
发送消息 MARK STOP 以指示处理结束
std::string getStamp () const
获取包含帧/日期/时间戳的字符串，具体取决于 serstamp 参数
Friends
class jevois::Engine
Related Functions
(Note that these are not member functions.)
JEVOIS_DEFINE_ENUM_CLASS (SerStyle,(Terse)(Normal)(Detail)(Fine))
Enum for Parameter.
JEVOIS_DECLARE_PARAMETER (serstyle, SerStyle, `Style for standardized serial messages as defined in ` `http://jevois.org/doc/UserSerialStyle.html`, SerStyle::Terse, SerStyle_Values, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (serprec, unsigned int, `Number of decimal points in standardized serial messages as ` `defined in http://jevois.org/doc/UserSerialStyle.html`, 0U, jevois::Range< unsigned int >(0U, 10U), ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (SerStamp,(None)(Frame)(Time)(FrameTime)(FrameDateTime))
Enum for Parameter.
JEVOIS_DECLARE_PARAMETER (serstamp, SerStamp, `Prepend standardized serial messages with a frame number, ` `time, frame+time, or frame+date+time. See details in ` `http://jevois.org/doc/UserSerialStyle.html`, SerStamp::None, SerStamp_Values, ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (SerMark,(None)(Start)(Stop)(Both))
Enum for Parameter.
JEVOIS_DECLARE_PARAMETER (sermark, SerMark, `Send serial message to mark the beginning (MARK START) of the ` `processing of a video frame from the camera sensor, the end (MARK STOP), or both. ` `Useful, among others, if one needs to know when no results were sent over serial ` `on a given frame. Combine with parameter serstamp if you need to know the frame number.`, SerMark::None, SerMark_Values, ParamCateg)
Parameter.
Constructor & Destructor Documentation
StdModule()
jevois::StdModule::StdModule (std::string const & instance)
Constructor.
instance 是用户定义的字符串，可用于区分同一模块的多个实例。
Definition at line 72 of file Module.C.
 StdModule()
jevois::StdModule::~StdModule () [virtual]
用于安全继承的虚拟析构函数
Definition at line 77 of file Module.C.
Member Function Documentation
getStamp()
std::string jevois::StdModule::getStamp () const [protected]
获取包含帧/日期/时间戳的字符串，具体取决于 serstamp 参数
Definition at line 81 of file Module.C.
References jevois::to_string().
sendSerialContour2D()
template<typename T >
template void jevois::StdModule::sendSerialContour2D (unsigned int camw, unsigned int camh, std::vector< cv::Point_< T > > points, std::string const & id = ``, std::string const & extra = ``)
发送图像坐标中多边形的标准化 2D 消息
如果您的物体周围有多边形，请使用此函数，例如，使用 cv::findContours() 找到的轮廓之一，或者如果您有矩形物体的 4 个角。 有关更多信息，请参阅 标准化串行消息格式 。坐标应以相机图像像素为单位，此函数将根据 用于将坐标从相机分辨率转换为标准坐标的辅助函数 将它们转换为 标准化坐标。对于 Terse 串行样式，将计算并输出点的重心；对于 Normal ，将计算并输出直立边界矩形；对于 Detailed ，将计算并输出旋转的边界矩形；对于 Fine ，将输出所有给定的点。请确保尝试减少点数，以使消息不会太长； 例如，请参阅 OpenCV approxPolyDP() 或类似函数。
Definition at line 284 of file Module.C.
References jevois::coords::imgToStd(), and jevois::replaceWhitespace().
sendSerialImg1Dx()
void jevois::StdModule::sendSerialImg1Dx (unsigned int camw, float x, float size = 0.0F, std::string const & id = ``, std::string const & extra = ``)
发送标准化 1D 消息以获取图像 X 坐标
有关更多信息，请参阅 标准化串行消息格式 。坐标应以相机图像像素为单位，此函数将根据 用于将坐标从相机分辨率转换为标准坐标的辅助函数 将它们转 换为标准化坐标。
Definition at line 124 of file Module.C.
References jevois::coords::imgToStdSize(), and jevois::coords::imgToStdX().
sendSerialImg1Dy()
void jevois::StdModule::sendSerialImg1Dy (unsigned int camh, float y, float size = 0.0F, std::string const & id = ``, std::string const & extra = ``)
发送 Y 图像坐标的标准化 1D 消息
有关更多信息，请参阅 标准化串行消息格式 。坐标应以相机图像像素为单位，此函数将根据 用于将坐标从相机分辨率转换为标准坐标的辅助函数 将它们转 换为标准化坐标。
Definition at line 173 of file Module.C.
References jevois::coords::imgToStdSize(), and jevois::coords::imgToStdY().
sendSerialImg2D()
void jevois::StdModule::sendSerialImg2D (unsigned int camw, unsigned int camh, float x, float y, float w = 0.0F, float h = 0.0F, std::string const & id = ``, std::string const & extra = ``)
发送标准化的 2D 图像坐标消息
如果您只知道位置和可选大小，请使用此功能。如果您有角，请使用其他变体。这里将假定为直立的矩形。有关更多信息，请参阅 标准化串行消息格式 。坐标应以相机图像像素为单位，此函数将根据 用于将坐标从相机分辨率转换为标准坐标的辅助函数 将它们转换为标准化坐标。
Definition at line 221 of file Module.C.
References h, jevois::coords::imgToStd(), and jevois::coords::imgToStdSize().
sendSerialMarkStart()
void jevois::StdModule::sendSerialMarkStart () [protected]
发送消息 MARK START 以指示处理的开始
可能会根据参数 serstamp 预先添加一个戳记。引擎会自动调用此功能，因此用户通常不会使用此函数。请注意，根据参数 sermark 的当前值，此函数可能不会发送任何内容。
Definition at line 519 of file Module.C.
Referenced by jevois::Engine::mainLoop().
sendSerialMarkStop()
void jevois::StdModule::sendSerialMarkStop () [protected]
发送消息 MARK STOP 以指示处理结束
可能会根据参数 serstamp 添加标记。引擎会自动调用此功能，因此用户通常不会使用此函数。请注意，根据参数 sermark 的当前值，此函数可能不会发送任何内容。
Definition at line 527 of file Module.C.
Referenced by jevois::Engine::mainLoop().
sendSerialObjDetImg2D() [1/2]
void jevois::StdModule::sendSerialObjDetImg2D (unsigned int camw, unsigned int camh, float x, float y, float w, float h, std::vector< ObjReco > const & res)
发送标准化对象检测 + 识别消息
res 应为分数和类别名称的列表，按分数降序排列。请注意，如果向量为空，则不会发送任何消息。有关对象框的信息，请参阅 sendSerialImg2D()。
Definition at line 572 of file Module.C.
References h, jevois::replaceWhitespace(), jevois::sformat(), and jevois::to_string().
Referenced by jevois::dnn::PostProcessorDetect::report().
sendSerialObjDetImg2D() [2/2]
void jevois::StdModule::sendSerialObjDetImg2D (unsigned int camw, unsigned int camh, jevois::ObjDetect const & det)
发送标准化的对象检测 + 识别消息
res 应为分数和类别名称的列表，按分数的降序排列。请注意，如果向量为空，则不会发送任何消息。有关对象框的信息，请参阅 sendSerialImg2D()。
Definition at line 602 of file Module.C.
References jevois::ObjDetect::brx, jevois::ObjDetect::bry, jevois::ObjDetect::reco, jevois::ObjDetect::tlx, and jevois::ObjDetect::tly.
sendSerialObjReco()
void jevois::StdModule::sendSerialObjReco (std::vector< ObjReco > const & res)
发送标准化对象识别消息
res 应为分数和类别名称的列表，按分数降序排列。请注意，如果向量为空，则不会发送任何消息。
Definition at line 535 of file Module.C.
References jevois::replaceWhitespace().
Referenced by jevois::dnn::PostProcessorClassify::report().
sendSerialStd1Dx()
void jevois::StdModule::sendSerialStd1Dx (float x, float size = 0.0F, std::string const & id = ``, std::string const & extra = ``)
发送标准化 1D 消息以获取标准化 X 坐标
有关更多信息，请参阅 标准化串行消息格式 。坐标应以相机图像像素为单位，此函数将根据 用于将坐标从相机分辨率转换为标准坐标的辅助函数 将它们转 换为标准化坐标。
Definition at line 138 of file Module.C.
References jevois::replaceWhitespace().
sendSerialStd1Dy()
void jevois::StdModule::sendSerialStd1Dy (float y, float size = 0.0F, std::string const & id = ``, std::string const & extra = ``)
发送标准化 1D 消息以获取标准化 Y 坐标
有关更多信息，请参阅 标准化串行消息格式 。坐标应以相机图像像素为单位，此函数将根据 用于将坐标从相机分辨率转换为标准坐标的辅助函数 将它们转 换为标准化坐标。
Definition at line 186 of file Module.C.
References jevois::replaceWhitespace().
sendSerialStd2D()
void jevois::StdModule::sendSerialStd2D (float x, float y, float w = 0.0F, float h = 0.0F, std::string const & id = ``, std::string const & extra = ``)
发送标准化的 2D 标准化坐标消息
如果您只知道位置和可选大小，请使用此功能。如果您有角，请使用其他变体。这里将假定为直立的矩形。有关更多信息，请参阅 标准化串行消息格式 。坐标应以相机图像像素为单位，此函数将根据 用于将坐标从相机分辨率转换为标准坐标的辅助函数 将它们转换为标准化坐标。
Definition at line 234 of file Module.C.
References h, and jevois::replaceWhitespace().
sendSerialStd3D() [1/2]
void jevois::StdModule::sendSerialStd3D (float x, float y, float z, float w = 0.0F, float h = 0.0F, float d = 0.0F, float q1 = 0.0F, float q2 = 0.0F, float q3 = 0.0f, float q4 = 0.0F, std::string const & id = ``, std::string const & extra = ``)
发送标准化 3D 消息
如果您只知道位置和可选的大小以及方向四元数，请使用此函数。如果您有一堆顶点，请使用其他变体。有关更多信息，请参阅 UserSerialStyle。坐标应以毫米为单位。
Definition at line 385 of file Module.C.
References h, and jevois::replaceWhitespace().
sendSerialStd3D() [2/2]
void jevois::StdModule::sendSerialStd3D (std::vector< cv::Point3f > points, std::string const & id = ``, std::string const & extra = ``)
发送标准化 3D 消息
如果您只知道位置和可选的大小以及方向四元数，请使用此函数。如果您有一堆顶点，请使用其他变体。有关更多信息，请参阅 UserSerialStyle。坐标应以毫米为单位。
Definition at line 437 of file Module.C.
References jevois::replaceWhitespace().
Friends And Related Function Documentation
jevois::Engine
friend class jevois::Engine [friend]
Definition at line 281 of file Module.H.
JEVOIS_DECLARE_PARAMETER() [1/4]
JEVOIS_DECLARE_PARAMETER (sermark , SerMark , `Send serial message to mark the beginning (MARK START) of the ` `processing of a video frame from the camera sensor, the endMARK STOP, or both. ` ` Useful, among others, if one needs to know when no results were sent over serial ` `on a given frame. Combine with parameter serstamp if you need to know the frame number.` , SerMark::None , SerMark_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [2/4]
JEVOIS_DECLARE_PARAMETER (serprec , unsigned int , `Number of decimal points in standardized serial messages as ` `defined in http://jevois.org/doc/UserSerialStyle.html` , 0U , jevois::Range< unsigned int > 0U, 10U, ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [3/4]
JEVOIS_DECLARE_PARAMETER (serstamp , SerStamp , `Prepend standardized serial messages with a frame number, ` ` time, frame+ time, or frame+date+time. See details in ` `http://jevois.org/doc/UserSerialStyle.html` , SerStamp::None , SerStamp_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [4/4]
JEVOIS_DECLARE_PARAMETER (serstyle , SerStyle , `Style for standardized serial messages as defined in ` `http://jevois.org/doc/UserSerialStyle.html` , SerStyle::Terse , SerStyle_Values , ParamCateg) [related]
Parameter.
JEVOIS_DEFINE_ENUM_CLASS() [1/3]
JEVOIS_DEFINE_ENUM_CLASS (SerMark , (None)(Start)(Stop)(Both)) [related]
Enum for Parameter.
JEVOIS_DEFINE_ENUM_CLASS() [2/3]
JEVOIS_DEFINE_ENUM_CLASS (SerStamp , (None)(Frame)(Time)(FrameTime)(FrameDateTime)) [related]
Enum for Parameter.
JEVOIS_DEFINE_ENUM_CLASS() [3/3]
JEVOIS_DEFINE_ENUM_CLASS (SerStyle , (Terse)(Normal)(Detail)(Fine)) [related]
Enum for Parameter.
The documentation for this class was generated from the following files:
include/jevois/Core/Module.H
src/jevois/Core/Module.C