jevois::MovieOutput Class Reference
#include <jevois/Core/MovieOutput.H>
使用 OpenCV 视频编码将视频输出到电影文件
此视频输出模式将输出帧保存到文件（或一系列文件）。在开发新算法以离线检查生成的输出的正确性或保存模块的某些文档/ 演示电影时，它很有用。
Definition at line 32 of file MovieOutput.H.
Public Member Functions
MovieOutput (std::string const &fn)
Constructor.
virtual ~MovieOutput ()
用于安全继承的虚拟析构函数
virtual void setFormat (VideoMapping const &m) override
设置视频格式和帧率
即，所有缓冲区都已排队等待发送但尚未发送。应用程序代码必须为每个 get () 平衡一个 send() 。 */virtual void get(RawImage &img) override
virtual void send (RawImage const &img) override
发送图像
virtual void streamOn () override
Start streaming.
virtual void abortStream () override
Abort streaming.
virtual void streamOff () override
Stop streaming.
Protected Member Functions
void run ()
使用线程对帧进行编码和保存
Protected Attributes
std::shared_ptr< VideoBuf > itsBuffer
我们的单个视频缓冲区
VideoMapping itsMapping
我们当前的视频映射，我们将输入调整为映射的摄像头大小
std::future< void > itsRunFut
Future for our run() thread.
jevois::BoundedBuffer< cv::Mat, jevois::BlockingBehavior::Block, jevois::BlockingBehavior::Block > itsBuf
要编码并写入文件的帧缓冲区
std::atomic< bool > itsSaving
当我们保存到文件时为 True
int itsFileNum
文件编号，在每次 streamOff() 时递增，以避免覆盖以前的文件
std::atomic< bool > itsRunning
当我们的 run() 线程应继续运行时为 True
std::string itsFilename
将视频保存到的当前文件名
std::string itsFilebase
Current file base to save video to.
Constructor & Destructor Documentation
MovieOutput()
jevois::MovieOutput::MovieOutput (std::string const & fn)
Constructor.
Definition at line 32 of file MovieOutput.C.
References jevois::async(), itsRunFut, and run().
 MovieOutput()
jevois::MovieOutput::~MovieOutput () [virtual]
用于安全继承的虚拟析构函数
Definition at line 39 of file MovieOutput.C.
References LERROR, LINFO, jevois::system(), and jevois::warnAndIgnoreException().
Member Function Documentation
abortStream()
void jevois::MovieOutput::abortStream () [override], [virtual]
Abort streaming.
这只会取消将来的 get() 和 send() 调用，仍应调用 streamOff() 来关闭流式传输。
Implements jevois::VideoOutput.
Definition at line 102 of file MovieOutput.C.
get()
void jevois::MovieOutput::get () & [override]
Definition at line 63 of file MovieOutput.C.
References jevois::RawImage::buf, jevois::RawImage::bufindex, jevois::RawImage::fmt, jevois::RawImage::fps, jevois::RawImage::height, LFATAL, and jevois::RawImage::width.
run()
void jevois::MovieOutput::run () [protected]
使用线程对帧进行编码和保存
Definition at line 127 of file MovieOutput.C.
References LFATAL.
Referenced by MovieOutput().
send()
void jevois::MovieOutput::send (RawImage const & img) [override], [virtual]
发送图像
如果格式不正确，则可能抛出 std::overflow_error，如果我们尚未使用前一个图像。
Implements jevois::VideoOutput.
Definition at line 81 of file MovieOutput.C.
References jevois::rawimage::convertToCvBGR(), LERROR, and LFATAL.
setFormat()
void jevois::MovieOutput::setFormat (VideoMapping const & m) [override], [virtual]
设置视频格式和帧率
Implements jevois::VideoOutput.
Definition at line 56 of file MovieOutput.C.
streamOff()
void jevois::MovieOutput::streamOff () [override], [virtual]
Stop streaming.
Implements jevois::VideoOutput.
Definition at line 108 of file MovieOutput.C.
References LERROR, LINFO, and jevois::system().
streamOn()
void jevois::MovieOutput::streamOn () [override], [virtual]
Start streaming.
Implements jevois::VideoOutput.
Definition at line 96 of file MovieOutput.C.
Member Data Documentation
itsBuf
jevois::BoundedBuffer<cv::Mat, jevois::BlockingBehavior::Block, jevois::BlockingBehavior::Block> jevois::MovieOutput::itsBuf [protected]
要编码并写入文件的帧缓冲区
Definition at line 69 of file MovieOutput.H.
itsBuffer
std::shared_ptr<VideoBuf> jevois::MovieOutput::itsBuffer [protected]
我们的单个视频缓冲区
Definition at line 63 of file MovieOutput.H.
itsFilebase
std::string jevois::MovieOutput::itsFilebase [protected]
Current file base to save video to.
Definition at line 74 of file MovieOutput.H.
itsFilename
std::string jevois::MovieOutput::itsFilename [protected]
将视频保存到的当前文件名
Definition at line 73 of file MovieOutput.H.
itsFileNum
int jevois::MovieOutput::itsFileNum [protected]
文件编号，在每次 streamOff() 时递增，以避免覆盖以前的文件
Definition at line 71 of file MovieOutput.H.
itsMapping
VideoMapping jevois::MovieOutput::itsMapping [protected]
我们当前的视频映射，我们将输入调整为映射的摄像头大小
Definition at line 64 of file MovieOutput.H.
itsRunFut
std::future<void> jevois::MovieOutput::itsRunFut [protected]
Future for our run() thread.
Definition at line 67 of file MovieOutput.H.
Referenced by MovieOutput().
itsRunning
std::atomic<bool> jevois::MovieOutput::itsRunning [protected]
当我们的 run() 线程应继续运行时为 True
Definition at line 72 of file MovieOutput.H.
itsSaving
std::atomic<bool> jevois::MovieOutput::itsSaving [protected]
当我们保存到文件时为 True
Definition at line 70 of file MovieOutput.H.
The documentation for this class was generated from the following files:
include/jevois/Core/MovieOutput.H
src/jevois/Core/MovieOutput.C