jevois::dnn::NetworkPythonImpl Class Reference
Definition at line 27 of file NetworkPython.C.
Public Member Functions
void loadpy (std::string const &pypath)
virtual ~NetworkPythonImpl ()
void freeze (bool doit)
void load ()
std::vector< cv::Mat > doprocess (std::vector< cv::Mat > const &outs, std::vector< std::string > &info)
Component (std::string const &instance)
Constructor.
Additional Inherited Members
Constructor & Destructor Documentation
 NetworkPythonImpl()
jevois::dnn::NetworkPythonImpl::~NetworkPythonImpl () [virtual]
Definition at line 42 of file NetworkPython.C.
Member Function Documentation
Component()
jevois::Component::Component
Constructor.
创建组件的标准方法是通过 Component::addSubComponent() 或 Manager::addComponent()，而不是手动构建。通过构造函数构造的组件 （例如，调用 new 操作符）将不会附加到 Component 层次结构。建议派生组件也有一个实例构造函数参数并将其传递给 base Component 类， 以允许复杂系统包含同一 Component 的多个实例。事实上，对于大多数组件来说，继承的构造函数是合适的：
class MyComp : public jevois::Component
{
public:
  // 继承的构造函数
  using jevois::Component::Component;
  // 用于安全继承的虚拟析构函数
  virtual ~MyComp();
};
Definition at line 32 of file Component.C.
doprocess()
std::vector< cv::Mat > jevois::dnn::NetworkPythonImpl::doprocess (std::vector< cv::Mat > const & outs, std::vector< std::string > & info)
Definition at line 69 of file NetworkPython.C.
References LFATAL, jevois::PythonWrapper::pyinst(), and jevois::python::pyVecToList().
freeze()
void jevois::dnn::NetworkPythonImpl::freeze (bool doit)
Definition at line 46 of file NetworkPython.C.
References jevois::python::hasattr(), and jevois::PythonWrapper::pyinst().
load()
void jevois::dnn::NetworkPythonImpl::load ()
Definition at line 63 of file NetworkPython.C.
References jevois::PythonWrapper::pyinst().
loadpy()
void jevois::dnn::NetworkPythonImpl::loadpy (std::string const & pypath)
Definition at line 52 of file NetworkPython.C.
References jevois::python::hasattr(), JEVOIS_SHARE_PATH, LINFO, jevois::PythonWrapper::pyinst(), and jevois::PythonWrapper::pythonload().
The documentation for this class was generated from the following file:
src/jevois/DNN/NetworkPython.C