jevois::PythonWrapper Class Reference
#include <jevois/Core/PythonWrapper.H>
辅助类，用于从 C++ 运行 Python 代码
此类加载 Python 代码并使其可通过 pyinst() 访问。它旨在与其他类组合，这些类实际上将通过 pyinst() 执行一些 Python 代码。
这里的主要约定是，python 代码将定义一个与 python 文件名完全相同的类（不带尾随的 .py 扩展名）。该类随后可通过 pyinst() 访问。
请注意，构造函数和 pythonload() 不会抛出错误，但如果在构造过程中发生错误，pyinst() 将会抛出错误
通常，此类由从 Component 继承的类继承，以创建可以运行 Python 代码的 Component 派生类。在这种情况下， PythonWrapper 将在加载 Python 代码时将该同级关联注册到 Engine 。在从 PythonWrapper 继承之前从 Component（或派 生类）继承至关重要，这样当调用 PythonWrapper 析构函数时，Component 基类应该尚未被销毁，并且它将从 Engine 中取 消注册。
Definition at line 40 of file PythonWrapper.H.
Public Member Functions
PythonWrapper ()
默认构造函数。稍后需要调用 pythonload()
virtual ~PythonWrapper ()
Destructor.
PythonWrapper (std::string const &path)
Construct from path.
void pythonload (std::string const &path)
如果使用了默认构造函数，则从 path 初始化
boost::python::object & pyinst ()
获取 python 类 pyinst，或者如果发生构造错误（例如，找不到文件）则抛出
boost::python::object & mainModule ()
Get the main module.
boost::python::object & mainNamespace ()
Get the main namespace.
const std::string & constructionError () const
获取构造错误（如果有）或空字符串
Constructor & Destructor Documentation
PythonWrapper() [1/2]
jevois::PythonWrapper::PythonWrapper ()
默认构造函数。稍后需要调用 pythonload()
Definition at line 23 of file PythonWrapper.C.
 PythonWrapper()
jevois::PythonWrapper::~PythonWrapper () [virtual]
Destructor.
Definition at line 104 of file PythonWrapper.C.
PythonWrapper() [2/2]
jevois::PythonWrapper::PythonWrapper (std::string const & path)
Construct from path.
Definition at line 28 of file PythonWrapper.C.
Member Function Documentation
constructionError()
const std::string & jevois::PythonWrapper::constructionError () const
获取构造错误（如果有）或空字符串
Definition at line 100 of file PythonWrapper.C.
mainModule()
boost::python::object & jevois::PythonWrapper::mainModule ()
Get the main module.
Definition at line 92 of file PythonWrapper.C.
mainNamespace()
boost::python::object & jevois::PythonWrapper::mainNamespace ()
Get the main namespace.
Definition at line 96 of file PythonWrapper.C.
pyinst()
boost::python::object & jevois::PythonWrapper::pyinst ()
获取 python 类 pyinst，或者如果发生构造错误（例如，找不到文件）则抛出
Definition at line 85 of file PythonWrapper.C.
Referenced by jevois::dnn::NetworkPythonImpl::doprocess(), jevois::dnn::NetworkPythonImpl::freeze(), jevois::dnn::PostProcessorPythonImpl::freeze(), jevois::dnn::PreProcessorPythonImpl::freeze(), jevois::dnn::NetworkPythonImpl::load(), jevois::dnn::NetworkPythonImpl::loadpy(), jevois::dnn::PostProcessorPythonImpl::loadpy(), jevois::dnn::PreProcessorPythonImpl::loadpy(), jevois::PythonModule::parseSerial(), jevois::PythonModule::postUninit(), jevois::PythonModule::preInit(), jevois::dnn::PreProcessorPythonImpl::process(), jevois::dnn::PostProcessorPythonImpl::process(), jevois::PythonModule::process(), jevois::dnn::PostProcessorPythonImpl::report(), jevois::dnn::PreProcessorPythonImpl::report(), and jevois::PythonModule::supportedCommands().
pythonload()
void jevois::PythonWrapper::pythonload (std::string const & path)
如果使用了默认构造函数，则从 path 初始化
Definition at line 34 of file PythonWrapper.C.
References jevois::getPythonExceptionString(), JEVOIS_CONFIG_PATH, JEVOIS_OPENCV_PYTHON_PATH, and JEVOIS_ROOT_PATH.
Referenced by jevois::dnn::NetworkPythonImpl::loadpy(), jevois::dnn::PreProcessorPythonImpl::loadpy(), jevois::dnn::PostProcessorPythonImpl::loadpy(), and jevois::PythonModule::preInit().
The documentation for this class was generated from the following files:
include/jevois/Core/PythonWrapper.H
src/jevois/Core/PythonWrapper.C