jevois::dnn::NetworkNPU Class Reference
#include <jevois/DNN/NetworkNPU.H>
在 Amlogic A311D NPU 加速器 (Verisilicon) 上运行的 DNN 神经网络的包装器
Definition at line 32 of file NetworkNPU.H.
Public Member Functions
virtual ~NetworkNPU ()
Destructor.
void freeze (bool doit) override
冻结/解冻参数，用户在运行时不应更改
virtual std::vector< vsi_nn_tensor_attr_t > inputShapes () override
Get shapes of all input tensors.
virtual std::vector< vsi_nn_tensor_attr_t > outputShapes () override
Get shapes of all output tensors.
Protected Member Functions
void load () override
Load from disk.
std::vector< cv::Mat > doprocess (std::vector< cv::Mat > const &blobs, std::vector< std::string > &info) override
Process input blobs and obtain output blobs.
Related Functions
(Note that these are not member functions.)
JEVOIS_DECLARE_PARAMETER (verifygraph, bool, `Verify NPU graph after loading it`, true, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (ovxver, std::string, `ovxlib version to use with NPU network, or leave blank ` `to use latest version`, ``, boost::regex(`^$|^[0-9]+\\.[0-9]+\\.[0-9]+$`), ParamCateg)
Parameter.
Constructor & Destructor Documentation
 NetworkNPU()
jevois::dnn::NetworkNPU::~NetworkNPU () [virtual]
Destructor.
Definition at line 118 of file NetworkNPU.C.
Member Function Documentation
doprocess()
std::vector< cv::Mat > jevois::dnn::NetworkNPU::doprocess (std::vector< cv::Mat > const & blobs, std::vector< std::string > & info) [override], [protected], [virtual]
Process input blobs and obtain output blobs.
Implements jevois::dnn::Network.
Definition at line 206 of file NetworkNPU.C.
References jevois::dnn::attrmat(), jevois::dnn::attrmatch(), jevois::dnn::attrstr(), jevois::dnn::dequantize(), LFATAL, jevois::dnn::shapestr(), jevois::to_string(), and jevois::warnAndRethrowException().
freeze()
void jevois::dnn::NetworkNPU::freeze (bool doit) [override], [virtual]
冻结/解冻参数，用户在运行时不应更改
Reimplemented from jevois::dnn::Network.
Definition at line 126 of file NetworkNPU.C.
References jevois::dnn::Network::freeze().
inputShapes()
std::vector< vsi_nn_tensor_attr_t > jevois::dnn::NetworkNPU::inputShapes () [override], [virtual]
Get shapes of all input tensors.
Implements jevois::dnn::Network.
Definition at line 78 of file NetworkNPU.C.
References jevois::dnn::parseTensorSpecs().
load()
void jevois::dnn::NetworkNPU::load () [override], [protected], [virtual]
Load from disk.
Implements jevois::dnn::Network.
Definition at line 137 of file NetworkNPU.C.
References jevois::absolutePath(), LFATAL, LINFO, NEW_VXNODE, jevois::dnn::parseTensorSpecs(), and jevois::split().
outputShapes()
std::vector< vsi_nn_tensor_attr_t > jevois::dnn::NetworkNPU::outputShapes () [override], [virtual]
Get shapes of all output tensors.
Implements jevois::dnn::Network.
Definition at line 84 of file NetworkNPU.C.
References jevois::dnn::parseTensorSpecs().
Friends And Related Function Documentation
JEVOIS_DECLARE_PARAMETER() [1/2]
JEVOIS_DECLARE_PARAMETER (ovxver , std::string , `ovxlib version to use with NPU network, or leave blank ` `to use latest version` , `` , boost::regex(`^$|^[0-9]+\\.[0-9]+\\.[0-9]+$`) , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [2/2]
JEVOIS_DECLARE_PARAMETER (verifygraph , bool , `Verify NPU graph after loading it` , true , ParamCateg) [related]
Parameter.
The documentation for this class was generated from the following files:
include/jevois/DNN/NetworkNPU.H
include/jevois/DNN/Network.H
src/jevois/DNN/NetworkNPU.C