jevois::dnn::NetworkPython Class Reference
#include <jevois/DNN/NetworkPython.H>
通过 python 调用的 DNN 神经网络的包装器
Definition at line 31 of file NetworkPython.H.
Public Member Functions
NetworkPython (std::string const &instance)
Constructor.
virtual ~NetworkPython ()
Destructor.
void freeze (bool doit) override
冻结/解冻参数，用户在运行时不应更改
std::vector< vsi_nn_tensor_attr_t > inputShapes () override
Get shapes of all input tensors.
std::vector< vsi_nn_tensor_attr_t > outputShapes () override
Get shapes of all output tensors.
void load () override
Load from disk.
std::vector< cv::Mat > doprocess (std::vector< cv::Mat > const &blobs, std::vector< std::string > &info) override
Process input blobs and obtain output blobs.
Protected Member Functions
void onParamChange (network::pynet const &param, std::string const &newval) override
Protected Attributes
std::shared_ptr< NetworkPythonImpl > itsImpl
Related Functions
(Note that these are not member functions.)
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (pynet, std::string, `Full path of the python network processor file. ` `Name of class defined in the file must match the file name without ` `the trailing '.py'`, ``, ParamCateg)
Parameter.
Constructor & Destructor Documentation
NetworkPython()
jevois::dnn::NetworkPython::NetworkPython (std::string const & instance)
Constructor.
Definition at line 86 of file NetworkPython.C.
References itsImpl.
 NetworkPython()
jevois::dnn::NetworkPython::~NetworkPython () [virtual]
Destructor.
Definition at line 93 of file NetworkPython.C.
Member Function Documentation
doprocess()
std::vector< cv::Mat > jevois::dnn::NetworkPython::doprocess (std::vector< cv::Mat > const & blobs, std::vector< std::string > & info) [override], [virtual]
Process input blobs and obtain output blobs.
Implements jevois::dnn::Network.
Definition at line 115 of file NetworkPython.C.
freeze()
void jevois::dnn::NetworkPython::freeze (bool doit) [override], [virtual]
冻结/解冻参数，用户在运行时不应更改
Reimplemented from jevois::dnn::Network.
Definition at line 97 of file NetworkPython.C.
References jevois::dnn::Network::freeze().
inputShapes()
std::vector< vsi_nn_tensor_attr_t > jevois::dnn::NetworkPython::inputShapes () [override], [virtual]
Get shapes of all input tensors.
Implements jevois::dnn::Network.
Definition at line 124 of file NetworkPython.C.
References jevois::dnn::parseTensorSpecs().
load()
void jevois::dnn::NetworkPython::load () [override], [virtual]
Load from disk.
Implements jevois::dnn::Network.
Definition at line 120 of file NetworkPython.C.
onParamChange()
void jevois::dnn::NetworkPython::onParamChange (network::pynet const & param, std::string const & newval) [override], [protected]
Definition at line 109 of file NetworkPython.C.
outputShapes()
std::vector< vsi_nn_tensor_attr_t > jevois::dnn::NetworkPython::outputShapes () [override], [virtual]
Get shapes of all output tensors.
Implements jevois::dnn::Network.
Definition at line 128 of file NetworkPython.C.
References jevois::dnn::parseTensorSpecs().
Friends And Related Function Documentation
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK()
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (pynet , std::string , `Full path of the python network processor file. ` `Name of class defined in the file must match the file name without ` `the trailing '.py'` , `` , ParamCateg) [related]
Parameter.
Member Data Documentation
itsImpl
std::shared_ptr<NetworkPythonImpl> jevois::dnn::NetworkPython::itsImpl [protected]
Definition at line 62 of file NetworkPython.H.
Referenced by NetworkPython().
The documentation for this class was generated from the following files:
include/jevois/DNN/NetworkPython.H
include/jevois/DNN/Network.H
src/jevois/DNN/NetworkPython.C