jevois::dnn::PreProcessor Class Reference
#include <jevois/DNN/PreProcessor.H>
神经网络管道的预处理器
这是深度神经网络处理管道的第一步。
派生类必须实现纯虚拟方法：
process()：处理输入图像并生成一些张量 (blob)
report()：描述 process() 对人类做了什么
freeze()：冻结/解冻用户在运行时不应更改的参数
它们应该保留一些关于要报告的内容的内部状态，因为 report() 总是在每一帧上被调用，但是如果网络速度较慢，则 process() 的调用频率可能会较低。
Definition at line 107 of file PreProcessor.H.
Public Member Functions
PreProcessor (std::string const &instance)
Constructor.
virtual ~PreProcessor ()
Destructor.
virtual void freeze (bool doit)=0
冻结/解冻运行时用户不应更改的参数
std::vector< cv::Mat > process (jevois::RawImage const &img, std::vector< vsi_nn_tensor_attr_t > const &attrs)
从输入图像中提取 blob
virtual void sendreport (jevois::StdModule *mod, jevois::RawImage *outimg=nullptr, jevois::OptGUIhelper *helper=nullptr, bool overlay=true, bool idle=false)
将上一个 process() 中发生的事情报告给控制台/输出视频/GUI
const cv::Size & imagesize () const
访问最后处理的图像大小
const std::vector< cv::Mat > & blobs () const
访问最后计算的 blob（如果尚未调用 process()，则为空）
cv::Size blobsize (size_t num) const
访问给定 blob 的宽度和高度，考虑 NCHW 或 NHWC
void b2i (float &x, float &y, size_t blobnum=0)
将 blob 中的坐标转换回原始图像
void b2i (float &x, float &y, cv::Size const &bsiz, bool letterboxed)
将 blob 的坐标转换回原始图像，给定一个已知的 blob 大小
cv::Rect getUnscaledCropRect (size_t blobnum=0)
在图像坐标中获取未缩放的裁剪矩形
void getUnscaledCropRect (size_t blobnum, int &tlx, int &tly, int &brx, int &bry)
在图像坐标中获取未缩放的裁剪矩形
void i2b (float &x, float &y, size_t blobnum=0)
将坐标从图像转换为 blob
void i2b (float &x, float &y, cv::Size const &bsiz, bool letterboxed)
将坐标从图像转换为 blob
std::shared_ptr< PreProcessorForPython > getPreProcForPy () const
获取指向我们的 python 友好接口的指针
Protected Member Functions
virtual std::vector< cv::Mat > process (cv::Mat const &img, bool isrgb, std::vector< vsi_nn_tensor_attr_t > const &attrs, std::vector< cv::Rect > &crops)=0
从输入图像中提取 blob
virtual void report (jevois::StdModule *mod, jevois::RawImage *outimg=nullptr, jevois::OptGUIhelper *helper=nullptr, bool overlay=true, bool idle=false)=0
将上一个 process() 中发生的事情报告给控制台/输出视频/GUI
Related Functions
(Note that these are not member functions.)
JEVOIS_DECLARE_PARAMETER (rgb, bool, `When true, model works with RGB input images instead BGR ones`, true, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (scale, float, `Value scaling factor applied to input pixels after mean subtraction, ` `or 0.0 to extract an unscaled UINT8 blob, typically for use with quantized networks`, 2.0F/255.0F, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (mean, cv::Scalar, `Mean values subtracted from input image, in the same RGB/BGR ` `order as the network's input`, cv::Scalar(127.5F, 127.5F, 127.5F), ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (stdev, cv::Scalar, `Input image is divided by stdev after mean subtraction and scale ` `factor are applied. This is rarely used. Same RGB/BGR order as the network's input`, cv::Scalar(1.0F, 1.0F, 1.0F), ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (letterbox, bool, `When true, extract the largest possible box from the input image ` `with same aspect ratio as the network's input tensor, and then rescale it to that ` `tensor's width and height (hence with cropping but no distortion). Otherwise, use ` `the whole image and rescale it to the network's input width and height with some ` `possible stretching.`, false, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (showin, bool, `Show outline of cropped image fed to network`, true, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (details, bool, `Show more details about the pre-processing steps`, false, ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (InterpMode,(Nearest)(Linear)(Cubic)(Area)(Lanczos4))
Enum for image resizing modes.
JEVOIS_DECLARE_PARAMETER (interp, InterpMode, `Image interpolation to use when resizing the input image ` `from camera to network input dims`, InterpMode::Nearest, InterpMode_Values, ParamCateg)
Parameter.
Constructor & Destructor Documentation
PreProcessor()
jevois::dnn::PreProcessor::PreProcessor (std::string const & instance)
Constructor.
Definition at line 26 of file PreProcessor.C.
 PreProcessor()
jevois::dnn::PreProcessor::~PreProcessor () [virtual]
Destructor.
Definition at line 31 of file PreProcessor.C.
Member Function Documentation
b2i() [1/2]
void jevois::dnn::PreProcessor::b2i (float & x, float & y, cv::Size const & bsiz, bool letterboxed)
将 blob 的坐标转换回原始图像，给定一个已知的 blob 大小
给定的坐标 x,y 应该在 [0..w-1]x[0..h-1] 中，其中 w,h 是 blob 的宽度和高度。这对于将检测到的框转换回原始输入坐 标很有用。
Definition at line 60 of file PreProcessor.C.
References LFATAL.
b2i() [2/2]
void jevois::dnn::PreProcessor::b2i (float & x, float & y, size_t blobnum = 0)
将 blob 中的坐标转换回原始图像
Definition at line 50 of file PreProcessor.C.
References LFATAL.
Referenced by jevois::dnn::PostProcessorDetect::process(), and jevois::dnn::PostProcessorYuNet::process().
blobs()
const std::vector< cv::Mat > & jevois::dnn::PreProcessor::blobs () const
访问最后计算的 blob（如果尚未调用 process()，则为空）
Definition at line 35 of file PreProcessor.C.
blobsize()
cv::Size jevois::dnn::PreProcessor::blobsize (size_t num) const
访问给定 blob 的宽度和高度，考虑 NCHW 或 NHWC
Definition at line 43 of file PreProcessor.C.
References jevois::dnn::attrsize(), and LFATAL.
Referenced by jevois::dnn::PostProcessorDetect::process(), and jevois::dnn::PostProcessorYuNet::process().
freeze()
virtual void jevois::dnn::PreProcessor::freeze (bool doit) [pure virtual]
冻结/解冻运行时用户不应更改的参数
Implemented in jevois::dnn::PreProcessorBlob, and jevois::dnn::PreProcessorPython.
getPreProcForPy()
std::shared_ptr< jevois::dnn::PreProcessorForPython > jevois::dnn::PreProcessor::getPreProcForPy () const
获取指向我们的 python 友好接口的指针
Definition at line 127 of file PreProcessor.C.
Referenced by jevois::dnn::PostProcessorPythonImpl::process().
getUnscaledCropRect() [1/2]
void jevois::dnn::PreProcessor::getUnscaledCropRect (size_t blobnum, int & tlx, int & tly, int & brx, int & bry)
在图像坐标中获取未缩放的裁剪矩形
Definition at line 88 of file PreProcessor.C.
getUnscaledCropRect() [2/2]
cv::Rect jevois::dnn::PreProcessor::getUnscaledCropRect (size_t blobnum = 0)
在图像坐标中获取未缩放的裁剪矩形
Definition at line 81 of file PreProcessor.C.
References LFATAL.
Referenced by jevois::dnn::PostProcessorSegment::process().
i2b() [1/2]
void jevois::dnn::PreProcessor::i2b (float & x, float & y, cv::Size const & bsiz, bool letterboxed)
将坐标从图像转换为 blob
给定坐标 x、y 应位于 [0..w-1]x[0..h-1] 中，其中 w、h 是图像的宽度和高度。这对于将鼠标坐标（在从屏幕坐标转 换为图像坐标之后）转换为输入 blob 内的位置很有用。
Definition at line 105 of file PreProcessor.C.
References LFATAL.
i2b() [2/2]
void jevois::dnn::PreProcessor::i2b (float & x, float & y, size_t blobnum = 0)
将坐标从图像转换为 blob
给定坐标 x、y 应位于 [0..w-1]x[0..h-1] 中，其中 w、h 是图像的宽度和高度。这对于将鼠标坐标（在从屏幕坐标转 换为图像坐标之后）转换为输入 blob 内的位置很有用。
Definition at line 95 of file PreProcessor.C.
References LFATAL.
imagesize()
const cv::Size & jevois::dnn::PreProcessor::imagesize () const
访问最后处理的图像大小
Definition at line 39 of file PreProcessor.C.
Referenced by jevois::dnn::PostProcessorDetect::process(), and jevois::dnn::PostProcessorYuNet::process().
process() [1/2]
virtual std::vector<cv::Mat> jevois::dnn::PreProcessor::process (cv::Mat const & img, bool isrgb, std::vector< vsi_nn_tensor_attr_t > const & attrs, std::vector< cv::Rect > & crops) [protected], [pure virtual]
从输入图像中提取 blob
Implemented in jevois::dnn::PreProcessorBlob, and jevois::dnn::PreProcessorPython.
process() [2/2]
std::vector< cv::Mat > jevois::dnn::PreProcessor::process (jevois::RawImage const & img, std::vector< vsi_nn_tensor_attr_t > const & attrs)
从输入图像中提取 blob
Definition at line 131 of file PreProcessor.C.
References jevois::rawimage::convertToCvBGR(), jevois::rawimage::convertToCvRGB(), jevois::rawimage::cvImage(), jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, and jevois::RawImage::width.
report()
virtual void jevois::dnn::PreProcessor::report (jevois::StdModule * mod, jevois::RawImage * outimg = nullptr, jevois::OptGUIhelper * helper = nullptr, bool overlay = true, bool idle = false) [protected], [pure virtual]
将上一个 process() 中发生的事情报告给控制台/输出视频/GUI
Implemented in jevois::dnn::PreProcessorBlob, and jevois::dnn::PreProcessorPython.
sendreport()
void jevois::dnn::PreProcessor::sendreport (jevois::StdModule * mod, jevois::RawImage * outimg = nullptr, jevois::OptGUIhelper * helper = nullptr, bool overlay = true, bool idle = false) [virtual]
将上一个 process() 中发生的事情报告给控制台/输出视频/GUI
Definition at line 155 of file PreProcessor.C.
References jevois::rawimage::drawRect(), jevois::fccstr(), jevois::GUIhelper::i2d(), jevois::yuyv::MedGrey, jevois::dnn::shapestr(), and jevois::RawImage::width.
Friends And Related Function Documentation
JEVOIS_DECLARE_PARAMETER() [1/8]
JEVOIS_DECLARE_PARAMETER (details , bool , `Show more details about the pre-processing steps` , false , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [2/8]
JEVOIS_DECLARE_PARAMETER (interp , InterpMode , `Image interpolation to use when resizing the input image ` `from camera to network input dims` , InterpMode::Nearest , InterpMode_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [3/8]
JEVOIS_DECLARE_PARAMETER (letterbox , bool , `When true, extract the largest possible box from the input image ` `with same aspect ratio as the network 's input tensor, and then rescale it to that ` `tensor 's width and height(hence with cropping but no distortion). Otherwise, use ` `the whole image and rescale it to the network 's input width and height with some ` `possible stretching.` , false , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [4/8]
JEVOIS_DECLARE_PARAMETER (mean , cv::Scalar , `Mean values subtracted from input image, in the same RGB/BGR ` `order as the network 's input` , cv::Scalar(127.5F, 127.5F, 127.5F) , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [5/8]
JEVOIS_DECLARE_PARAMETER (rgb , bool , `When true, model works with RGB input images instead BGR ones` , true , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [6/8]
JEVOIS_DECLARE_PARAMETER (scale , float , `Value scaling factor applied to input pixels after mean subtraction, ` `or 0.0 to extract an unscaled UINT8 blob, typically for use with quantized networks` , 2.0F/255. 0F, ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [7/8]
JEVOIS_DECLARE_PARAMETER (showin , bool , `Show outline of cropped image fed to network` , true , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [8/8]
JEVOIS_DECLARE_PARAMETER (stdev , cv::Scalar , `Input image is divided by stdev after mean subtraction and scale ` `factor are applied. This is rarely used. Same RGB/BGR order as the network's input` , cv::Scalar(1.0F, 1.0F, 1.0F) , ParamCateg) [related]
Parameter.
JEVOIS_DEFINE_ENUM_CLASS()
JEVOIS_DEFINE_ENUM_CLASS (InterpMode , (Nearest)(Linear)(Cubic)(Area)(Lanczos4)) [related]
Enum for image resizing modes.
The documentation for this class was generated from the following files:
include/jevois/DNN/PreProcessor.H
src/jevois/DNN/PreProcessor.C