jevois::Watchdog Class Reference
#include <jevois/Debug/Watchdog.H>
简单的看门狗类
如果至少每超时秒不调用 reset()，则此类将终止当前进程。 如果超时 <= 0.0，则看门狗处于非活动状态（永远不会超时并终 止进程）。 请注意，为了尽可能轻量，此类运行一个后台线程，循环每超时秒迭代一次，因此确切的终止时间是近似的。
Definition at line 28 of file Watchdog.H.
Public Member Functions
Watchdog (double timeout)
Constructor.
~Watchdog ()
Virtual destructor for safe inheritance.
void reset ()
重置我们的内部计时器。如果这种情况至少每超时秒不发生一次，则进程将被终止
Protected Member Functions
void run (double timeout)
Protected Attributes
std::future< void > itsRunFut
std::atomic< bool > itsReset = true
std::atomic< bool > itsRunning = false
Constructor & Destructor Documentation
Watchdog()
jevois::Watchdog::Watchdog (double timeout)
Constructor.
Definition at line 27 of file Watchdog.C.
References jevois::async_little(), itsRunFut, itsRunning, and run().
 Watchdog()
jevois::Watchdog::~Watchdog ()
Virtual destructor for safe inheritance.
Definition at line 37 of file Watchdog.C.
References JEVOIS_WAIT_GET_FUTURE.
Member Function Documentation
reset()
void jevois::Watchdog::reset ()
重置我们的内部计时器。如果这种情况至少每超时秒不发生一次，则进程将被终止
Definition at line 47 of file Watchdog.C.
run()
void jevois::Watchdog::run (double timeout) [protected]
Definition at line 51 of file Watchdog.C.
References LERROR, jevois::system(), and jevois::to_string().
Referenced by Watchdog().
Member Data Documentation
itsReset
std::atomic<bool> jevois::Watchdog::itsReset = true [protected]
Definition at line 43 of file Watchdog.H.
itsRunFut
std::future<void> jevois::Watchdog::itsRunFut [protected]
Definition at line 42 of file Watchdog.H.
Referenced by Watchdog().
itsRunning
std::atomic<bool> jevois::Watchdog::itsRunning = false [protected]
Definition at line 44 of file Watchdog.H.
Referenced by Watchdog().
The documentation for this class was generated from the following files:
include/jevois/Debug/Watchdog.H
src/jevois/Debug/Watchdog.C