jevois::UserInterface Class Reference
#include <jevois/Core/UserInterface.H>
基于字符串的用户界面的抽象基类
用户通过发出文本命令和接收文本答案与 JeVois 硬件交互。UserInterface 是此类通信的抽象基类，其派生类为 Serial（在平台硬件上， 使用硬件串行和 USB 串行）或 StdioInterface（在主机上，使用终端中的用户输入和输出）。
请参阅 命令行界面用户指南 了解命令行界面的用户文档。
Definition at line 31 of file UserInterface.H.
Public Types
enum Type { Type::Hard,
Type::USB,
Type::Stdio,
Type::GUI
 }
接口类型的枚举
Public Member Functions
UserInterface (std::string const &instance)
Constructor.
virtual ~UserInterface ()
Destructor.
virtual bool readSome (std::string &str)=0
读取一些字节（如果可用），并在完成时（按下 RETURN 键）返回 true 和一个字符串
virtual void writeString (std::string const &str)=0
写入字符串
virtual void writeString (std::string const &prefix, std::string const &str)
写入一个字符串，并在前面添加前缀
virtual Type type () const =0
派生类必须实现此并返回其接口类型
Additional Inherited Members
Member Enumeration Documentation
Type
enum jevois::UserInterface::Type [strong]
接口类型的枚举
Enumerator
Hard
USB
Stdio
GUI
Definition at line 56 of file UserInterface.H.
Constructor & Destructor Documentation
UserInterface()
jevois::UserInterface::UserInterface (std::string const & instance)
Constructor.
Definition at line 21 of file UserInterface.C.
 UserInterface()
jevois::UserInterface::~UserInterface () [virtual]
Destructor.
Definition at line 26 of file UserInterface.C.
Member Function Documentation
readSome()
virtual bool jevois::UserInterface::readSome (std::string & str) [pure virtual]
读取一些字节（如果可用），并在完成时（按下 RETURN 键）返回 true 和一个字符串
如果用户输入尚未完成（尚未按下 RETURN 键），则 str 保持不变。RETURN（行尾）标记不会复制到 str 中，只会复制直到行尾标 记为止接收到的字符。
Implemented in jevois::Serial, jevois::GUIserial, jevois::GUIconsole, and jevois::StdioInterface.
type()
virtual Type jevois::UserInterface::type () const [pure virtual]
派生类必须实现此并返回其接口类型
Implemented in jevois::Serial, jevois::GUIconsole, and jevois::StdioInterface.
Referenced by jevois::Engine::mainLoop(), jevois::Engine::runScriptFromFile(), and jevois::Engine::sendSerial().
writeString() [1/2]
void jevois::UserInterface::writeString (std::string const & prefix, std::string const & str) [virtual]
写入一个字符串，并在前面添加前缀
字符串中不应包含行终止符，writeString() 将添加一个。在 Serial 派生类中，这将使用 serial::linestyle 的行终止约定来支 持不同的样式（CR、CRLF、LF 等）。
Definition at line 30 of file UserInterface.C.
writeString() [2/2]
virtual void jevois::UserInterface::writeString (std::string const & str) [pure virtual]
写入字符串
字符串中不应包含行终止符，writeString() 将添加一个。在 Serial 派生类中，这将使用 serial::linestyle 的行终止约定来支 持不同的样式（CR、CRLF、LF 等）。
Implemented in jevois::Serial, jevois::GUIconsole, jevois::GUIserial, and jevois::StdioInterface.
Referenced by jevois::Engine::mainLoop(), jevois::Component::paramInfo(), jevois::Engine::parseCommand(), jevois::PythonModule::parseSerial(), jevois::Engine::runScriptFromFile(), and jevois::Engine::sendSerial().
The documentation for this class was generated from the following files:
include/jevois/Core/UserInterface.H
src/jevois/Core/UserInterface.C