jevois::JpegCompressor Class Reference
#include <jevois/Image/Jpeg.H>
turbojpeg 压缩器的简单单例包装器
大多数用户不需要使用此类，compressBRGtoJpeg() 在内部使用它来避免在每个视频帧上重新创建 turbojpeg 压缩器对象。
Definition at line 40 of file Jpeg.H.
Public Member Functions
JpegCompressor ()
Constructor, create the turbojpeg object.
virtual ~JpegCompressor ()
Destructor, frees the turbojpeg object.
void * compressor ()
Access the compressor handle.
Additional Inherited Members
Constructor & Destructor Documentation
JpegCompressor()
jevois::JpegCompressor::JpegCompressor ()
Constructor, create the turbojpeg object.
Definition at line 23 of file Jpeg.C.
 JpegCompressor()
jevois::JpegCompressor::~JpegCompressor () [virtual]
Destructor, frees the turbojpeg object.
Definition at line 27 of file Jpeg.C.
Member Function Documentation
compressor()
void * jevois::JpegCompressor::compressor ()
Access the compressor handle.
Definition at line 31 of file Jpeg.C.
Referenced by jevois::compressBGRtoJpeg(), jevois::compressGRAYtoJpeg(), jevois::compressRGBAtoJpeg(), and jevois::compressRGBtoJpeg().
The documentation for this class was generated from the following files:
include/jevois/Image/Jpeg.H
src/jevois/Image/Jpeg.C