jevois::dnn::Network Class Reference
#include <jevois/DNN/Network.H>
表示神经网络的抽象类。
派生类通过 OpenCV（CPU、OpenCL 或 OpenVino/Myriad-X）、Amlogic/Vivante NPU、Hailo-8、Python 或 Google Coral TPU 提供实现。
Definition at line 159 of file Network.H.
Public Member Functions
virtual ~Network ()
Destructor.
void waitBeforeDestroy ()
如果网络正在加载，则等待加载完成后再销毁
bool ready ()
当网络准备好运行（加载并初始化）时返回 true
virtual std::vector< vsi_nn_tensor_attr_t > inputShapes ()=0
Get shapes of all input tensors.
virtual std::vector< vsi_nn_tensor_attr_t > outputShapes ()=0
Get shapes of all output tensors.
std::vector< cv::Mat > process (std::vector< cv::Mat > const &blobs, std::vector< std::string > &info)
处理输入 blob 并获取输出 blob。
virtual void freeze (bool doit)
冻结/解冻用户在运行时不应更改的参数
Protected Member Functions
virtual void load ()=0
Load from disk.
virtual std::vector< cv::Mat > doprocess (std::vector< cv::Mat > const &blobs, std::vector< std::string > &info)=0
处理输入 blobs 并获取输出 blobs
void onParamChange (network::outreshape const &param, std::string const &val) override
Related Functions
(Note that these are not member functions.)
JEVOIS_DECLARE_PARAMETER (comment, std::string, `Optional comment about the network`, ``, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (url, std::string, `Optional URL for the network`, ``, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (dataroot, std::string, `Root directory to use when config or model parameters ` `are relative paths.`, JEVOIS_SHARE_PATH, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (config, std::string, `Path to a text file that contains network configuration. ` `Can have extension .prototxt (Caffe), .pbtxt (TensorFlow), or .cfg (Darknet). ` `If path is relative, it will be prefixed by dataroot.`, ``, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (model, std::string, `Path to a binary file of model contains trained weights. ` `Can have extension .caffemodel (Caffe), .pb (TensorFlow), .t7 or .net (Torch), ` `.tflite (TensorFlow Lite), or .weights (Darknet). If path is relative, it will be ` `prefixed by dataroot.`, ``, ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (Target,(CPU)(OpenCL)(OpenCL_FP16)(Myriad)(NPU))
Enum.
JEVOIS_DECLARE_PARAMETER (target, Target, `OpenCV compute target to use. Changes will take effect ` `next time you load a different model.`, Target::CPU, Target_Values, ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (Backend,(OpenCV)(InferenceEngine)(TimVX))
Enum.
JEVOIS_DECLARE_PARAMETER (backend, Backend, `OpenCV compute backend to use. Default will use the inference ` `engine if available, otherwise OpenCV (note that inference engine only works on Intel ` `processors or MyriadX hardware, thus you should normally select OpenCV when running ` `on JeVois-Pro Platform, unless you want to use an optional MyriadX accelerator). ` `Changes will take effect next time you load a model.`, JEVOIS_BACKEND_DEFAULT, Backend_Values, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (intensors, std::string, `Specification of input tensors`, ``, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (extraintensors, std::string, `Specification of extra fixed input tensors that will be ` `added after the regular intensors. Format is: ` `<type>:<shape>:val1 val2 ... valN, <type>:<shape>:val1 ... valN. For example, for ` `URetinex-Net: 32F:1x1x1:3.0`, ``, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (outtensors, std::string, `Specification of output tensors`, ``, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (outreshape, std::string, `Specification of reshaped output tensors ` `sometimes useful to re-interpret tensors to what a post-processor expects for ` `example, TPU YoloV4-Int-VOC outputs 5D tensors 32F:1x52x52x3x85, 32F:1x26x26x3x85, ` `32F:1x13x13x3x85 but the YOLO post-processor expects 4D, which would be specified here ` `as 32F:1x52x52x255, 32F:1x26x26x255, 32F:1x13x13x255. Note that this only changes ` `the description of dimensions, but does not move any pixel data around (e.g., cannot ` `convert from NCHW to NHWC, convert data types, etc). Use sparingly and with caution.`, ``, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (dequant, bool, `Dequantize output tensors to float32 from their native quantized type`, true, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (tpunum, size_t, `Coral EdgeTPU number to use to run this model, typically 0, or can be ` `1 when using a dual-TPU add-on board, or more when using additional TPUs connected ` `to USB ports`, 0, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (spunum, size_t, `Hailo8 device number to use to run this model, typically 0 unless ` `several Hailo8 accelerators are connected to the system`, 0, ParamCateg)
Parameter.
Constructor & Destructor Documentation
 Network()
jevois::dnn::Network::~Network () [virtual]
Destructor.
CAUTION: 派生类必须在其析构函数中调用 waitBeforeDestroy()
Definition at line 23 of file Network.C.
Member Function Documentation
doprocess()
virtual std::vector<cv::Mat> jevois::dnn::Network::doprocess (std::vector< cv::Mat > const & blobs, std::vector< std::string > & info) [protected], [pure virtual]
处理输入 blobs 并获取输出 blobs
Implemented in jevois::dnn::NetworkNPU, jevois::dnn::NetworkHailo, jevois::dnn::NetworkONNX, jevois::dnn::NetworkOpenCV, jevois::dnn::NetworkTPU, and jevois::dnn::NetworkPython.
freeze()
void jevois::dnn::Network::freeze (bool doit) [virtual]
冻结/解冻用户在运行时不应更改的参数
注意：派生类可以通过重写此函数来冻结自己的参数，并且应该记住仍然调用基类 jevois::dnn::Network::freeze(doit)
Reimplemented in jevois::dnn::NetworkNPU, jevois::dnn::NetworkHailo, jevois::dnn::NetworkONNX, jevois::dnn::NetworkOpenCV, jevois::dnn::NetworkTPU, and jevois::dnn::NetworkPython.
Definition at line 27 of file Network.C.
Referenced by jevois::dnn::NetworkPython::freeze(), jevois::dnn::NetworkOpenCV::freeze(), jevois::dnn::NetworkTPU::freeze(), jevois::dnn::NetworkONNX::freeze(), jevois::dnn::NetworkHailo::freeze(), and jevois::dnn::NetworkNPU::freeze().
inputShapes()
virtual std::vector<vsi_nn_tensor_attr_t> jevois::dnn::Network::inputShapes () [pure virtual]
Get shapes of all input tensors.
Implemented in jevois::dnn::NetworkNPU, jevois::dnn::NetworkHailo, jevois::dnn::NetworkONNX, jevois::dnn::NetworkOpenCV, jevois::dnn::NetworkTPU, and jevois::dnn::NetworkPython.
load()
virtual void jevois::dnn::Network::load () [protected], [pure virtual]
Load from disk.
Implemented in jevois::dnn::NetworkNPU, jevois::dnn::NetworkHailo, jevois::dnn::NetworkONNX, jevois::dnn::NetworkOpenCV, jevois::dnn::NetworkTPU, and jevois::dnn::NetworkPython.
Referenced by ready().
onParamChange()
void jevois::dnn::Network::onParamChange (network::outreshape const & param, std::string const & val) [override], [protected]
Definition at line 35 of file Network.C.
References jevois::dnn::parseTensorSpecs().
outputShapes()
virtual std::vector<vsi_nn_tensor_attr_t> jevois::dnn::Network::outputShapes () [pure virtual]
Get shapes of all output tensors.
Implemented in jevois::dnn::NetworkNPU, jevois::dnn::NetworkHailo, jevois::dnn::NetworkONNX, jevois::dnn::NetworkOpenCV, jevois::dnn::NetworkTPU, and jevois::dnn::NetworkPython.
process()
std::vector< cv::Mat > jevois::dnn::Network::process (std::vector< cv::Mat > const & blobs, std::vector< std::string > & info)
处理输入 blob 并获取输出 blob。
Network 实现可以将信息数据推送到信息字符串中，该字符串将显示给用户。约定是：如果信息行以 '* ' 开头，则它 是标题，如果以 '- ' 开头，则它是项目符号。信息应始终组织到顶层的标题中。
Definition at line 82 of file Network.C.
References jevois::dnn::attrdims(), jevois::dnn::attrmat(), LFATAL, jevois::dnn::shapestr(), jevois::split(), and jevois::dnn::strshape().
ready()
bool jevois::dnn::Network::ready ()
当网络准备好运行（加载并初始化）时返回 true
Definition at line 57 of file Network.C.
References jevois::async(), LINFO, load(), and jevois::warnAndRethrowException().
waitBeforeDestroy()
void jevois::dnn::Network::waitBeforeDestroy ()
如果网络正在加载，则等待加载完成后再销毁
CAUTION: 派生类必须在其析构函数中调用 waitBeforeDestroy()
Definition at line 44 of file Network.C.
References LINFO.
Referenced by jevois::dnn::NetworkOpenCV::~NetworkOpenCV(), and jevois::dnn::NetworkTPU::~NetworkTPU().
Friends And Related Function Documentation
JEVOIS_DECLARE_PARAMETER() [1/13]
JEVOIS_DECLARE_PARAMETER (backend , Backend , `OpenCV compute backend to use. Default will use the inference ` `engine if available, otherwise OpenCV(note that inference engine only works on Intel ` `processors or MyriadX hardware, thus you should normally select OpenCV when running ` `on JeVois-Pro Platform, unless you want to use an optional MyriadX accelerator). ` `Changes will take effect next time you load a model.` , JEVOIS_BACKEND_DEFAULT , Backend_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [2/13]
JEVOIS_DECLARE_PARAMETER (comment , std::string , `Optional comment about the network` , `` , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [3/13]
JEVOIS_DECLARE_PARAMETER (config , std::string , `Path to a text file that contains network configuration. ` `Can have extension .prototxt Caffe, . pbtxtTensorFlow, or .cfg(Darknet). ` `If path is relative, it will be prefixed by dataroot.` , `` , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [4/13]
JEVOIS_DECLARE_PARAMETER (dataroot , std::string , `Root directory to use when config or model parameters ` `are relative paths.` , JEVOIS_SHARE_PATH , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [5/13]
JEVOIS_DECLARE_PARAMETER (dequant , bool , `Dequantize output tensors to float32 from their native quantized type` , true , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [6/13]
JEVOIS_DECLARE_PARAMETER (extraintensors , std::string , `Specification of extra fixed input tensors that will be ` `added after the regular intensors. Format is: ` `<type>:<shape>:val1 val2 ... valN, < type >:< shape >:val1 ... valN. For example, for ` `URetinex-Net:32F:1x1x1:3.0` , `` , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [7/13]
JEVOIS_DECLARE_PARAMETER (intensors , std::string , `Specification of input tensors` , `` , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [8/13]
JEVOIS_DECLARE_PARAMETER (model , std::string , `Path to a binary file of model contains trained weights. ` `Can have extension .caffemodel Caffe, . pbTensorFlow, .t7 or . netTorch, ` `. tfliteTensorFlow Lite, or .weights(Darknet). If path is relative, it will be ` `prefixed by dataroot.` , `` , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [9/13]
JEVOIS_DECLARE_PARAMETER (outtensors , std::string , `Specification of output tensors` , `` , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [10/13]
JEVOIS_DECLARE_PARAMETER (spunum , size_t , `Hailo8 device number to use to run this model, typically 0 unless ` `several Hailo8 accelerators are connected to the system` , 0 , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [11/13]
JEVOIS_DECLARE_PARAMETER (target , Target , `OpenCV compute target to use. Changes will take effect ` `next time you load a different model.` , Target::CPU , Target_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [12/13]
JEVOIS_DECLARE_PARAMETER (tpunum , size_t , `Coral EdgeTPU number to use to run this model, typically 0, or can be ` `1 when using a dual-TPU add-on board, or more when using additional TPUs connected ` `to USB ports` , 0 , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [13/13]
JEVOIS_DECLARE_PARAMETER (url , std::string , `Optional URL for the network` , `` , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK()
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (outreshape , std::string , `Specification of reshaped output tensors ` `sometimes useful to re-interpret tensors to what a post-processor expects for ` ` example, TPU YoloV4-Int-VOC outputs 5D tensors 32F:1x52x52x3x85 , 32F:1x26x26x3x85 , ` `32F:1x13x13x3x85 but the YOLO post-processor expects 4D, which would be specified here ` `as 32F:1x52x52x255 , 32F:1x26x26x255 , 32F:1x13x13x255. Note that this only changes ` `the description of dimensions, but does not move any pixel data around(e.g., cannot ` `convert from NCHW to NHWC, convert data types, etc). Use sparingly and with caution.` , `` , ParamCateg) [related]
Parameter.
JEVOIS_DEFINE_ENUM_CLASS() [1/2]
JEVOIS_DEFINE_ENUM_CLASS (Backend , (OpenCV)(InferenceEngine)(TimVX)) [related]
Enum.
JEVOIS_DEFINE_ENUM_CLASS() [2/2]
JEVOIS_DEFINE_ENUM_CLASS (Target , (CPU)(OpenCL)(OpenCL_FP16)(Myriad)(NPU)) [related]
Enum.
The documentation for this class was generated from the following files:
include/jevois/DNN/Network.H
src/jevois/DNN/Network.C