jevois::dnn::NetworkHailo Class Reference
#include <jevois/DNN/NetworkHailo.H>
在 Hailo8 神经加速器上运行的 DNN 神经网络的包装器
请注意，此网络类型不支持在外部设置张力器或输出张力器，这些在 HEF 文件中已修复。
Definition at line 33 of file NetworkHailo.H.
Public Member Functions
NetworkHailo (std::string const &instance)
Constructor.
virtual ~NetworkHailo ()
Destructor.
void freeze (bool doit) override
冻结/解冻参数，用户在运行时不应更改
virtual std::vector< vsi_nn_tensor_attr_t > inputShapes () override
Get shapes of all input tensors.
virtual std::vector< vsi_nn_tensor_attr_t > outputShapes () override
Get shapes of all output tensors.
Protected Member Functions
void load () override
Load from disk.
std::vector< cv::Mat > doprocess (std::vector< cv::Mat > const &blobs, std::vector< std::string > &info) override
Process input blobs and obtain output blobs.
void onParamChange (network::turbo const &par, bool const &newval) override
Related Functions
(Note that these are not member functions.)
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (turbo, bool, `Turbo mode. Has no significant effect on small or ` `fast networks. Use with caution as it may lead to overheating, not ` `recommended for production`, false, ParamCateg)
Parameter.
Constructor & Destructor Documentation
NetworkHailo()
jevois::dnn::NetworkHailo::NetworkHailo (std::string const & instance)
Constructor.
Definition at line 35 of file NetworkHailo.C.
 NetworkHailo()
jevois::dnn::NetworkHailo::~NetworkHailo () [virtual]
Destructor.
Definition at line 64 of file NetworkHailo.C.
Member Function Documentation
doprocess()
std::vector< cv::Mat > jevois::dnn::NetworkHailo::doprocess (std::vector< cv::Mat > const & blobs, std::vector< std::string > & info) [override], [protected], [virtual]
Process input blobs and obtain output blobs.
Implements jevois::dnn::Network.
Definition at line 168 of file NetworkHailo.C.
References jevois::async(), jevois::dnn::attrmatch(), jevois::dnn::attrstr(), jevois::dnn::dequantize(), jevois::joinall(), LFATAL, jevois::sformat(), jevois::dnn::shapestr(), and jevois::to_string().
freeze()
void jevois::dnn::NetworkHailo::freeze (bool doit) [override], [virtual]
冻结/解冻参数，用户在运行时不应更改
Reimplemented from jevois::dnn::Network.
Definition at line 72 of file NetworkHailo.C.
References jevois::dnn::Network::freeze().
inputShapes()
std::vector< vsi_nn_tensor_attr_t > jevois::dnn::NetworkHailo::inputShapes () [override], [virtual]
Get shapes of all input tensors.
Implements jevois::dnn::Network.
Definition at line 56 of file NetworkHailo.C.
load()
void jevois::dnn::NetworkHailo::load () [override], [protected], [virtual]
Load from disk.
Implements jevois::dnn::Network.
Definition at line 80 of file NetworkHailo.C.
References jevois::absolutePath(), jevois::dnn::attrdims(), jevois::dnn::attrmat(), jevois::dnn::attrstr(), HAILO_CHECK, LERROR, LFATAL, LINFO, and jevois::dnn::tensorattr().
onParamChange()
void jevois::dnn::NetworkHailo::onParamChange (network::turbo const & par, bool const & newval) [override], [protected]
Definition at line 162 of file NetworkHailo.C.
outputShapes()
std::vector< vsi_nn_tensor_attr_t > jevois::dnn::NetworkHailo::outputShapes () [override], [virtual]
Get shapes of all output tensors.
Implements jevois::dnn::Network.
Definition at line 60 of file NetworkHailo.C.
Friends And Related Function Documentation
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK()
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (turbo , bool , `Turbo mode. Has no significant effect on small or ` `fast networks. Use with caution as it may lead to overheating, not ` `recommended for production` , false , ParamCateg) [related]
Parameter.
The documentation for this class was generated from the following files:
include/jevois/DNN/NetworkHailo.H
include/jevois/DNN/Network.H
src/jevois/DNN/NetworkHailo.C