jevois::Module Class Reference
#include <jevois/Core/Module.H>
视觉处理模块的虚基类
Module 是实现摄像头到 USB 逐帧视频处理的基类。 Engine 根据最终用户选择的当前 VideoMapping（例如，主机上的网络摄像 头查看程序设置的当前图像分辨率、格式和帧速率）实例化一个从 Module 派生的类。 根据 videomappings.cfg 中的 VideoMapping 定义和用户选择的当前 VideoMapping，Module 被加载为共享对象 (.so) 文件。
Module 自 Component，因此可以包含：
任意数量的 Parameter 设置
任意复杂的 Component 对象子层次结构，用于实现各种功能。所有子组件的 Parameter 设置均可供 Module 和 Engine 使用。
这样，人们就可以高效地实现复杂的视觉处理管道，并大量重复使用代码。例如，人们可能首先想要实现一个 EdgeDetector 或 Saliency 组件，并为各种阈值、特征等设置 Parameter。然后，人们可以创建任意数量的顶级对象，这些对象派生自 Module， 并且可能在子组件层次结构中包含一个或多个 EdgeDetector、Saliency 等组件，模块中的实现只是将图像从一个 Component 路由到另一个，以创建处理管道。
从 Module 派生的类应该实现最多四个函数：
当当前 VideoMapping 同时指定特定的相机分辨率和格式以及 USB 分辨率和格式时，Engine 主循环每次迭代都会调用一次 process(InputFrame && inframe, OutputFrame && outframe)。此函数应处理接收到的输入帧并用结果填充输出帧的像素缓冲 区。在调用 process() 之前，已经为输入和输出图像分配了内存。由于输出图像实际上是由 USB Gadget 驱动程序（最终由 Linux 内核）分配的，因此其像素内存位置无法移动（因此，不要尝试复制输出图像或用另一个图像替换它等；只需将像素数 据写入输出图像的像素阵列）。视频模式或帧速率没有限制，除非 Camera 硬件支持，并且受 USB 带宽限制。对于大多数实现 ，匹配输入和输出帧速率是最简单的，这意味着每次调用 process() 都会访问和使用提供的 InputFrame 和 OutputFrame（一 输入一输出处理管道）。但这不是强制性的。例如，用于飞行无人机的运动流计算 Module 可能具有 320x240 YUYV 53.0fps 输入和 100x142 GREY 10.6fps 输出（由于此示例中的输出帧速率比输入低 5 倍，因此 process() 函数每调用 5 次才会获取 、填充和发送一次 OutputFrame；process() 函数的实现应该跟踪这一点，例如，通过每次调用 process() 时递增的成员变量 ）。除了填充 OutputFrame 的像素数据之外，process() 还可以使用 sendSerial() 通过串行端口发送结果（例如，供连接到 JeVois 平台硬件的 Arduino 使用）。
当当前 VideoMapping 指定特定的相机分辨率和格式，并且 USB 输出格式为 NONE 时，每个 Camera 帧调用一次 process(InputFrame && inframe)。此函数应处理接收到的输入帧，然后通常使用 sendSerial() 将结果发送到串行端口（例 如，供连接到 JeVois 平台硬件的 Arduino 使用）。对视频模式或帧速率没有限制，除非 Camera 硬件支持。
parseSerial(std::string const & str, std::shared_ptr<UserInterface> s) 允许 Module 支持自定义用户命令。Engine 会将串行或其他它 UserInterface 收到的不理解的任何命令转发给此函数。您应该将其用于超出 Parameter 设置（ Engine 本身已经支持）或 Engine 内置命令（参见 命令行界面用户指南 ）的范围。例如，可以在此处实现一个名为 `start` 的命令 ，以允许用户启动某些特定的东西。
supportsCommands(std::ostream & os) 应输出 parseSerial() 支持的任何自定义命令的可读描述。当用户通过 Serial 端口 输入 `help` 时，将显示这些描述。
Note
每个模块实现文件都应包含对模块类的 JEVOIS_REGISTER_MODULE(MODULENAME) 的调用。这会创建一些纯 C 入口点，当 从动态库 (.so) 文件加载模块以实例化模块时，将使用这些入口点。有关示例，请参阅 关于如何为 JeVois 编写新的机器视觉模块的教程 。
Definition at line 89 of file Module.H.
Public Member Functions
Module (std::string const &instance)
Constructor.
virtual ~Module ()
用于安全继承的虚拟析构函数
virtual void process (InputFrame &&inframe, OutputFrame &&outframe)
处理函数，从相机接收帧并通过 USB 发送帧的版本
virtual void process (InputFrame &&inframe)
处理函数，从相机接收帧但不使用 USB 的版本
virtual void process (InputFrame &&inframe, GUIhelper &helper)
处理函数，从相机接收帧的版本，没有 USB，但在 JeVois-Pro 上有 GUI 输出
virtual void sendSerial (std::string const &str)
通过 'serout' 串行端口发送字符串
virtual void parseSerial (std::string const &str, std::shared_ptr< UserInterface > s)
从串行端口接收包含用户命令的字符串
virtual void supportedCommands (std::ostream &os)
此模块支持的自定义命令的可读描述
Additional Inherited Members
Constructor & Destructor Documentation
Module()
jevois::Module::Module (std::string const & instance)
Constructor.
instance 是一个用户定义的字符串，可用于区分同一模块的多个实例。
Definition at line 31 of file Module.C.
 Module()
jevois::Module::~Module () [virtual]
用于安全继承的虚拟析构函数
Definition at line 36 of file Module.C.
Member Function Documentation
parseSerial()
void jevois::Module::parseSerial (std::string const & str, std::shared_ptr< UserInterface > s) [virtual]
从串行端口接收包含用户命令的字符串
Reimplemented in jevois::PythonModule.
Definition at line 63 of file Module.C.
Referenced by jevois::PythonModule::parseSerial().
process() [1/3]
void jevois::Module::process (InputFrame && inframe) [virtual]
处理函数，从相机接收帧但不使用 USB 的版本
此函数对相机抓取的每个视频帧调用一次，并且应在相机的帧周期内完成以避免丢帧。InputFrame 对象是一个简单的包装器，以确 保即使处理函数在处理过程中的任何时间点抛出，低级视频缓冲区也将始终返回到低级相机驱动程序。如果发生任何错误，因此可以随 时从 process() 中抛出，只需确保您的本地分配资源将被释放，这通常最好通过使用 shared_ptr 和类似的包装器来实现。 Engine （它为您的模块调用每个帧的 process()）将捕获任何异常并继续下一帧。
基类中的默认实现只是抛出。派生类应该覆盖它。
Reimplemented in jevois::PythonModule.
Definition at line 44 of file Module.C.
References LFATAL.
process() [2/3]
void jevois::Module::process (InputFrame && inframe, GUIhelper & helper) [virtual]
处理函数，从相机接收帧的版本，没有 USB，但在 JeVois-Pro 上有 GUI 输出
此函数对相机抓取的每个视频帧调用一次，并且应在相机的帧周期内完成以避免丢帧。InputFrame 对象是一个简单的包装器，以确保 即使处理函数在处理过程中的任何时候抛出，低级视频缓冲区也将始终返回到低级相机驱动程序。如果发生任何错误，因此可以随时从 process() 中抛出，只需确保您的本地分配资源将被释放，这通常最好通过使用 shared_ptr 和类似的包装器来实现。 Engine （ 它为您的模块的每一帧调用 process()）将捕获任何异常并继续下一帧。
基类中的默认实现只是抛出。派生类应该覆盖它。
Reimplemented in jevois::PythonModule.
Definition at line 49 of file Module.C.
References LFATAL.
process() [3/3]
void jevois::Module::process (InputFrame && inframe, OutputFrame && outframe) [virtual]
处理函数，从相机接收帧并通过 USB 发送帧的版本
此函数对相机抓取的每个视频帧调用一次，并且应在相机的帧周期内完成以避免丢帧。InputFrame 和 OutputFrame 对象是简单的 包装器，以确保即使处理函数在处理过程中的任何时间点抛出，低级视频缓冲区也将始终返回到低级相机和 USB 驱动程序。如果发生 任何错误，可以随时从 process() 中抛出，只需确保您的本地分配资源将被释放，这通常最好通过使用 shared_ptr 和类似的包装器 来实现。 Engine （它为您的模块调用每个帧的 process()）将捕获任何异常并继续下一帧。
基类中的默认实现只是抛出。派生类应该覆盖它。
Reimplemented in jevois::PythonModule.
Definition at line 40 of file Module.C.
References LFATAL.
sendSerial()
void jevois::Module::sendSerial (std::string const & str) [virtual]
通过 'serout' 串行端口发送字符串
默认实现只是将字符串发送到 Engine 中 'serout' Parameter 指定的串行端口（可以是硬件串行端口、USB 串行端口、两者或都不是 ；有关 serout 的信息，请参阅 命令行界面用户指南 ）。大多数情况下无需覆盖。通常，您会在 process() 中使用此函数来发送一些处 理结果。
请注意，Engine 中默认的 'serout' Parameter 设置为 None。这是为了让用户在视觉处理的串行输出流开始之前配置参数、获取参数 值、可能阅读帮助消息等。一旦准备好接收串行输出，通常会通过 JeVois 命令行发出命令 'setpar serout Hard '以启用到硬件串行 端口的串行输出。Arduino 会在准备好工作时发出该 setpar 命令。有关示例，请参阅 ArduinoTutorial。
Definition at line 54 of file Module.C.
References LFATAL, and jevois::Engine::sendSerial().
supportedCommands()
void jevois::Module::supportedCommands (std::ostream & os) [virtual]
此模块支持的自定义命令的可读描述
此处的格式是免费的。只需使用 std::endl 来划分行，这些行将由串行端口转换为适当的行尾。默认实现将 `None` 写入 os。
Reimplemented in jevois::PythonModule.
Definition at line 67 of file Module.C.
Referenced by jevois::PythonModule::supportedCommands().
The documentation for this class was generated from the following files:
include/jevois/Core/Module.H
src/jevois/Core/Module.C