jevois::VideoBuf Class Reference
#include <jevois/Core/VideoBuf.H>
V4L2 视频缓冲区，保存在 shared_ptr 中
在构造时从给定的文件描述符请求 MMAP 的内存区域，并在析构时取消映射。VideoBuf 用于通过 RawImage 将 MMAP 的视频缓冲 区从 Camera 和 Gadget 驱动程序传递到应用程序代码。实际的内存分配由内核驱动程序执行。因此，VideoBuf 像素数组不能从 一个内存位置移动到另一个内存位置。
Definition at line 28 of file VideoBuf.H.
Public Member Functions
VideoBuf (int const fd, size_t const length, unsigned int offset, int const dmafd)
构造和分配 MMAP 的内存
~VideoBuf ()
析构函数取消内存映射
void sync ()
同步数据
void * data () const
获取指向缓​​冲区数据的指针
size_t length () const
获取分配的内存长度
void setBytesUsed (size_t n)
设置使用的字节数，例如，对于应用程序代码压缩到缓冲区的 MJPEG 图像
size_t bytesUsed () const
获取已使用的字节数，仅对MJPEG图像有效
int dmaFd () const
获取与此缓冲区关联的 dma_buf fd，该 fd 在构造时给出
Constructor & Destructor Documentation
VideoBuf()
jevois::VideoBuf::VideoBuf (int const fd, size_t const length, unsigned int offset, int const dmafd)
构造和分配 MMAP 的内存
主要用于调试目的（支持 VideoDisplay），如果 fd 为 -1，则我们执行常规内存分配而不是 mmap。
Definition at line 27 of file VideoBuf.C.
References length(), and PLFATAL.
 VideoBuf()
jevois::VideoBuf::~VideoBuf ()
析构函数取消内存映射
Definition at line 49 of file VideoBuf.C.
References PLERROR.
Member Function Documentation
bytesUsed()
size_t jevois::VideoBuf::bytesUsed () const
获取已使用的字节数，仅对MJPEG图像有效
Definition at line 123 of file VideoBuf.C.
data()
void * jevois::VideoBuf::data () const
获取指向缓​​冲区数据的指针
Definition at line 105 of file VideoBuf.C.
dmaFd()
int jevois::VideoBuf::dmaFd () const
获取与此缓冲区关联的 dma_buf fd，该 fd 在构造时给出
Definition at line 129 of file VideoBuf.C.
length()
size_t jevois::VideoBuf::length () const
获取分配的内存长度
Definition at line 111 of file VideoBuf.C.
Referenced by VideoBuf().
setBytesUsed()
void jevois::VideoBuf::setBytesUsed (size_t n)
设置使用的字节数，例如，对于应用程序代码压缩到缓冲区的 MJPEG 图像
Definition at line 117 of file VideoBuf.C.
sync()
void jevois::VideoBuf::sync ()
同步数据
这在某些情况下可能很有用，可以避免支持 DMA 的驱动程序和 CPU 之间的缓存一致性问题。
Definition at line 85 of file VideoBuf.C.
References clearcache(), and LERROR.
The documentation for this class was generated from the following files:
include/jevois/Core/VideoBuf.H
src/jevois/Core/VideoBuf.C