jevois::dnn::Pipeline Class Reference
#include <jevois/DNN/Pipeline.H>
神经处理管道
JeVois 中的神经处理管道包括：
pre-processing 输入图像以提取一个或多个 blobs，用作深度神经网络的输入 tensors
通过深度网络处理输入 blob 并获得输出 blob
post-processing 输出 blob，显示结果并发送串行消息
Pipline 通常通过解析 YAML 配置文件（zoo 文件）来配置，该文件确定要使用哪种类型的 pre-processing、network 和 post-processing，并为其设置参数。
Definition at line 133 of file Pipeline.H.
Public Member Functions
Pipeline (std::string const &instance)
Constructor.
virtual ~Pipeline ()
Destructor.
bool ready () const
当 preproc、net、postproc 三者都准备就绪时返回 true
void process (jevois::RawImage const &inimg, jevois::StdModule *mod, jevois::RawImage *outimg, jevois::OptGUIhelper *helper, bool idle=false)
处理输入图像，将结果发送到 serial/image/gui
void freeze (bool doit)
冻结/解冻运行时用户不应更改的参数
Protected Member Functions
void postInit () override
Called after all sub-Components are init()ed.
void preUninit () override
Called before all sub-Components are uninit()ed.
void reloadZoo (std::string const &root, std::string const &filt, std::string const &zoofile)
void onParamChange (pipeline::zooroot const &param, std::string const &val) override
void onParamChange (pipeline::zoo const &param, std::string const &val) override
void onParamChange (pipeline::filter const &param, pipeline::Filter const &val) override
void onParamChange (pipeline::pipe const &param, std::string const &val) override
void onParamChange (pipeline::nettype const &param, pipeline::NetType const &val) override
void onParamChange (pipeline::preproc const &param, pipeline::PreProc const &val) override
void onParamChange (pipeline::postproc const &param, pipeline::PostProc const &val) override
void onParamChange (pipeline::benchmark const &param, bool const &val) override
void showInfo (std::vector< std::string > const &info, jevois::StdModule *mod, jevois::RawImage *outimg, jevois::OptGUIhelper *helper, bool ovl, bool idle)
void asyncNetWait ()
bool checkAsyncNetComplete ()
void showDataPeekWindow (jevois::GUIhelper *helper, bool refresh)
Protected Attributes
std::shared_ptr< PreProcessor > itsPreProcessor
std::shared_ptr< Network > itsNetwork
std::shared_ptr< PostProcessor > itsPostProcessor
Related Functions
(Note that these are not member functions.)
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (zooroot, std::string, `Path where to find zoo files (.yml). ` `If not absolute, it is relative to this module's path`, JEVOIS_SHARE_PATH `/dnn`, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (zoo, std::string, `Filename for neural network zoo file (.yml). ` `If not absolute, it is relative to zooroot`, `models.yml`, ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (Filter,(All)(OpenCV)(TPU)(NPU)(VPU)(VPUX)(NPUX)(SPU)(ORT))
Enum.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (filter, Filter, `Filter to possibly only show as options in ` `the 'pipe' parameter some class of models from the zoo`, Filter::All, Filter_Values, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (pipe, std::string, `Pipeline to use, which should correspond to a ` `top-level entry in the zoo file. Network execution types are: OpenCV: ` `on CPU, NPU: on JeVois NPU accelerator, TPU: on Coral Edge TPU if ` `available, VPU: on MyriadX VPU if available, NPUX: on NPU via TimVX ` `OpenCV extension, VPUX: on CPU via ARM-Compute OpenVino emulation ` `of VPU, and SPU: on Hailo8 SPU if available.`, ``, ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (PreProc,(Blob)(Python))
Enum.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (preproc, PreProc, `Pre-Processor to use, usually set automatically ` `by selecting a pipeline from the zoo file`, PreProc::Blob, PreProc_Values, ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (NetType,(OpenCV)(ORT)(NPU)(TPU)(SPU)(Python))
Enum.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (nettype, NetType, `Network runtime framework to use, usually set ` `automatically by selecting a pipeline from the zoo file`, NetType::OpenCV, NetType_Values, ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (PostProc,(Classify)(Detect)(Segment)(YuNet)(Python)(Stub))
Enum.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (postproc, PostProc, `Post-Processor to use, usually set automatically ` `by selecting a pipeline from the zoo file`, PostProc::Classify, PostProc_Values, ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (Processing,(Sync)(Async))
Enum.
JEVOIS_DECLARE_PARAMETER (processing, Processing, `Type of processing: Sync runs pre-processing, ` `network, and post-processing sequentially for every frame. Use for fast ` `networks only, otherwise it will slow down the GUI... Async runs the network in ` `a thread and should be used for networks slower than the camera framerate.`, Processing::Async, Processing_Values, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (overlay, bool, `Show some pipeline info as an overlay over output or GUI video`, true, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (paramwarn, bool, `Issue warning if parameters are specified in the zoo file for ` `a pipeline, but the pipeline's component is not using them. Warnings appear ` `in the console when the pipeline is loaded.`, true, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (statsfile, std::string, `Append pre/net/post timing statistics in HTML table format ` `to the specified file if not empty. If path is relative, it is to ` JEVOIS_SHARE_PATH, ``, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (benchmark, bool, `Cycle through all networks specified by filter and, ` `for each, run it for a while and append pre/net/post timing statistics ` `in HTML table format to ` JEVOIS_SHARE_PATH `/benchmark.html`, false, ParamCateg)
Parameter.
Constructor & Destructor Documentation
Pipeline()
jevois::dnn::Pipeline::Pipeline (std::string const & instance)
Constructor.
Definition at line 104 of file Pipeline.C.
References jevois::getNumInstalledNPUs(), jevois::getNumInstalledSPUs(), jevois::getNumInstalledTPUs(), jevois::getNumInstalledVPUs(), and LINFO.
 Pipeline()
jevois::dnn::Pipeline::~Pipeline () [virtual]
Destructor.
Definition at line 153 of file Pipeline.C.
Member Function Documentation
asyncNetWait()
void jevois::dnn::Pipeline::asyncNetWait () [protected]
Definition at line 160 of file Pipeline.C.
References LERROR.
checkAsyncNetComplete()
bool jevois::dnn::Pipeline::checkAsyncNetComplete () [protected]
Definition at line 641 of file Pipeline.C.
freeze()
void jevois::dnn::Pipeline::freeze (bool doit)
冻结/解冻运行时用户不应更改的参数
Definition at line 127 of file Pipeline.C.
onParamChange() [1/8]
void jevois::dnn::Pipeline::onParamChange (pipeline::benchmark const & param, bool const & val) [override], [protected]
Definition at line 192 of file Pipeline.C.
onParamChange() [2/8]
void jevois::dnn::Pipeline::onParamChange (pipeline::filter const & param, pipeline::Filter const & val) [override], [protected]
onParamChange() [3/8]
void jevois::dnn::Pipeline::onParamChange (pipeline::nettype const & param, pipeline::NetType const & val) [override], [protected]
Definition at line 543 of file Pipeline.C.
References LFATAL, and LINFO.
onParamChange() [4/8]
void jevois::dnn::Pipeline::onParamChange (pipeline::pipe const & param, std::string const & val) [override], [protected]
Definition at line 333 of file Pipeline.C.
onParamChange() [5/8]
void jevois::dnn::Pipeline::onParamChange (pipeline::postproc const & param, pipeline::PostProc const & val) [override], [protected]
Definition at line 602 of file Pipeline.C.
References LINFO.
onParamChange() [6/8]
void jevois::dnn::Pipeline::onParamChange (pipeline::preproc const & param, pipeline::PreProc const & val) [override], [protected]
Definition at line 523 of file Pipeline.C.
References LINFO.
onParamChange() [7/8]
void jevois::dnn::Pipeline::onParamChange (pipeline::zoo const & param, std::string const & val) [override], [protected]
Definition at line 207 of file Pipeline.C.
References jevois::absolutePath(), and LINFO.
onParamChange() [8/8]
void jevois::dnn::Pipeline::onParamChange (pipeline::zooroot const & param, std::string const & val) [override], [protected]
Definition at line 184 of file Pipeline.C.
postInit()
void jevois::dnn::Pipeline::postInit () [override], [protected], [virtual]
Called after all sub-Components are init()ed.
Reimplemented from jevois::Component.
Definition at line 139 of file Pipeline.C.
preUninit()
void jevois::dnn::Pipeline::preUninit () [override], [protected], [virtual]
Called before all sub-Components are uninit()ed.
Reimplemented from jevois::Component.
Definition at line 146 of file Pipeline.C.
process()
void jevois::dnn::Pipeline::process (jevois::RawImage const & inimg, jevois::StdModule * mod, jevois::RawImage * outimg, jevois::OptGUIhelper * helper, bool idle = false)
处理输入图像，将结果发送到 serial/image/gui
如果网络未 ready，则不会进行任何处理。当 helper 不为null时（即使用 GUI 显示），当 idle 为 true 时隐藏信息 窗口。该函数捕获所有异常并报告它们。
Definition at line 656 of file Pipeline.C.
References jevois::absolutePath(), jevois::async(), jevois::GUIhelper::itext(), JEVOIS_SHARE_PATH, jevois::join(), LINFO, jevois::replaceAll(), jevois::GUIhelper::reportAndIgnoreException(), jevois::GUIhelper::reportError(), jevois::secs2str(), jevois::dnn::shapestr(), jevois::split(), jevois::warnAndIgnoreException(), jevois::yuyv::White, and jevois::rawimage::writeText().
ready()
bool jevois::dnn::Pipeline::ready () const
当 preproc、net、postproc 三者都准备就绪时返回 true
Definition at line 635 of file Pipeline.C.
reloadZoo()
void jevois::dnn::Pipeline::reloadZoo (std::string const & root, std::string const & filt, std::string const & zoofile) [protected]
showDataPeekWindow()
void jevois::dnn::Pipeline::showDataPeekWindow (jevois::GUIhelper * helper, bool refresh) [protected]
Definition at line 1032 of file Pipeline.C.
References jevois::GUIhelper::combo(), jevois::GUIhelper::reportError(), jevois::dnn::shapestr(), jevois::to_string(), and jevois::GUIhelper::toggleButton().
showInfo()
void jevois::dnn::Pipeline::showInfo (std::vector< std::string > const & info, jevois::StdModule * mod, jevois::RawImage * outimg, jevois::OptGUIhelper * helper, bool ovl, bool idle) [protected]
Definition at line 997 of file Pipeline.C.
References jevois::stringStartsWith(), jevois::yuyv::White, and jevois::rawimage::writeText().
Friends And Related Function Documentation
JEVOIS_DECLARE_PARAMETER() [1/4]
JEVOIS_DECLARE_PARAMETER (overlay , bool , `Show some pipeline info as an overlay over output or GUI video` , true , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [2/4]
JEVOIS_DECLARE_PARAMETER (paramwarn , bool , `Issue warning if parameters are specified in the zoo file for ` `a pipeline, but the pipeline 's component is not using them. Warnings appear ` `in the console when the pipeline is loaded.` , true , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [3/4]
JEVOIS_DECLARE_PARAMETER (processing , Processing , `Type of processing: Sync runs pre- processing, ` ` network, and post-processing sequentially for every frame. Use for fast ` `networks only, otherwise it will slow down the GUI... Async runs the network in ` `a thread and should be used for networks slower than the camera framerate.` , Processing::Async , Processing_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [4/4]
JEVOIS_DECLARE_PARAMETER (statsfile , std::string , `Append pre/net/post timing statistics in HTML table format ` `to the specified file if not empty. If path is relative, it is to ` JEVOIS_SHARE_PATH, `` , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [1/8]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (benchmark , bool , `Cycle through all networks specified by filter and, ` `for each, run it for a while and append pre/net/post timing statistics ` `in HTML table format to ` JEVOIS_SHARE_PATH `/benchmark.html` , false , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [2/8]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (filter , Filter , `Filter to possibly only show as options in ` `the 'pipe' parameter some class of models from the zoo` , Filter::All , Filter_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [3/8]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (nettype , NetType , `Network runtime framework to use, usually set ` `automatically by selecting a pipeline from the zoo file` , NetType::OpenCV , NetType_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [4/8]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (pipe , std::string , `Pipeline to use, which should correspond to a ` `top-level entry in the zoo file. Network execution types are:OpenCV:` `on CPU, NPU:on JeVois NPU accelerator, TPU:on Coral Edge TPU if ` ` available, VPU:on MyriadX VPU if available, NPUX:on NPU via TimVX ` `OpenCV extension, VPUX:on CPU via ARM-Compute OpenVino emulation ` `of VPU, and SPU:on Hailo8 SPU if available.` , `` , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [5/8]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (postproc , PostProc , `Post-Processor to use, usually set automatically ` `by selecting a pipeline from the zoo file` , PostProc::Classify , PostProc_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [6/8]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (preproc , PreProc , `Pre-Processor to use, usually set automatically ` `by selecting a pipeline from the zoo file` , PreProc::Blob , PreProc_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [7/8]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (zoo , std::string , `Filename for neural network zoo file (.yml). ` `If not absolute, it is relative to zooroot` , `models.yml` , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [8/8]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (zooroot , std::string , `Path where to find zoo files (.yml). ` `If not absolute, it is relative to this module 's path` , JEVOIS_SHARE_PATH `/dnn` , ParamCateg) [related]
Parameter.
JEVOIS_DEFINE_ENUM_CLASS() [1/5]
JEVOIS_DEFINE_ENUM_CLASS (Filter , (All)(OpenCV)(TPU)(NPU)(VPU)(VPUX)(NPUX)(SPU)(ORT)) [related]
Enum.
JEVOIS_DEFINE_ENUM_CLASS() [2/5]
JEVOIS_DEFINE_ENUM_CLASS (NetType , (OpenCV)(ORT)(NPU)(TPU)(SPU)(Python)) [related]
Enum.
JEVOIS_DEFINE_ENUM_CLASS() [3/5]
JEVOIS_DEFINE_ENUM_CLASS (PostProc , (Classify)(Detect)(Segment)(YuNet)(Python)(Stub)) [related]
Enum.
JEVOIS_DEFINE_ENUM_CLASS() [4/5]
JEVOIS_DEFINE_ENUM_CLASS (PreProc , (Blob)(Python)) [related]
Enum.
JEVOIS_DEFINE_ENUM_CLASS() [5/5]
JEVOIS_DEFINE_ENUM_CLASS (Processing , (Sync)(Async)) [related]
Enum.
Member Data Documentation
itsNetwork
std::shared_ptr<Network> jevois::dnn::Pipeline::itsNetwork [protected]
Definition at line 162 of file Pipeline.H.
itsPostProcessor
std::shared_ptr<PostProcessor> jevois::dnn::Pipeline::itsPostProcessor [protected]
Definition at line 163 of file Pipeline.H.
itsPreProcessor
std::shared_ptr<PreProcessor> jevois::dnn::Pipeline::itsPreProcessor [protected]
Definition at line 161 of file Pipeline.H.
The documentation for this class was generated from the following files:
include/jevois/DNN/Pipeline.H
src/jevois/DNN/Pipeline.C