jevois::dnn::PreProcessorPythonImpl Class Reference
Definition at line 28 of file PreProcessorPython.C.
Public Member Functions
void loadpy (std::string const &pypath)
virtual ~PreProcessorPythonImpl ()
void freeze (bool doit)
std::vector< cv::Mat > process (cv::Mat const &img, bool swaprb, std::vector< vsi_nn_tensor_attr_t > const &attrs, std::vector< cv::Rect > &crops)
void report (jevois::StdModule *mod, jevois::RawImage *outimg=nullptr, jevois::OptGUIhelper *helper=nullptr, bool overlay=true, bool idle=false)
Component (std::string const &instance)
Constructor.
Additional Inherited Members
Constructor & Destructor Documentation
 PreProcessorPythonImpl()
jevois::dnn::PreProcessorPythonImpl::~PreProcessorPythonImpl () [virtual]
Definition at line 45 of file PreProcessorPython.C.
Member Function Documentation
Component()
jevois::Component::Component
Constructor.
创建组件的标准方法是通过 Component::addSubComponent() 或 Manager::addComponent()，而不是手动构建。通过构造函数构造的组件 （例如，调用 new 操作符）将不会附加到 Component 层次结构。建议派生组件也有一个实例构造函数参数并将其传递给 base Component 类， 以允许复杂系统包含同一 Component 的多个实例。事实上，对于大多数组件来说，继承的构造函数是合适的：
class MyComp : public jevois::Component
{
public:
  // 继承的构造函数
  using jevois::Component::Component;
  // 用于安全继承的虚拟析构函数
  virtual ~MyComp();
};
Definition at line 32 of file Component.C.
freeze()
void jevois::dnn::PreProcessorPythonImpl::freeze (bool doit)
Definition at line 49 of file PreProcessorPython.C.
References jevois::python::hasattr(), and jevois::PythonWrapper::pyinst().
loadpy()
void jevois::dnn::PreProcessorPythonImpl::loadpy (std::string const & pypath)
Definition at line 55 of file PreProcessorPython.C.
References jevois::python::hasattr(), JEVOIS_SHARE_PATH, LINFO, jevois::PythonWrapper::pyinst(), and jevois::PythonWrapper::pythonload().
process()
std::vector< cv::Mat > jevois::dnn::PreProcessorPythonImpl::process (cv::Mat const & img, bool swaprb, std::vector< vsi_nn_tensor_attr_t > const & attrs, std::vector< cv::Rect > & crops)
Definition at line 66 of file PreProcessorPython.C.
References jevois::dnn::attrstr(), CROPERR, h, jevois::PythonWrapper::pyinst(), and jevois::to_string().
report()
void jevois::dnn::PreProcessorPythonImpl::report (jevois::StdModule * mod, jevois::RawImage * outimg = nullptr, jevois::OptGUIhelper * helper = nullptr, bool overlay = true, bool idle = false)
Definition at line 109 of file PreProcessorPython.C.
References jevois::PythonWrapper::pyinst().
The documentation for this class was generated from the following file:
src/jevois/DNN/PreProcessorPython.C