jevois::dnn::PostProcessorPythonImpl Class Reference
Definition at line 28 of file PostProcessorPython.C.
Public Member Functions
void loadpy (std::string const &pypath)
virtual ~PostProcessorPythonImpl ()
void freeze (bool doit)
void process (std::vector< cv::Mat > const &outs, PreProcessor *preproc)
void report (jevois::StdModule *mod, jevois::RawImage *outimg=nullptr, jevois::OptGUIhelper *helper=nullptr, bool overlay=true, bool idle=false)
Component (std::string const &instance)
Constructor.
Additional Inherited Members
Constructor & Destructor Documentation
 PostProcessorPythonImpl()
jevois::dnn::PostProcessorPythonImpl::~PostProcessorPythonImpl () [virtual]
Definition at line 44 of file PostProcessorPython.C.
Member Function Documentation
Component()
jevois::Component::Component
Constructor.
创建组件的标准方法是通过 Component::addSubComponent() 或 Manager::addComponent()，而不是手动构建。通过构造函数构造的组件 （例如，调用 new 操作符）将不会附加到 Component 层次结构。建议派生组件也有一个实例构造函数参数并将其传递给 base Component 类， 以允许复杂系统包含同一 Component 的多个实例。事实上，对于大多数组件来说，继承的构造函数是合适的：
class MyComp : public jevois::Component
{
public:
  // 继承的构造函数
  using jevois::Component::Component;
  // 用于安全继承的虚拟析构函数
  virtual ~MyComp();
};
Definition at line 32 of file Component.C.
freeze()
void jevois::dnn::PostProcessorPythonImpl::freeze (bool doit)
Definition at line 48 of file PostProcessorPython.C.
References jevois::python::hasattr(), and jevois::PythonWrapper::pyinst().
loadpy()
void jevois::dnn::PostProcessorPythonImpl::loadpy (std::string const & pypath)
Definition at line 54 of file PostProcessorPython.C.
References jevois::python::hasattr(), JEVOIS_SHARE_PATH, LINFO, jevois::PythonWrapper::pyinst(), and jevois::PythonWrapper::pythonload().
process()
void jevois::dnn::PostProcessorPythonImpl::process (std::vector< cv::Mat > const & outs, PreProcessor * preproc)
Definition at line 65 of file PostProcessorPython.C.
References jevois::dnn::PreProcessor::getPreProcForPy(), jevois::PythonWrapper::pyinst(), and jevois::python::pyVecToList().
report()
void jevois::dnn::PostProcessorPythonImpl::report (jevois::StdModule * mod, jevois::RawImage * outimg = nullptr, jevois::OptGUIhelper * helper = nullptr, bool overlay = true, bool idle = false)
Definition at line 73 of file PostProcessorPython.C.
References jevois::PythonWrapper::pyinst().
The documentation for this class was generated from the following file:
src/jevois/DNN/PostProcessorPython.C