jevois::dnn::PostProcessorDetectYOLO Class Reference
#include <jevois/DNN/PostProcessorDetectYOLO.H>
用于原始 YOLO 解码的后处理器子组件
Definition at line 27 of file PostProcessorDetectYOLO.H.
Public Member Functions
virtual ~PostProcessorDetectYOLO ()
Destructor.
void freeze (bool doit)
冻结/解冻用户在运行时不应更改的参数
void yolo (std::vector< cv::Mat > const &outs, std::vector< int > &classIds, std::vector< float > &confidences, std::vector< cv::Rect > &boxes, size_t nclass, float boxThreshold, float confThreshold, cv::Size const &bsiz, int fudge, size_t const maxbox)
Generic raw YOLO processing.
Related Functions
(Note that these are not member functions.)
JEVOIS_DECLARE_PARAMETER (scalexy, float, `If 0, use old-style YOLO boxes (YOLOv2/v3/v4) otherwise, this is ` `the scale_xy factor for new-style YOLO coordinates (YOLOv5/v7 value is usually 2.0 ` `but check the yolo layer in the model's .cfg file)`, 0.0F, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (sigmoid, bool, `Apply sigmoid to raw YOLO outputs, use when the last conv layers ` `just before yolo/detection/region layers have linear activation (most ` `YOLOv2/v3/v4 models, but not YOLOv5/v7 which have logistic activation on their ` `last conv)`, true, ParamCateg)
Parameter.
Additional Inherited Members
Constructor & Destructor Documentation
 PostProcessorDetectYOLO()
jevois::dnn::PostProcessorDetectYOLO::~PostProcessorDetectYOLO () [virtual]
Destructor.
Definition at line 50 of file PostProcessorDetectYOLO.C.
Member Function Documentation
freeze()
void jevois::dnn::PostProcessorDetectYOLO::freeze (bool doit)
冻结/解冻用户在运行时不应更改的参数
Definition at line 54 of file PostProcessorDetectYOLO.C.
yolo()
void jevois::dnn::PostProcessorDetectYOLO::yolo (std::vector< cv::Mat > const & outs, std::vector< int > & classIds, std::vector< float > & confidences, std::vector< cv::Rect > & boxes, size_t nclass, float boxThreshold, float confThreshold, cv::Size const & bsiz, int fudge, size_t const maxbox)
Generic raw YOLO processing.
Definition at line 68 of file PostProcessorDetectYOLO.C.
References jevois::async(), jevois::joinall(), LINFO, LTHROW, jevois::sformat(), and jevois::dnn::shapestr().
Friends And Related Function Documentation
JEVOIS_DECLARE_PARAMETER() [1/2]
JEVOIS_DECLARE_PARAMETER (scalexy , float , `If 0, use old-style YOLO boxes(YOLOv2/v3/v4) otherwise, this is ` `the scale_xy factor for new-style YOLO coordinates(YOLOv5/v7 value is usually 2.0 ` `but check the yolo layer in the model 's .cfg file)` , 0. 0F, ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [2/2]
JEVOIS_DECLARE_PARAMETER (sigmoid , bool , `Apply sigmoid to raw YOLO outputs, use when the last conv layers ` `just before yolo/detection/region layers have linear activation(most ` `YOLOv2/v3/v4 models, but not YOLOv5/v7 which have logistic activation on their ` `last conv)` , true , ParamCateg) [related]
Parameter.
The documentation for this class was generated from the following files:
include/jevois/DNN/PostProcessorDetectYOLO.H
include/jevois/DNN/PostProcessor.H
src/jevois/DNN/PostProcessorDetectYOLO.C