jevois::Engine Class Reference
#include <jevois/Core/Engine.H>
JeVois processing engine - 从相机传感器获取图像，对其进行处理，并通过 USB 发送结果。
Engine 协调视觉处理软件的执行。它是一个 Manager ，即它是 Component 对象层次结构的根，它处理对其参数设置及其构造、 init()、 unInit() 和析构的访问。组件层次结构由根部的 Engine 和用户在运行时选择的 Module 组成，例如，在连接到 JeVois 硬件的主机上 运行的摄像机软件上选择给定的视频格式。然后， Module 可以包含任意复杂的 Component 对象层次结构，其中包含参数设置。Module 派生自 Component，因此也可能有自己的参数设置。
Engine 包含以下基本元素：
A VideoInput, 实例化为用于实时视频流的 Camera 或用于处理预先录制的视频文件或图像序列的 MovieInput （在算法开发期间有用， 用于测试和优化可再现的输入）；
A VideoOutput, 在 JeVois 硬件平台上运行时实例化为 USB Gadget 驱动程序，在有图形显示器的计算机上运行时实例化为 VideoDisplay， 或者实例化为 MovieOutput 将输出视频帧保存到磁盘，或者实例化为 VideoOutputNone （如果）需要对视觉算法进行基准测试，同时 忽略与传输输出帧相关的任何工作。
A DynamicLoader 根据用户选择在运行时加载所选的视觉处理 Module；
任意数量的 UserInterface 对象，实例化为硬件 Serial 端口（平台硬件上的 4 针 JST 1.0mm 连接器）、USB Serial 端口（在连接 JeVois 硬件的主机上可见）通过 USB），或 StdioInterface （直接在终端启动 JeVois Engine 接受命令并在终端打印结果，在通用 计算机而不是平台硬件上运行时特别有用）。当在平台硬件上运行时，通常会创建两个 UserInterface 对象（一个硬件 Serial ，一个通 过 USB Serial ），而在通用计算机上运行时，通常只创建一个 UserInterface （类型为 StdioInterface ）在终端启动 jevois-daemon 并且接受命令）；
从 videomappings.cfg 文件导入的 VideoMapping 定义列表。这些定义指定了使用的 Module 及其相应的 Camera 设置并使用 USB 输出的 模式，以及未通过 USB 流式视频输出的模式（例如，当将硬件平台连接到 Arduino 时）仅有的）。
Engine 的主循环一直运行到用户决定退出为止，基本上会经历以下步骤：
创建 InputFrame 对象，它是下一个可用 Camera 帧的异常安全包装器。该帧可能尚未捕获。InputFrame 可以被理解为一种机制，用于在 将来当该帧可用时（即相机已捕获）来访问该帧。这与 C++11 的 std::future 框架非常相似。
当当前 VideoMapping 指定通过 USB 流式传输视频帧时，还要创建一个 OutputFrame 对象，该对象是下一个可用 Gadget 帧的异常安全包装器。 这也是一种用于访问 USB 驱动程序提供的下一个空白视频缓冲区的机制，在通过 USB 将其发送到主机之前应该填充有趣的像素数据。
调用当前加载的 Module 的 process() 函数，当当前 VideoMapping 指定通过 USB 发送某些视频输出时，可以调用 process(InputFrame, OutputFrame) ， 或者当当前 VideoMapping 指定没有视频输出时，调用 process(InputFrame)。 Module 的 process() 函数抛出的任何异常都将 被捕获、报告和忽略。 process() 函数通常会通过 InputFrame 包装器请求下一个可用的相机图像（此请求可能会阻塞，直到相机 传感器硬件捕获该帧），处理该图像，通过 OutputFrame 包装器请求下一个可用的输出图像（当 VideoMapping 指定 USB 视频输出时）， 并将一些结果绘制到该输出图像中，然后将其通过 USB 发送到主机，以供某些网络摄像头程序显示或由运行在该输出图像上的某些自定义 视觉软件进一步处理。此外，当前加载的 Module 可以通过 UserInterface 端口发出消息（例如，指示找到目标的位置，以让 Arduino 知道它）。
读取用户通过 UserInterface 端口发出的任何新命令并执行适当的命令。
当用户在连接 JeVois 硬件的主机上运行的网络摄像头软件中选择不同的视频模式时，处理用户更改 VideoMapping 的请求。此类请求 可能会触发当前 Module 的卸载并加载新的 Module，并更改相机像素格式、图像大小等。这些更改保证在 Module 的 process() 函数 未运行时发生，即 Module 程序员不必担心在执行 process() 函数期间图像尺寸或像素格式可能发生的变化。
将通过 USB 或 UserInterface 接收到的任何用户请求传递给实际的 Camera 硬件驱动程序，以调整相机参数（例如，当用户更改网络 摄像头程序中的对比度时，该请求将通过 USB 发送到 Engine，然后 Engine 将其转发到 Camera 硬件驱动程序）。
Definition at line 377 of file Engine.H.
Public Member Functions
Engine (std::string const &instance)
Constructor.
Engine (int argc, char const *argv[], std::string const &instance)
Constructor with command-line parsing.
~Engine ()
Destructor.
void reloadVideoMappings ()
从 videomappings.cfg 重新加载视频映射。
const VideoMapping & findVideoMapping (unsigned int oformat, unsigned int owidth, unsigned int oheight, float oframespersec) const
查找具有给定输出规格的 VideoMapping，如果未找到则抛​​出
const VideoMapping & getCurrentVideoMapping () const
获取当前视频映射
size_t numVideoMappings () const
返回视频映射的数量
const VideoMapping & getVideoMapping (size_t idx) const
允许访问我们在构建时从文件解析的视频映射
size_t getVideoMappingIdx (unsigned int iformat, unsigned int iframe, unsigned int interval) const
获取给定 UVC iformat、iframe 和 interval 的视频映射索引
const VideoMapping & getDefaultVideoMapping () const
Allow access to the default video mapping.
size_t getDefaultVideoMappingIdx () const
Allow access to the default video mapping index.
void foreachVideoMapping (std::function< void(VideoMapping const &m)> &&func)
在每个视频映射上运行一个函数
void requestSetFormat (int idx)
使用它从 process() 中请求格式更改
void quit ()
Terminate the program.
void reboot ()
请求重启
void setFormat (size_t idx)
当用户选择新的输出视频格式时的回调
void streamOn ()
开始从相机、处理和 USB 流式传输视频
void streamOff ()
停止从相机、处理和 USB 流式传输视频
int mainLoop ()
主循环：抓取、处理、通过 USB 发送。应由主应用程序线程调用
void sendSerial (std::string const &str, bool islog=false)
向所有串行端口发送一个字符串
std::shared_ptr< Module > module () const
获取指向当前模块的指针（可能为空）
std::shared_ptr< Camera > camera () const
获取指向我们相机的指针（可能为空，特别是当不使用相机而是使用电影输入时）
void drawCameraGUI ()
将所有相机控件绘制到我们的 GUI 中
CameraCalibration loadCameraCalibration (std::string const &stem=`calibration`, bool do_throw=false)
为当前正在运行的模块加载 OpenCV 相机矩阵和失真系数的辅助函数
void saveCameraCalibration (CameraCalibration const &calib, std::string const &stem=`calibration`)
保存当前正在运行的模块的 OpenCV 相机矩阵和失真系数的辅助函数
void registerPythonComponent (Component *comp, void *pyinst)
将组件注册为链接到某些 python 代码，由在 python 中创建的动态参数使用
void unRegisterPythonComponent (Component *comp)
取消注册与某些 Python 代码链接的组件，由 Python 中创建的动态参数使用
Component * getPythonComponent (void *pyinst) const
获取使用给定 python 实例注册的组件
void reportError (std::string const &err)
void clearErrors ()
清除 JeVois-Pro GUI 中当前显示的所有错误
void nextDemo ()
处于演示模式时，切换到下一个演示
void abortDemo ()
处于演示模式时，中止演示模式
Protected Member Functions
void runScriptFromFile (std::string const &filename, std::shared_ptr< UserInterface > ser, bool throw_no_file)
从文件运行脚本
void onParamChange (engine::serialdev const &param, std::string const &newval) override
Parameter callback.
void onParamChange (engine::usbserialdev const &param, std::string const &newval) override
Parameter callback.
void onParamChange (engine::cpumode const &param, engine::CPUmode const &newval) override
Parameter callback.
void onParamChange (engine::cpumax const &param, unsigned int const &newval) override
Parameter callback.
void onParamChange (engine::videoerrors const &param, bool const &newval) override
Parameter callback.
void onParamChange (engine::gui const &param, bool const &newval) override
Parameter callback.
void onParamChange (engine::cpumaxl const &param, unsigned int const &newval) override
Parameter callback.
void onParamChange (engine::cpumodel const &param, engine::CPUmode const &newval) override
Parameter callback.
void onParamChange (engine::demomode const &param, float const &newval) override
Parameter callback.
void preInit () override
Override of Manager::preInit()
void postInit () override
Override of Manager::postInit()
bool parseCommand (std::string const &str, std::shared_ptr< UserInterface > s, std::string const &pfx=``)
解析通过串行端口接收到的用户命令
Protected Attributes
size_t itsDefaultMappingIdx
Index of default mapping.
std::vector< VideoMapping > itsMappings
来自 videomappings.cfg 的所有映射
VideoMapping itsCurrentMapping
当前映射，如果使用 setmapping2，则可能与 itsMappings 中的任何映射都不匹配
std::shared_ptr< VideoInput > itsCamera
Our camera.
std::shared_ptr< IMU > itsIMU
std::shared_ptr< VideoOutput > itsGadget
Our IMU.
std::unique_ptr< DynamicLoader > itsLoader
Our module loader.
std::shared_ptr< Module > itsModule
Our current module.
std::atomic< bool > itsRunning
True when we are running.
std::atomic< bool > itsStreaming
True when we are streaming video.
std::atomic< bool > itsStopMainLoop
Flag used to stop the main loop.
std::timed_mutex itsMtx
Mutex to protect our internals.
Related Functions
(Note that these are not member functions.)
size_t frameNum ()
获取当前视频处理帧号
JEVOIS_DECLARE_PARAMETER (cameradev, std::string, `Camera device name (if starting with /dev/v...), or movie ` `file name (e.g., movie.mpg) or image sequence (e.g., im%02d.jpg, to read frames ` `im00.jpg, im01.jpg, etc).`, JEVOIS_CAMERA_DEFAULT, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (camerasens, CameraSensor, `Camera sensor. Users would usually not set this parameter ` `manually, it is set through boot-time configuration.`, JEVOIS_CAMERASENS_DEFAULT, CameraSensor_Values, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (cameralens, CameraLens, `Camera lens. Users should usually not set this parameter ` `using the global JeVois params.cfg config file.`, CameraLens::standard, CameraLens_Values, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (cameranbuf, unsigned int, `Number of video input (camera) buffers, or 0 for automatic.`, 0, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (gadgetdev, std::string, `Gadget device name. This is used on platform hardware only. ` `On host hardware, a display window will be used unless gadgetdev is None (useful ` `for benchmarking) or is a file stem for a movie file that does not start with /dev/ ` `(and which should contain a printf-style directive for a single int argument, ` `the movie number).`, JEVOIS_GADGET_DEFAULT, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (gadgetnbuf, unsigned int, `Number of video output (USB video) buffers, or 0 for auto`, 0, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (videomapping, int, `Index of Video Mapping to use, or -1 to use the default mapping. ` `Note that this parameter is only available when parsing command-line arguments. ` `At runtime, the setmapping command should be used instead.`, -1, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (serialmonitors, bool, `If true, serial port monitors will be enabled ` `in the GUI, which can be used to peek at serial communications not ` `directed to the console. Can be turned off at start time (e.g., in the ` `global JeVois params.cfg) as there is some small CPU cost to it.`, true, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (serialdev, std::string, `Hardware (4-pin connector) serial device name, ` `or 'stdio' to use the console, or empty for no hardware serial port`, JEVOIS_SERIAL_DEFAULT, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (usbserialdev, std::string, `Over-the-USB serial device name, or empty`, JEVOIS_USBSERIAL_DEFAULT, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (camreg, bool, `Enable raw access to camera registers through setcamreg and getcamreg`, false, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (imureg, bool, `Enable raw access to IMU registers through setimureg and getimureg`, false, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (camturbo, bool, `Enable camera turbo mode by relaxing the need for DMA-coherent video ` `buffer memory. This can accelerate severalfolds access to the captured image data, but ` `it may also yield stripe artifacts with some modules, such as PassThrough. The stripes ` `are pieces of incorrect data in the cache. You should experiment with each particular ` `module. Turbo mode is not recommended for any production-grade application.`, false, ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (SerPort,(None)(All)(Hard)(USB))
Enum for Parameter.
JEVOIS_DECLARE_PARAMETER (serlog, SerPort, `Show log and debug messages on selected serial port(s)`, SerPort::None, SerPort_Values, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (videoerrors, bool, `Show any machine vision module errors (exceptions) ` `in the video stream. Only takes effect if streaming video to USB.`, true, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (serout, SerPort, `Send module serial messages to selected serial port(s)`, SerPort::None, SerPort_Values, ParamCateg)
Parameter.
JEVOIS_DEFINE_ENUM_CLASS (CPUmode,(PowerSave)(Conservative)(OnDemand)(Interactive)(Performance))
Enum for Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (cpumode, CPUmode, `CPU frequency modulation mode` ` for A73 big cores`, CPUmode::Performance, CPUmode_Values, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (cpumodel, CPUmode, `CPU frequency modulation mode for A53 little cores`, CPUmode::Performance, CPUmode_Values, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (cpumax, unsigned int, `CPU maximum frequency in MHz` `. To enable overclock frequencies above 2208 MHz, you need to first edit ` `/boot/env.txt and change max_freq_a73, then reboot. Use with caution!`, 2208, { 500, 667, 1000, 1200, 1398, 1512, 1608, 1704, 1800, 1908, 2016, 2100, 2208, 2304, 2400 }, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (cpumaxl, unsigned int, `CPU maximum frequency in MHz, for A53 little cores. ` `To enable overclock frequencies above 1800 MHz, you need to first edit ` `/boot/env.txt and change max_freq_a53, then reboot. Use with caution!`, 1800, { 500, 667, 1000, 1200, 1398, 1512, 1608, 1704, 1800, 1908, 2016, 2100, 2208 }, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (multicam, bool, `Allow up to 3 JeVois cameras on one USB bus. Enabling this ` `reduces the amount of USB bandwidth used by each JeVois camera, from 3kb ` `per USB isochronous microframe to 1kb. All 3 JeVois cameras must have this ` `option enabled, and the JeVois linux kernel module should also have ` `been loaded with multicam on.`, false, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (quietcmd, bool, `When true, do not issue a message 'OK' after every correct command ` `received at the command-line interface. Recommended for advanced users only.`, false, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (python, bool, `When true, enable support for modules written in Python. Otherwise, ` `attempting to load a python module will throw an exception. Disabling python saves ` `a lot of memory and may be useful when using C++ modules that run large deep neural ` `networks.`, true, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (serlimit, size_t, `Maximum number of serial messages that can be sent by a module ` `using sendSerial(), for each video frame, or 0 for no limit. Any message sent by ` `the module beyond the first serlimit ones will be dropped. This is useful to avoid ` `overloading the serial link, for example in case one is running a ArUco detector and ` `a large number of ArUco tags are present in the field of view of JeVois.`, 0, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (gui, bool, `Use a graphical user interface instead of plain display ` `when true`, true, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (conslock, bool, `Lock the console and capture the keyboard and mouse to avoid ` `interference, only effective on JeVois-Pro Platform, otherwise ignored. Set conslock ` `to false if you are experiencing hard crashes and want to run jevoispro-daemon in gdb.`, true, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER (watchdog, double, `Timeout in seconds after which we kill this process if the main loop ` `is stuck somehow, or 0.0 for no watchdog`, 10.0, ParamCateg)
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (demomode, float, `Show a demonstration of some available JeVois-Pro ` `machine vision modules, cycling to the next modules after a number ` `of seconds specified by this parameter (or 0.0 for no demo mode).`, 0.0F, ParamCateg)
Parameter.
Constructor & Destructor Documentation
Engine() [1/2]
jevois::Engine::Engine (std::string const & instance)
Constructor.
Definition at line 221 of file Engine.C.
References jevois::async_little(), and JEVOIS_TRACE.
Engine() [2/2]
jevois::Engine::Engine (int argc, char const * argv[], std::string const & instance)
Constructor with command-line parsing.
Definition at line 239 of file Engine.C.
References jevois::async_little(), and JEVOIS_TRACE.
 Engine()
jevois::Engine::~Engine ()
Destructor.
Definition at line 826 of file Engine.C.
References JEVOIS_TIMED_LOCK, JEVOIS_TRACE, jevois::logSetEngine(), and jevois::warnAndIgnoreException().
Member Function Documentation
abortDemo()
void jevois::Engine::abortDemo ()
处于演示模式时，中止演示模式
Definition at line 604 of file Engine.C.
camera()
std::shared_ptr< jevois::Camera > jevois::Engine::camera () const
获取指向我们相机的指针（可能为空，特别是当不使用相机而是使用电影输入时）
Definition at line 1455 of file Engine.C.
clearErrors()
void jevois::Engine::clearErrors ()
清除 JeVois-Pro GUI 中当前显示的所有错误
在 JevoisPro GUI 中，通过 reportError() 报告的错误会保留显示几秒钟，但有时我们希望立即清除它们，例如，在 DNN 管道抛 出后，如果用户选择另一个，我们希望之前的错误立即消失，因为它不再适用。当不使用 JeVois-Pro GUI 时，这没有效果。
Definition at line 1390 of file Engine.C.
drawCameraGUI()
void jevois::Engine::drawCameraGUI ()
将所有相机控件绘制到我们的 GUI 中
Definition at line 2842 of file Engine.C.
findVideoMapping()
const jevois::VideoMapping & jevois::Engine::findVideoMapping (unsigned int oformat, unsigned int owidth, unsigned int oheight, float oframespersec) const
查找具有给定输出规格的 VideoMapping，如果未找到则抛​​出
Definition at line 1575 of file Engine.C.
References jevois::fccstr(), LFATAL, and jevois::VideoMapping::match().
foreachVideoMapping()
void jevois::Engine::foreachVideoMapping (std::function< void(VideoMapping const &m)> && func)
在每个视频映射上运行一个函数
您的函数将被调用的第一个映射是索引为 0 的映射，依此类推，直到索引为 numVideoMappings()-1。如果您的函数抛出异常，我们会 报告异常然后忽略它，然后我们继续下一个映射。
Definition at line 1567 of file Engine.C.
References jevois::warnAndIgnoreException().
getCurrentVideoMapping()
const jevois::VideoMapping & jevois::Engine::getCurrentVideoMapping () const
获取当前视频映射
请注意，如果当前映射是通过 setmapping2 CLI 命令动态设置的，则当前映射可能没有在从 videomappings.cfg 获取的映射列表中的条目。
Definition at line 1511 of file Engine.C.
getDefaultVideoMapping()
const jevois::VideoMapping & jevois::Engine::getDefaultVideoMapping () const
Allow access to the default video mapping.
Definition at line 1559 of file Engine.C.
getDefaultVideoMappingIdx()
size_t jevois::Engine::getDefaultVideoMappingIdx () const
Allow access to the default video mapping index.
Definition at line 1563 of file Engine.C.
getPythonComponent()
jevois::Component * jevois::Engine::getPythonComponent (void * pyinst) const
获取使用给定 python 实例注册的组件
Definition at line 2998 of file Engine.C.
References LDEBUG, and LFATAL.
getVideoMapping()
const jevois::VideoMapping & jevois::Engine::getVideoMapping (size_t idx) const
允许访问我们在构建时从文件解析的视频映射
Definition at line 1519 of file Engine.C.
References LFATAL.
getVideoMappingIdx()
size_t jevois::Engine::getVideoMappingIdx (unsigned int iformat, unsigned int iframe, unsigned int interval) const
获取给定 UVC iformat、iframe 和 interval 的视频映射索引
Definition at line 1528 of file Engine.C.
References LFATAL, jevois::VideoMapping::ofps, jevois::VideoMapping::uvcformat, jevois::VideoMapping::uvcframe, and jevois::VideoMapping::uvcToFps().
loadCameraCalibration()
jevois::CameraCalibration jevois::Engine::loadCameraCalibration (std::string const & stem = `calibration`, bool do_throw = false)
为当前正在运行的模块加载 OpenCV 相机矩阵和失真系数的辅助函数
Definition at line 1459 of file Engine.C.
References jevois::CameraCalibration::h, h, JEVOIS_SHARE_PATH, jevois::CameraCalibration::lens, LFATAL, LINFO, jevois::CameraCalibration::load(), jevois::CameraCalibration::sensor, jevois::to_string(), and jevois::CameraCalibration::w.
mainLoop()
int jevois::Engine::mainLoop ()
主循环：抓取、处理、通过 USB 发送。应由主应用程序线程调用
Definition at line 1087 of file Engine.C.
References jevois::UserInterface::Hard, JEVOIS_TIMED_LOCK, JEVOIS_TRACE, JEVOIS_VERSION_STRING, JEVOISPRO_FMT_GUI, jevois::StdModule::sendSerialMarkStart(), jevois::StdModule::sendSerialMarkStop(), jevois::UserInterface::type(), jevois::warnAndIgnoreException(), and jevois::UserInterface::writeString().
module()
std::shared_ptr< jevois::Module > jevois::Engine::module () const
获取指向当前模块的指针（可能为空）
Definition at line 1447 of file Engine.C.
nextDemo()
void jevois::Engine::nextDemo ()
处于演示模式时，切换到下一个演示
Definition at line 600 of file Engine.C.
numVideoMappings()
size_t jevois::Engine::numVideoMappings () const
返回视频映射的数量
Definition at line 1515 of file Engine.C.
onParamChange() [1/9]
void jevois::Engine::onParamChange (engine::cpumax const & param, unsigned int const & newval) [override], [protected]
Parameter callback.
onParamChange() [2/9]
void jevois::Engine::onParamChange (engine::cpumaxl const & param, unsigned int const & newval) [override], [protected]
Parameter callback.
onParamChange() [3/9]
void jevois::Engine::onParamChange (engine::cpumode const & param, engine::CPUmode const & newval) [override], [protected]
Parameter callback.
onParamChange() [4/9]
void jevois::Engine::onParamChange (engine::cpumodel const & param, engine::CPUmode const & newval) [override], [protected]
Parameter callback.
onParamChange() [5/9]
void jevois::Engine::onParamChange (engine::demomode const & param, float const & newval) [override], [protected]
Parameter callback.
onParamChange() [6/9]
void jevois::Engine::onParamChange (engine::gui const & param, bool const & newval) [override], [protected]
Parameter callback.
onParamChange() [7/9]
void jevois::Engine::onParamChange (engine::serialdev const & param, std::string const & newval) [override], [protected]
Parameter callback.
onParamChange() [8/9]
void jevois::Engine::onParamChange (engine::usbserialdev const & param, std::string const & newval) [override], [protected]
Parameter callback.
onParamChange() [9/9]
void jevois::Engine::onParamChange (engine::videoerrors const & param, bool const & newval) [override], [protected]
Parameter callback.
parseCommand()
bool jevois::Engine::parseCommand (std::string const & str, std::shared_ptr< UserInterface > s, std::string const & pfx = ``) [protected]
解析通过串行端口接收到的用户命令
收到不正确的命令（例如，错误的参数值）时抛出，如果成功则返回 true，如果命令未被识别并且应由 Module 尝试，则返回 false。 pfx 是一个可选前缀，将添加到所有生成的消息或错误中。
Definition at line 1957 of file Engine.C.
References jevois::Serial::fileGet(), jevois::Serial::filePut(), jevois::getSysInfoCPU(), jevois::getSysInfoMem(), jevois::getSysInfoVersion(), JEVOIS_CUSTOM_DNN_PATH, JEVOIS_CUSTOM_DNN_URL, JEVOIS_USBSD_SYS, JEVOIS_VERSION_STRING, JEVOISPRO_FMT_GUI, LDEBUG, jevois::split(), jevois::system(), jevois::to_string(), and jevois::UserInterface::writeString().
postInit()
void jevois::Engine::postInit () [override], [protected], [virtual]
Override of Manager::postInit()
Reimplemented from jevois::Manager.
Definition at line 641 of file Engine.C.
References jevois::Component::freezeAllParams(), jevois::getFileString(), JEVOIS_ENGINE_INIT_SCRIPT, JEVOIS_TIMED_LOCK, LERROR, LINFO, jevois::logSetEngine(), jevois::Manager::postInit(), jevois::sensorHasIMU(), jevois::python::setEngine(), jevois::stringStartsWith(), and jevois::warnAndIgnoreException().
preInit()
void jevois::Engine::preInit () [override], [protected], [virtual]
Override of Manager::preInit()
Reimplemented from jevois::Manager.
Definition at line 617 of file Engine.C.
References JEVOIS_CONFIG_PATH, JEVOIS_MODULE_PARAMS_FILENAME, and jevois::Manager::preInit().
quit()
void jevois::Engine::quit ()
Terminate the program.
Definition at line 1855 of file Engine.C.
reboot()
void jevois::Engine::reboot ()
请求重启
在 JeVois-A33 平台上，触发硬重置。在 JeVois-Pro 平台或 JeVois-Host 上，只需终止程序即可。
Definition at line 1834 of file Engine.C.
References LERROR, and jevois::system().
registerPythonComponent()
void jevois::Engine::registerPythonComponent (jevois::Component * comp, void * pyinst)
将组件注册为链接到某些 python 代码，由在 python 中创建的动态参数使用
Definition at line 2979 of file Engine.C.
References jevois::Component::instanceName(), LDEBUG, and LFATAL.
reloadVideoMappings()
void jevois::Engine::reloadVideoMappings ()
从 videomappings.cfg 重新加载视频映射。
Mappings 会在启动时自动加载，因此仅当文件发生修改并且需要刷新映射时才应使用此方法。请注意，这不会刷新 USB 输出的可用分辨率， 这需要完全重启才能重新初始化内核 Gadget 模块。还要注意可能的状态不一致（例如，如果外部代码持有先前由 findVideoMapping() 返回的引用。因此，请谨慎使用。基本上，应该只有 GUIhelper 使用它。
Definition at line 628 of file Engine.C.
References LINFO.
reportError()
void jevois::Engine::reportError (std::string const & err)
Definition at line 1381 of file Engine.C.
References LERROR.
requestSetFormat()
void jevois::Engine::requestSetFormat (int idx)
使用它从 process() 中请求格式更改
Definition at line 927 of file Engine.C.
References JEVOIS_TRACE.
runScriptFromFile()
void jevois::Engine::runScriptFromFile (std::string const & filename, std::shared_ptr< UserInterface > ser, bool throw_no_file) [protected]
从文件运行脚本
文件名应该是绝对的。文件应该包含 Engine 支持的任何命令，每行一个。文件名应该相对于当前模块的路径。
Definition at line 2764 of file Engine.C.
References jevois::UserInterface::GUI, jevois::UserInterface::Hard, LFATAL, jevois::strip(), jevois::to_string(), jevois::UserInterface::type(), jevois::UserInterface::USB, jevois::warnAndIgnoreException(), and jevois::UserInterface::writeString().
saveCameraCalibration()
void jevois::Engine::saveCameraCalibration (jevois::CameraCalibration const & calib, std::string const & stem = `calibration`)
保存当前正在运行的模块的 OpenCV 相机矩阵和失真系数的辅助函数
注意：为了线程安全，应锁定引擎；在 Module::process() 内部调用它是安全的。
Definition at line 1497 of file Engine.C.
References jevois::CameraCalibration::h, JEVOIS_SHARE_PATH, jevois::CameraCalibration::lens, LINFO, jevois::CameraCalibration::save(), jevois::CameraCalibration::sensor, jevois::to_string(), and jevois::CameraCalibration::w.
sendSerial()
void jevois::Engine::sendSerial (std::string const & str, bool islog = false)
向所有串行端口发送一个字符串
Note
当 islog 为真时，这被认为是一条日志消息，它将被发送到参数 serlog 指定的端口。否则，该消息将被发送到参数 serout 指 定的端口。请注意，每个视频帧可以发送的消息数量可能受参数 serlimit 的限制；对于给定的视频帧，最多只能发送 serlimit 条消息。这对于避免串行链路过载很有用，例如在运行 ArUco 检测器并且 JeVois 的视野中存在大量 ArUco 标签的情况下。
Definition at line 1336 of file Engine.C.
References jevois::UserInterface::GUI, jevois::UserInterface::Hard, jevois::UserInterface::type(), jevois::UserInterface::USB, jevois::warnAndIgnoreException(), and jevois::UserInterface::writeString().
Referenced by jevois::Module::sendSerial().
setFormat()
void jevois::Engine::setFormat (size_t idx)
当用户选择新的输出视频格式时的回调
在这里，我们停止流式传输，删除任何当前处理模块，设置相机格式，设置小工具输出格式，加载新的处理模块，然后再次开始流式传 输。通常使用 findVideoMapping() 从通过 USB 链接接收的输出规范中获取给定的 VideoMapping。
Definition at line 934 of file Engine.C.
References JEVOIS_TIMED_LOCK, JEVOIS_TRACE, LDEBUG, and LFATAL.
streamOff()
void jevois::Engine::streamOff ()
停止从相机、处理和 USB 流式传输视频
Definition at line 906 of file Engine.C.
References JEVOIS_TIMED_LOCK, JEVOIS_TRACE, and LDEBUG.
streamOn()
void jevois::Engine::streamOn ()
开始从相机、处理和 USB 流式传输视频
Definition at line 895 of file Engine.C.
References JEVOIS_TIMED_LOCK, and JEVOIS_TRACE.
unRegisterPythonComponent()
void jevois::Engine::unRegisterPythonComponent (Component * comp)
取消注册与某些 Python 代码链接的组件，由 Python 中创建的动态参数使用
请谨慎使用，以保证线程安全和对象生命周期，因为我们在这里只使用原始指针
Definition at line 2989 of file Engine.C.
References jevois::Component::instanceName(), and LDEBUG.
Friends And Related Function Documentation
frameNum()
size_t frameNum () [related]
获取当前视频处理帧号
Engine 维护一个主帧计数器，该计数器在每次调用模块的 process() 时都会递增，无论调用是否成功。当模块尚未加载（例如加载失 败）时，计数器不会递增。每次加载新模块时，计数器都会重置为零。
这是作为一项自由函数实现的，以便任何人都可以访问它：
size_t current_frame_number = jevois::frameNum();
它是线程安全的。程序员注意：实现在 Engine.C 中，因为 Engine 是管理计数器的那个。它在这里声明，以便用户不必包含 Engine.H
JEVOIS_DECLARE_PARAMETER() [1/19]
JEVOIS_DECLARE_PARAMETER (cameradev , std::string , `Camera device name if starting with /dev/v..., or movie ` `file name(e.g., movie.mpg) or image sequence(e.g., im%02d.jpg, to read frames ` `im00.jpg, im01.jpg, etc).` , JEVOIS_CAMERA_DEFAULT , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [2/19]
JEVOIS_DECLARE_PARAMETER (cameralens , CameraLens , `Camera lens. Users should usually not set this parameter ` `using the global JeVois params.cfg config file.` , CameraLens::standard , CameraLens_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [3/19]
JEVOIS_DECLARE_PARAMETER (cameranbuf , unsigned int , `Number of video input (camera) buffers, or 0 for automatic.` , 0 , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [4/19]
JEVOIS_DECLARE_PARAMETER (camerasens , CameraSensor , `Camera sensor. Users would usually not set this parameter ` ` manually, it is set through boot-time configuration.` , JEVOIS_CAMERASENS_DEFAULT , CameraSensor_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [5/19]
JEVOIS_DECLARE_PARAMETER (camreg , bool , `Enable raw access to camera registers through setcamreg and getcamreg` , false , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [6/19]
JEVOIS_DECLARE_PARAMETER (camturbo , bool , `Enable camera turbo mode by relaxing the need for DMA-coherent video ` `buffer memory. This can accelerate severalfolds access to the captured image data, but ` `it may also yield stripe artifacts with some modules, such as PassThrough. The stripes ` `are pieces of incorrect data in the cache. You should experiment with each particular ` `module. Turbo mode is not recommended for any production-grade application.` , false , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [7/19]
JEVOIS_DECLARE_PARAMETER (conslock , bool , `Lock the console and capture the keyboard and mouse to avoid ` ` interference, only effective on JeVois-Pro Platform, otherwise ignored. Set conslock ` `to false if you are experiencing hard crashes and want to run jevoispro-daemon in gdb.` , true , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [8/19]
JEVOIS_DECLARE_PARAMETER (gadgetdev , std::string , `Gadget device name. This is used on platform hardware only. ` `On host hardware, a display window will be used unless gadgetdev is None(useful ` `for benchmarking) or is a file stem for a movie file that does not start with/dev/` `(and which should contain a printf-style directive for a single int argument, ` `the movie number).` , JEVOIS_GADGET_DEFAULT , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [9/19]
JEVOIS_DECLARE_PARAMETER (gadgetnbuf , unsigned int , `Number of video output (USB video) buffers, or 0 for auto` , 0 , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [10/19]
JEVOIS_DECLARE_PARAMETER (imureg , bool , `Enable raw access to IMU registers through setimureg and getimureg` , false , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [11/19]
JEVOIS_DECLARE_PARAMETER (multicam , bool , `Allow up to 3 JeVois cameras on one USB bus. Enabling this ` `reduces the amount of USB bandwidth used by each JeVois camera, from 3kb ` `per USB isochronous microframe to 1kb. All 3 JeVois cameras must have this ` `option enabled, and the JeVois linux kernel module should also have ` `been loaded with multicam on.` , false , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [12/19]
JEVOIS_DECLARE_PARAMETER (python , bool , `When true, enable support for modules written in Python. Otherwise, ` `attempting to load a python module will throw an exception. Disabling python saves ` `a lot of memory and may be useful when using C++modules that run large deep neural ` `networks.` , true , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [13/19]
JEVOIS_DECLARE_PARAMETER (quietcmd , bool , `When true, do not issue a message 'OK' after every correct command ` `received at the command-line interface. Recommended for advanced users only.` , false , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [14/19]
JEVOIS_DECLARE_PARAMETER (serialmonitors , bool , `If true, serial port monitors will be enabled ` `in the GUI, which can be used to peek at serial communications not ` `directed to the console. Can be turned off at start time(e.g., in the ` `global JeVois params.cfg) as there is some small CPU cost to it.` , true , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [15/19]
JEVOIS_DECLARE_PARAMETER (serlimit , size_t , `Maximum number of serial messages that can be sent by a module ` `using sendSerial(), for each video frame, or 0 for no limit. Any message sent by ` `the module beyond the first serlimit ones will be dropped. This is useful to avoid ` `overloading the serial link, for example in case one is running a ArUco detector and ` `a large number of ArUco tags are present in the field of view of JeVois.` , 0 , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [16/19]
JEVOIS_DECLARE_PARAMETER (serlog , SerPort , `Show log and debug messages on selected serial port(s)` , SerPort::None , SerPort_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [17/19]
JEVOIS_DECLARE_PARAMETER (serout , SerPort , `Send module serial messages to selected serial port(s)` , SerPort::None , SerPort_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [18/19]
JEVOIS_DECLARE_PARAMETER (videomapping , int , `Index of Video Mapping to use, or -1 to use the default mapping. ` `Note that this parameter is only available when parsing command-line arguments. ` `At runtime, the setmapping command should be used instead.` , - 1, ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER() [19/19]
JEVOIS_DECLARE_PARAMETER (watchdog , double , `Timeout in seconds after which we kill this process if the main loop ` `is stuck somehow, or 0.0 for no watchdog` , 10. 0, ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [1/9]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (cpumax , unsigned int , `CPU maximum frequency in MHz` `. To enable overclock frequencies above 2208 MHz, you need to first edit ` `/boot/env.txt and change max_freq_a73, then reboot. Use with caution!` , 2208 , { 500, 667, 1000, 1200, 1398, 1512, 1608, 1704, 1800, 1908, 2016, 2100, 2208, 2304, 2400 } , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [2/9]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (cpumaxl , unsigned int , `CPU maximum frequency in MHz, for A53 little cores. ` `To enable overclock frequencies above 1800 MHz, you need to first edit ` `/boot/env.txt and change max_freq_a53, then reboot. Use with caution!` , 1800 , { 500, 667, 1000, 1200, 1398, 1512, 1608, 1704, 1800, 1908, 2016, 2100, 2208 } , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [3/9]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (cpumode , CPUmode , `CPU frequency modulation mode` ` for A73 big cores` , CPUmode::Performance , CPUmode_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [4/9]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (cpumodel , CPUmode , `CPU frequency modulation mode for A53 little cores` , CPUmode::Performance , CPUmode_Values , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [5/9]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (demomode , float , `Show a demonstration of some available JeVois-Pro ` `machine vision modules, cycling to the next modules after a number ` `of seconds specified by this parameter(or 0.0 for no demo mode).` , 0. 0F, ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [6/9]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (gui , bool , `Use a graphical user interface instead of plain display ` `when true` , true , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [7/9]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (serialdev , std::string , `Hardware (4-pin connector) serial device name, ` `or 'stdio' to use the console, or empty for no hardware serial port` , JEVOIS_SERIAL_DEFAULT , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [8/9]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (usbserialdev , std::string , `Over-the-USB serial device name, or empty` , JEVOIS_USBSERIAL_DEFAULT , ParamCateg) [related]
Parameter.
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK() [9/9]
JEVOIS_DECLARE_PARAMETER_WITH_CALLBACK (videoerrors , bool , `Show any machine vision module errors (exceptions) ` `in the video stream. Only takes effect if streaming video to USB.` , true , ParamCateg) [related]
Parameter.
JEVOIS_DEFINE_ENUM_CLASS() [1/2]
JEVOIS_DEFINE_ENUM_CLASS (CPUmode , (PowerSave)(Conservative)(OnDemand)(Interactive)(Performance)) [related]
Enum for Parameter.
JEVOIS_DEFINE_ENUM_CLASS() [2/2]
JEVOIS_DEFINE_ENUM_CLASS (SerPort , (None)(All)(Hard)(USB)) [related]
Enum for Parameter.
Member Data Documentation
itsCamera
std::shared_ptr<VideoInput> jevois::Engine::itsCamera [protected]
Our camera.
Definition at line 560 of file Engine.H.
itsCurrentMapping
VideoMapping jevois::Engine::itsCurrentMapping [protected]
当前映射，如果使用 setmapping2，则可能与 itsMappings 中的任何映射都不匹配
Definition at line 558 of file Engine.H.
itsDefaultMappingIdx
size_t jevois::Engine::itsDefaultMappingIdx [protected]
Index of default mapping.
Definition at line 556 of file Engine.H.
itsGadget
std::shared_ptr<VideoOutput> jevois::Engine::itsGadget [protected]
Our IMU.
Our gadget
Definition at line 562 of file Engine.H.
itsIMU
std::shared_ptr<IMU> jevois::Engine::itsIMU [protected]
Definition at line 561 of file Engine.H.
itsLoader
std::unique_ptr<DynamicLoader> jevois::Engine::itsLoader [protected]
Our module loader.
Definition at line 564 of file Engine.H.
itsMappings
std::vector<VideoMapping> jevois::Engine::itsMappings [protected]
来自 videomappings.cfg 的所有映射
Definition at line 557 of file Engine.H.
itsModule
std::shared_ptr<Module> jevois::Engine::itsModule [protected]
Our current module.
Definition at line 565 of file Engine.H.
itsMtx
std::timed_mutex jevois::Engine::itsMtx [mutable], [protected]
Mutex to protect our internals.
Definition at line 571 of file Engine.H.
itsRunning
std::atomic<bool> jevois::Engine::itsRunning [protected]
True when we are running.
Definition at line 567 of file Engine.H.
itsStopMainLoop
std::atomic<bool> jevois::Engine::itsStopMainLoop [protected]
Flag used to stop the main loop.
Definition at line 569 of file Engine.H.
itsStreaming
std::atomic<bool> jevois::Engine::itsStreaming [protected]
True when we are streaming video.
Definition at line 568 of file Engine.H.
The documentation for this class was generated from the following files:
include/jevois/Core/Engine.H
include/jevois/Component/Component.H
src/jevois/Core/Engine.C