Jpeg 相关的类和函数
Jpeg 类和函数，主要用于支持从相机捕获的原始未压缩图像通过 USB 发送 MJPEG 视频输出。
Classes
class jevois::JpegCompressor
turbojpeg 压缩器的简单单例包装器
Functions
void jevois::convertYUYVtoYUV422 (unsigned char const *src, int width, int height, unsigned char *dst)
辅助从打包的 YUYV 转换为平面 YUV422
unsigned long jevois::compressBGRtoJpeg (unsigned char const *src, int width, int height, unsigned char *dst, int quality=75)
将原始像素缓冲区压缩为 jpeg
void jevois::compressBGRtoJpeg (cv::Mat const &src, RawImage &dst, int quality=75)
将 BGR cv::Mat 压缩为输出 JPEG jevois::RawImage
unsigned long jevois::compressRGBtoJpeg (unsigned char const *src, int width, int height, unsigned char *dst, int quality=75)
将原始像素缓冲区压缩为 jpeg
void jevois::compressRGBtoJpeg (cv::Mat const &src, RawImage &dst, int quality=75)
将 RGB cv::Mat 压缩为输出 JPEG jevois::RawImage
unsigned long jevois::compressRGBAtoJpeg (unsigned char const *src, int width, int height, unsigned char *dst, int quality=75)
将原始像素缓冲区压缩为 jpeg
void jevois::compressRGBAtoJpeg (cv::Mat const &src, RawImage &dst, int quality=75)
将 RGBA cv::Mat 压缩为输出 JPEG jevois::RawImage
unsigned long jevois::compressGRAYtoJpeg (unsigned char const *src, int width, int height, unsigned char *dst, int quality=75)
将原始像素缓冲区压缩为 jpeg
void jevois::compressGRAYtoJpeg (cv::Mat const &src, RawImage &dst, int quality=75)
将 Gray cv::Mat 压缩为输出 JPEG jevois::RawImage
Function Documentation
compressBGRtoJpeg() [1/2]
void jevois::compressBGRtoJpeg (cv::Mat const & src, RawImage & dst, int quality = 75)
将 BGR cv::Mat 压缩为输出 JPEG jevois::RawImage
dst RawImage 应该有一个分配的缓冲区，通常用于从 UVC gadget 获取的 RawImage。
Definition at line 108 of file Jpeg.C.
References jevois::RawImage::buf, jevois::compressBGRtoJpeg(), and jevois::RawImage::pixelsw().
compressBGRtoJpeg() [2/2]
unsigned long jevois::compressBGRtoJpeg (unsigned char const * src, int width, int height, unsigned char * dst, int quality = 75)
将原始像素缓冲区压缩为 jpeg
Definition at line 52 of file Jpeg.C.
References jevois::JpegCompressor::compressor(), and jevois::Singleton< JpegCompressor >::instance().
Referenced by jevois::compressBGRtoJpeg(), and jevois::rawimage::convertCvBGRtoRawImage().
compressGRAYtoJpeg() [1/2]
void jevois::compressGRAYtoJpeg (cv::Mat const & src, RawImage & dst, int quality = 75)
将 Gray cv::Mat 压缩为输出 JPEG jevois::RawImage
Definition at line 126 of file Jpeg.C.
References jevois::RawImage::buf, jevois::compressGRAYtoJpeg(), and jevois::RawImage::pixelsw().
compressGRAYtoJpeg() [2/2]
unsigned long jevois::compressGRAYtoJpeg (unsigned char const * src, int width, int height, unsigned char * dst, int quality = 75)
将原始像素缓冲区压缩为 jpeg
Definition at line 94 of file Jpeg.C.
References jevois::JpegCompressor::compressor(), and jevois::Singleton< JpegCompressor >::instance().
Referenced by jevois::compressGRAYtoJpeg(), and jevois::rawimage::convertCvGRAYtoRawImage().
compressRGBAtoJpeg() [1/2]
void jevois::compressRGBAtoJpeg (cv::Mat const & src, RawImage & dst, int quality = 75)
将 RGBA cv::Mat 压缩为输出 JPEG jevois::RawImage
dst RawImage 应该有一个分配的缓冲区，通常用于从 UVC gadget 获取的 RawImage。
Definition at line 120 of file Jpeg.C.
References jevois::RawImage::buf, jevois::compressRGBAtoJpeg(), and jevois::RawImage::pixelsw().
compressRGBAtoJpeg() [2/2]
unsigned long jevois::compressRGBAtoJpeg (unsigned char const * src, int width, int height, unsigned char * dst, int quality = 75)
将原始像素缓冲区压缩为 jpeg
返回压缩后的大小。dst 缓冲区应该由调用者分配，大小至少为 width * height * 2 个字节。质量应该介于 1（最差）和 100（最好） 之间。
Definition at line 80 of file Jpeg.C.
References jevois::JpegCompressor::compressor(), and jevois::Singleton< JpegCompressor >::instance().
Referenced by jevois::compressRGBAtoJpeg(), and jevois::rawimage::convertCvRGBAtoRawImage().
compressRGBtoJpeg() [1/2]
void jevois::compressRGBtoJpeg (cv::Mat const & src, RawImage & dst, int quality = 75)
将 RGB cv::Mat 压缩为输出 JPEG jevois::RawImage
dst RawImage 应该有一个分配的缓冲区，通常用于从 UVC gadget 获取的 RawImage。
Definition at line 114 of file Jpeg.C.
References jevois::RawImage::buf, jevois::compressRGBtoJpeg(), and jevois::RawImage::pixelsw().
compressRGBtoJpeg() [2/2]
unsigned long jevois::compressRGBtoJpeg (unsigned char const * src, int width, int height, unsigned char * dst, int quality = 75)
将原始像素缓冲区压缩为 jpeg
返回压缩后的大小。dst 缓冲区应该由调用者分配，大小至少为 width * height * 2 个字节。质量应介于 1（最差）和 100（最好） 之间。
Definition at line 66 of file Jpeg.C.
References jevois::JpegCompressor::compressor(), and jevois::Singleton< JpegCompressor >::instance().
Referenced by jevois::compressRGBtoJpeg(), and jevois::rawimage::convertCvRGBtoRawImage().
convertYUYVtoYUV422()
void jevois::convertYUYVtoYUV422 (unsigned char const * src, int width, int height, unsigned char * dst)
辅助从打包的 YUYV 转换为平面 YUV422
Definition at line 35 of file Jpeg.C.