Misc utilities
各种实用程序和辅助函数。
Classes
class jevois::ThreadPool
具有 CPU 亲和力的线程池
Modules
其他与控制编译相关的预处理器实用程序
控制台访问实用程序
控制台相关的实用程序和帮助函数。
用于将坐标从相机分辨率转换为标准坐标的辅助函数
JeVois 中的不同机器视觉算法可能以不同的相机分辨率运行，例如 1280x1024、320x240 或 176x144。当在相机帧中检测到某些感兴 趣的物品时，人们通常希望将该物品的坐标发送到串行端口。如果直接发送物品的图像坐标，就会出现问题，即现在接收器（例如 Arduino）需要知道使用了哪种相机图像分辨率，以便能够正确解释这些坐标。例如，如果视觉注意（显著性）算法使用 640x480 相 机输入运行，则相机视野中心的显著物体的坐标为 320,240。但如果将相同的显著性算法配置为处理 320x240 输入视频（以便它可以 以更高的帧速率运行），现在视野中心的物体的坐标为 160,120。如果将控制例如云台的 Arduino 连接到 JeVois，我们需要一种方法 来独立于相机使用的视频分辨率传达世界上目标物体的坐标。
Name demangling 函数
Name demangling 函数返回源代码中所写的类型的原始名称，而不是编译器内部使用的名称，该名称被解析以避免跨不同命名空 间、重载等的名称冲突和混淆。
Macros
#define XIOCTL(dev, req, mem)
辅助宏用于执行 ioctl、忽略中断，如果发生错误，则发出致命消息并抛出
#define XIOCTL_QUIET(dev, req, mem)
辅助宏用于执行 ioctl、忽略中断，并且如果出现错误则静默抛出
#define XIOCTL_QUIET_ONCE(dev, req, mem)
辅助宏用于执行 ioctl、忽略中断，并且如果出现错误则静默抛出
Functions
template<typename T >
std::vector< T > jevois::joinall (std::vector< std::future< T >> &fvec, bool multiline=true)
从多个异步线程收集结果，这些线程都返回 T 结果
void jevois::joinall (std::vector< std::future< void >> &fvec, bool multiline=true)
从多个异步线程收集结果，这些线程都返回 T 结果
std::string jevois::fccstr (unsigned int fcc)
将 V4L2 four-cc 代码（V4L2_PIX_FMT_...）转换为 4 字符字符串
std::string jevois::cvtypestr (unsigned int cvtype)
将 cv::Mat::type() 代码转换为字符串（例如 CV_8UC1、CV_32SC3 等）
unsigned int jevois::cvBytesPerPix (unsigned int cvtype)
返回给定 OpenCV 像素类型每像素的字节数
unsigned int jevois::strfcc (std::string const &str)
将 JeVois 视频格式字符串转换为 V4L2 four-cc 代码 (V4L2_PIX_FMT_...)
unsigned int jevois::v4l2BytesPerPix (unsigned int fcc)
返回给定 V4L2_PIX_FMT_ 每像素的字节数...
unsigned int jevois::v4l2ImageSize (unsigned int fcc, unsigned int width, unsigned int height)
返回给定 V4L2_PIX_FMT_... 的图像大小（以字节为单位）, width, height
unsigned int jevois::blackColor (unsigned int fcc)
返回对应于给定视频格式的黑色的值
unsigned int jevois::whiteColor (unsigned int fcc)
返回对应于给定视频格式的白色的值
void jevois::applyLetterBox (unsigned int &imw, unsigned int &imh, unsigned int const winw, unsigned int const winh, bool noalias)
应用 letterbox 调整大小以使图像适合窗口
std::vector< std::string > jevois::split (std::string const &input, std::string const &regex=`\\s+`)
使用正则表达式将字符串拆分为 tokens 向量以指定要拆分的内容；默认正则表达式按空格拆分
std::string jevois::join (std::vector< std::string > const &strings, std::string const &delimiter)
将 tokens 向量连接成字符串
bool jevois::stringStartsWith (std::string const &str, std::string const &prefix)
如果 str 以 prefix 开头，则返回 true（包括两个字符串相等的情况）
std::string jevois::replaceWhitespace (std::string const &str, char rep='_')
用下划线（默认）或其他字符替换字符串中的空格字符
std::string jevois::strip (std::string const &str)
从字符串末尾去除空格（包括 CR、LF、tabs 等）
std::string jevois::extractString (std::string const &str, std::string const &startsep, std::string const &endsep)
提取两个分隔符之间的字符串部分
size_t jevois::replaceStringFirst (std::string &str, std::string const &from, std::string const &to)
将 'from' 的第一个实例替换为 'to'
size_t jevois::replaceStringAll (std::string &str, std::string const &from, std::string const &to)
将所有 'from' 实例替换为 'to'
std::string jevois::replaceAll (std::string const &str, std::string const &from, std::string const &to)
将所有 'from' 实例替换为 'to'
std::string jevois::tolower (std::string const &str)
Convert string to lowercase.
std::filesystem::path jevois::absolutePath (std::filesystem::path const &root, std::filesystem::path const &path)
根据两个路径计算绝对路径
std::string jevois::sformat (char const *fmt,...) __attribute__((format(__printf__
使用 printf 样式参数创建字符串
template<typename T >
std::string T jevois::from_string (std::string const &str)
从字符串转换为类型
template<typename T >
std::string jevois::to_string (T const &val)
从字符串转换为类型，适用于整数类型的版本
template<typename dest_type , typename source_type >
dest_type jevois::clamped_convert (source_type source)
Clamped numerical conversion.
void jevois::flushcache ()
刷新缓存，有时在 turbo 模式下运行相机时可能会有用
std::string jevois::system (std::string const &cmd, bool errtoo=true)
执行命令并将 stdout 输出抓取到字符串
std::string jevois::secs2str (double secs)
报告以秒为单位的持续时间，单位可变（ns、us、ms 或 s），精度为小数点后 2 位
std::string jevois::secs2str (std::vector< double > secs)
报告以秒为单位给出的 avg+/-std 持续时间，单位为变量（ns、us、ms 或 s），带有 1 个小数点
void jevois::secs2str (std::ostringstream &ss, double secs)
报告以秒为单位的持续时间（ns、us、ms 或 s）
std::string jevois::num2str (double n)
报告一个具有可变乘数（K、M、G、T、P、E、Z、Y）的数字，精度为小数点后 2 位
void jevois::num2str (std::ostringstream &ss, double n)
报告具有可变乘数 (K、M、G、T、P、E、Z、Y) 的数字
std::string jevois::getFileString (char const *fname, int skip=0)
从文件中读取一行并将其作为字符串返回
Macro Definition Documentation
XIOCTL
#define XIOCTL(dev, req, mem)
辅助宏用于执行 ioctl、忽略中断，如果发生错误，则发出致命消息并抛出
该宏假定 req 是相应 ioctl 编号的标识符 (#define)
Definition at line 198 of file Utils.H.
XIOCTL_QUIET
#define XIOCTL_QUIET(dev, req, mem)
辅助宏用于执行 ioctl、忽略中断，并且如果出现错误则静默抛出
这很有用，例如，对于 V4L2 相机格式枚举，其中应该使用增加的格式号调用 ioctl，直到失败。当发生这种情况时，我们 不想像 XIOCTL() 那样显示任何致命错误消息。此宏假定 req 是相应 ioctl 编号的标识符。
Definition at line 208 of file Utils.H.
XIOCTL_QUIET_ONCE
#define XIOCTL_QUIET_ONCE(dev, req, mem)
辅助宏用于执行 ioctl、忽略中断，并且如果出现错误则静默抛出
这很有用，例如，对于 V4L2 相机格式枚举，其中应该使用增加的格式号调用 ioctl，直到失败。当发生这种情况时，我们 不想像 XIOCTL() 那样显示任何致命错误消息。此宏假定 req 是相应 ioctl 编号的标识符。请注意，在此版本中，我们 会抛出任何错误。
Definition at line 219 of file Utils.H.
Function Documentation
absolutePath()
std::filesystem::path jevois::absolutePath (std::filesystem::path const & root, std::filesystem::path const & path)
根据两个路径计算绝对路径
参数 path 包含可以是绝对路径也可以是相对路径；参数 root 应包含根路径。如果 path 是绝对路径，则返回该路径；否则， 将 root 添加到其前面并返回结果。
Definition at line 385 of file Utils.C.
Referenced by jevois::Component::absolutePath(), jevois::dnn::NetworkOpenCV::load(), jevois::dnn::NetworkTPU::load(), jevois::dnn::NetworkONNX::load(), jevois::dnn::NetworkHailo::load(), jevois::dnn::NetworkNPU::load(), jevois::dnn::Pipeline::onParamChange(), jevois::dnn::Pipeline::process(), and jevois::Component::setParamsFromFile().
applyLetterBox()
void jevois::applyLetterBox (unsigned int & imw, unsigned int & imh, unsigned int const winw, unsigned int const winh, bool noalias)
应用 letterbox 调整大小以使图像适合窗口
修改给定的图像尺寸（imw，imh），以使图像适合窗口尺寸（winw，winh），同时尽可能大，但不修改图像的纵横比。如果指定了 noalias，则缩放因子将向下舍入到最接近的整数以防止显示混叠。这可能会减小显示的图像大小。例如，对于 1920x1080 的窗口，当 noalias 为 false 时，640x480 的图像将被 leterbox 化为 1440x1080。但这是 2.25 的比例因子，可能会产生渲染混叠。当 noalias 为 true 时，leterbox 图像大小将为 1280x960（比例因子为 2.0）。
Definition at line 222 of file Utils.C.
References LFATAL.
Referenced by jevois::GPUimage::draw(), and jevois::dnn::PreProcessorBlob::process().
blackColor()
unsigned int jevois::blackColor (unsigned int fcc)
返回对应于给定视频格式的黑色的值
Definition at line 172 of file Utils.C.
References jevois::fccstr(), JEVOISPRO_FMT_GUI, and LFATAL.
clamped_convert()
template<typename dest_type , typename source_type >
dest_type jevois::clamped_convert (source_type source)
Clamped numerical conversion.
cvBytesPerPix()
unsigned int jevois::cvBytesPerPix (unsigned int cvtype)
返回给定 OpenCV 像素类型每像素的字节数
Definition at line 89 of file Utils.C.
References LFATAL.
Referenced by jevois::dnn::concatenate(), jevois::dnn::NetworkTPU::doprocess(), and jevois::dnn::NetworkONNX::doprocess().
cvtypestr()
std::string jevois::cvtypestr (unsigned int cvtype)
将 cv::Mat::type() 代码转换为字符串（例如 CV_8UC1、CV_32SC3 等）
Definition at line 58 of file Utils.C.
References jevois::to_string().
Referenced by jevois::dnn::concatenate(), jevois::rawimage::convertCvBGRtoCvYUYV(), jevois::rawimage::convertCvBGRtoRawImage(), jevois::rawimage::convertCvGRAYtoCvYUYV(), jevois::rawimage::convertCvGRAYtoRawImage(), jevois::rawimage::convertCvRGBAtoCvYUYV(), jevois::rawimage::convertCvRGBAtoRawImage(), jevois::rawimage::convertCvRGBtoCvYUYV(), jevois::rawimage::convertCvRGBtoRawImage(), jevois::dnn::NetworkONNX::doprocess(), jevois::rawimage::pasteBGRtoYUYV(), jevois::rawimage::pasteRGBtoYUYV(), jevois::dnn::PreProcessorBlob::process(), jevois::OutputFrame::sendCv(), jevois::dnn::shapestr(), and jevois::rawimage::unpackCvRGBAtoGrayRawImage().
extractString()
std::string jevois::extractString (std::string const & str, std::string const & startsep, std::string const & endsep)
提取两个分隔符之间的字符串部分
如果未找到分隔符，则返回空字符串。
Definition at line 316 of file Utils.C.
fccstr()
std::string jevois::fccstr (unsigned int fcc)
将 V4L2 four-cc 代码（V4L2_PIX_FMT_...）转换为 4 字符字符串
Definition at line 45 of file Utils.C.
Referenced by jevois::blackColor(), jevois::VideoMapping::c2str(), jevois::CameraDevice::CameraDevice(), jevois::RawImage::clear(), jevois::rawimage::convertCvBGRtoRawImage(), jevois::rawimage::convertCvGRAYtoRawImage(), jevois::rawimage::convertCvRGBAtoRawImage(), jevois::rawimage::convertCvRGBtoRawImage(), jevois::VideoMapping::cstr(), jevois::Engine::findVideoMapping(), jevois::GPUtextureDmaBuf::GPUtextureDmaBuf(), jevois::GUIhelper::iinfo(), jevois::VideoMapping::ostr(), jevois::RawImage::require(), jevois::dnn::PreProcessor::sendreport(), jevois::CameraDevice::setFormat(), jevois::Gadget::setFormat(), jevois::GPUimage::setInternal(), jevois::GPUimage::setWithDmaBuf(), jevois::v4l2BytesPerPix(), and jevois::whiteColor().
flushcache()
void jevois::flushcache ()
刷新缓存，有时在 turbo 模式下运行相机时可能会有用
Definition at line 449 of file Utils.C.
References LERROR.
from_string()
template<typename T >
std::string T jevois::from_string (std::string const & str)
从字符串转换为类型
对于整数类型，内部使用 std::stoll() 作为该类型，它支持前缀 0（八进制）和 0x（十六进制）。请注意八进制约定，除非您有意，否 则不要传递前导零。对于非整数类型，内部使用 operator>> 作为该类型，因此它适用于任何支持它的类型。
getFileString()
std::string jevois::getFileString (char const * fname, int skip = 0)
从文件中读取一行并将其作为字符串返回
有助于从虚拟内核文件系统获取信息，例如 CPU 温度等。参数 skip 可选地指定在返回感兴趣的行之前要跳过的行数。
Definition at line 541 of file Utils.C.
Referenced by jevois::dnn::NetworkTPU::doprocess(), jevois::GUIhelper::drawSystem(), jevois::getFanSpeed(), jevois::getNumInstalledSPUs(), jevois::getNumInstalledTPUs(), jevois::getSysInfoCPU(), jevois::getSysInfoMem(), jevois::getSysInfoVersion(), jevois::GUIhelper::GUIhelper(), and jevois::Engine::postInit().
join()
std::string jevois::join (std::vector< std::string > const & strings, std::string const & delimiter)
将 tokens 向量连接成字符串
Definition at line 280 of file Utils.C.
Referenced by jevois::dnn::Pipeline::process().
joinall() [1/2]
template<typename T >
std::vector<T> jevois::joinall (std::vector< std::future< T >> & fvec, bool multiline = true)
从多个异步线程收集结果，这些线程都返回 T 结果
保证 get() 将在所有 futures 上运行。如果抛出任何错误，则收集所有错误消息（如果可能，例如，抛出了 std::exception）并将它们 组装成单个字符串，形式为 `[error 1][error 2] ...` 或 `error 1\nerror 2\n...`，然后将其作为 std::runtime_error 抛出
Referenced by jevois::dnn::NetworkHailo::doprocess(), and jevois::dnn::PostProcessorDetectYOLO::yolo().
joinall() [2/2]
void jevois::joinall (std::vector< std::future< void >> & fvec, bool multiline = true)
从多个异步线程收集结果，这些线程都返回 T 结果
保证 get() 将在所有 futures 上运行。如果出现任何异常，则收集所有错误消息（如果可能，例如，抛出了 std::exception）并将它们 组装成单个字符串，形式为 `[error 1][error 2] ...` 或 `error 1\nerror 2\n...`，然后将其作为 std::runtime_error
num2str() [1/2]
std::string jevois::num2str (double n)
报告一个具有可变乘数（K、M、G、T、P、E、Z、Y）的数字，精度为小数点后 2 位
Definition at line 511 of file Utils.C.
References jevois::sformat().
Referenced by jevois::dnn::NetworkOpenCV::doprocess().
num2str() [2/2]
void jevois::num2str (std::ostringstream & ss, double n)
报告具有可变乘数 (K、M、G、T、P、E、Z、Y) 的数字
在调用此函数之前，您应该使用流中的 std::setprecision(n) 确定精度。
Definition at line 526 of file Utils.C.
replaceAll()
std::string jevois::replaceAll (std::string const & str, std::string const & from, std::string const & to)
将所有 'from' 实例替换为 'to'
Definition at line 361 of file Utils.C.
Referenced by jevois::dnn::Pipeline::process().
replaceStringAll()
size_t jevois::replaceStringAll (std::string & str, std::string const & from, std::string const & to)
将所有 'from' 实例替换为 'to'
Definition at line 344 of file Utils.C.
Referenced by jevois::dnn::readLabelsFile().
replaceStringFirst()
size_t jevois::replaceStringFirst (std::string & str, std::string const & from, std::string const & to)
将 'from' 的第一个实例替换为 'to'
Definition at line 331 of file Utils.C.
replaceWhitespace()
std::string jevois::replaceWhitespace (std::string const & str, char rep = '_')
用下划线（默认）或其他字符替换字符串中的空格字符
Definition at line 300 of file Utils.C.
Referenced by jevois::StdModule::sendSerialContour2D(), jevois::StdModule::sendSerialObjDetImg2D(), jevois::StdModule::sendSerialObjReco(), jevois::StdModule::sendSerialStd1Dx(), jevois::StdModule::sendSerialStd1Dy(), jevois::StdModule::sendSerialStd2D(), and jevois::StdModule::sendSerialStd3D().
secs2str() [1/3]
std::string jevois::secs2str (double secs)
报告以秒为单位的持续时间，单位可变（ns、us、ms 或 s），精度为小数点后 2 位
Definition at line 478 of file Utils.C.
References jevois::sformat().
Referenced by jevois::dnn::Pipeline::process(), jevois::Timer::stop(), jevois::Profiler::stop(), and jevois::TimerOne::stop().
secs2str() [2/3]
void jevois::secs2str (std::ostringstream & ss, double secs)
报告以秒为单位的持续时间（ns、us、ms 或 s）
在调用此函数之前，您应该使用流中的 std::setprecision(n) 确定精度。
Definition at line 502 of file Utils.C.
secs2str() [3/3]
std::string jevois::secs2str (std::vector< double > secs)
报告以秒为单位给出的 avg+/-std 持续时间，单位为变量（ns、us、ms 或 s），带有 1 个小数点
Definition at line 487 of file Utils.C.
References jevois::sformat().
sformat()
std::string jevois::sformat (char const * fmt, ...)
使用 printf 样式参数创建字符串
Example:
std::string s = jevois::sformat("MyString_%f_%d", 1.0, 2);
通常应避免使用 sformat()，而应使用 C++ 的流式运算符，但有一个例外，即当发出包含浮点数的串行消息时，sformat 的类似 printf 的语法可用于快速轻松地指定数值精度。
Definition at line 439 of file Utils.C.
Referenced by jevois::DMPdata::activity(), jevois::dnn::NetworkTPU::doprocess(), jevois::dnn::NetworkHailo::doprocess(), jevois::GUIhelper::iinfo(), jevois::num2str(), jevois::Camera::readRegister(), jevois::dnn::PostProcessorClassify::report(), jevois::dnn::PostProcessorDetect::report(), jevois::dnn::PostProcessorYuNet::report(), jevois::secs2str(), jevois::StdModule::sendSerialObjDetImg2D(), jevois::Camera::writeRegister(), and jevois::dnn::PostProcessorDetectYOLO::yolo().
split()
std::vector< std::string > jevois::split (std::string const & input, std::string const & regex = `\\s+`)
使用正则表达式将字符串拆分为 tokens 向量以指定要拆分的内容；默认正则表达式按空格拆分
Definition at line 270 of file Utils.C.
Referenced by jevois::drawErrorImage(), jevois::GUIhelper::drawSystem(), jevois::Serial::filePut(), jevois::GUIhelper::GUIhelper(), jevois::dnn::NetworkNPU::load(), jevois::dnn::PostProcessorClassify::onParamChange(), jevois::dnn::PostProcessorDetect::onParamChange(), jevois::Engine::parseCommand(), jevois::dnn::parseTensorSpecs(), jevois::dnn::PreProcessorBlob::process(), jevois::dnn::Pipeline::process(), jevois::dnn::Network::process(), jevois::dnn::strshape(), jevois::warnAndIgnoreException(), jevois::warnAndRethrowException(), and jevois::ChatBox::writeString().
strfcc()
unsigned int jevois::strfcc (std::string const & str)
将 JeVois 视频格式字符串转换为 V4L2 four-cc 代码 (V4L2_PIX_FMT_...)
如果 str 不是以下之一，则抛出运行时错误：BAYER、YUYV、GREY、GRAY、MJPG、RGB565、BGR24 或 NONE。
Definition at line 111 of file Utils.C.
References ISP_V4L2_PIX_FMT_META, and JEVOISPRO_FMT_GUI.
stringStartsWith()
bool jevois::stringStartsWith (std::string const & str, std::string const & prefix)
如果 str 以 prefix 开头，则返回 true（包括两个字符串相等的情况）
Definition at line 294 of file Utils.C.
Referenced by jevois::GUIserial::draw(), jevois::GUIconsole::draw(), jevois::GUIhelper::drawSystem(), jevois::Serial::filePut(), jevois::Engine::postInit(), and jevois::dnn::Pipeline::showInfo().
strip()
std::string jevois::strip (std::string const & str)
从字符串末尾去除空格（包括 CR、LF、tabs 等）
Definition at line 308 of file Utils.C.
Referenced by jevois::Engine::runScriptFromFile().
system()
std::string jevois::system (std::string const & cmd, bool errtoo = true)
执行命令并将 stdout 输出抓取到字符串
如果 errtoo 为真，我们还通过在命令后附加 2>&1 来抓取错误。如果命令无法以某种方式运行，或者以非零退出代码退出，则抛出 std::runtime_error。
Definition at line 461 of file Utils.C.
References LFATAL.
Referenced by jevois::GUIhelper::compileCommand(), jevois::GUIhelper::drawSystem(), jevois::getNumInstalledTPUs(), jevois::getNumInstalledVPUs(), jevois::Engine::parseCommand(), jevois::Engine::reboot(), jevois::Watchdog::run(), jevois::MovieOutput::streamOff(), and jevois::MovieOutput::~MovieOutput().
to_string()
template<typename T >
std::string jevois::to_string (T const & val)
从字符串转换为类型，适用于整数类型的版本
Referenced by jevois::dnn::attrstr(), jevois::CameraDevice::CameraDevice(), jevois::cvtypestr(), jevois::dnn::NetworkTPU::doprocess(), jevois::dnn::NetworkHailo::doprocess(), jevois::dnn::NetworkNPU::doprocess(), jevois::GUIhelper::drawImage(), jevois::GUIhelper::drawInputFrame(), jevois::GUIhelper::drawInputFrame2(), jevois::Serial::fileGet(), jevois::dnn::getLabel(), jevois::getNumInstalledSPUs(), jevois::getNumInstalledTPUs(), jevois::StdModule::getStamp(), jevois::getSysInfoCPU(), jevois::dnn::hailo2vsi(), jevois::Engine::loadCameraCalibration(), main(), jevois::dnn::onnx2vsi(), jevois::Engine::parseCommand(), jevois::dnn::PreProcessorPythonImpl::process(), jevois::dnn::PreProcessorBlob::process(), jevois::VideoBuffers::qbuf(), jevois::Watchdog::run(), jevois::Engine::runScriptFromFile(), jevois::CameraCalibration::save(), jevois::Engine::saveCameraCalibration(), jevois::ImGuiBackendMALI::scanDevices(), jevois::StdModule::sendSerialObjDetImg2D(), jevois::Camera::setFormat(), jevois::dnn::shapestr(), jevois::dnn::Pipeline::showDataPeekWindow(), jevois::VideoMapping::sopath(), jevois::dnn::tensorattr(), and jevois::dnn::vsi2cv().
tolower()
std::string jevois::tolower (std::string const & str)
Convert string to lowercase.
Definition at line 377 of file Utils.C.
v4l2BytesPerPix()
unsigned int jevois::v4l2BytesPerPix (unsigned int fcc)
返回给定 V4L2_PIX_FMT_ 每像素的字节数...
Definition at line 141 of file Utils.C.
References jevois::fccstr(), ISP_V4L2_PIX_FMT_META, JEVOISPRO_FMT_GUI, and LFATAL.
Referenced by jevois::RawImage::bytesize(), jevois::RawImage::bytesperpix(), jevois::rawimage::cvImage(), jevois::GPUtextureDmaBuf::GPUtextureDmaBuf(), and jevois::v4l2ImageSize().
v4l2ImageSize()
unsigned int jevois::v4l2ImageSize (unsigned int fcc, unsigned int width, unsigned int height)
返回给定 V4L2_PIX_FMT_... 的图像大小（以字节为单位）, width, height
Definition at line 168 of file Utils.C.
References jevois::v4l2BytesPerPix().
Referenced by jevois::VideoMapping::c2size(), jevois::VideoMapping::csize(), jevois::VideoMapping::osize(), jevois::CameraDevice::streamOn(), and jevois::Gadget::streamOn().
whiteColor()
unsigned int jevois::whiteColor (unsigned int fcc)
返回对应于给定视频格式的白色的值
Definition at line 197 of file Utils.C.
References jevois::fccstr(), JEVOISPRO_FMT_GUI, and LFATAL.
Referenced by jevois::drawErrorImage().