调试辅助类、函数和宏
Classes
class jevois::Log< Level >
Logger 类
class jevois::timed_lock_guard
在 std::timed_mutex 上获取锁对象，或在等待 1 秒后 LFATAL
class jevois::Profiler
简单的 profiler 类
class jevois::Timer
简单计时器类
class jevois::TimerOne
简单的一次性计时器类
class jevois::Watchdog
简单的看门狗类
Macros
#define LDEBUG(msg)
方便用户打印出控制台或系统日志消息的宏，DEBUG 级别
#define PLDEBUG(msg)
与 LDEBUG 类似，但附加了 errno 和 strerror(errno)，用于某些系统调用失败时
#define LINFO(msg)
方便用户打印控制台或系统日志消息的宏，INFO 级别
#define PLINFO(msg)
与 LINFO 类似但附加 errno 和 strerror(errno)，用于某些系统调用失败时
#define LERROR(msg)
方便用户打印控制台或系统日志消息的宏， ERROR level
#define PLERROR(msg)
与 LERROR 类似但附加 errno 和 strerror(errno)，用于某些系统调用失败时
#define LFATAL(msg)
Convenience macro for users to print out console or syslog messages, FATAL level.
#define PLFATAL(msg)
方便用户打印控制台或系统日志消息的宏，FATAL 级别
#define JEVOIS_ASSERT(cond)
测试某事是否为真，如果不是，则发出 LFATAL
#define JEVOIS_TRACE(level)
Trace object.
#define JEVOIS_TIMED_LOCK(mtx)
辅助宏用于创建 timed_lock_guard 对象
Functions
void jevois::warnAndRethrowException (std::string const &prefix=``)
便捷函数用于捕获异常、发出一些 LERROR（取决于类型）并重新抛出它
std::string jevois::warnAndIgnoreException (std::string const &prefix=``)
便捷函数用于捕获异常、发出一些 LERROR（取决于类型）并忽略它
void jevois::warnAndRethrowParamCallbackException (std::string const &descriptor, std::string const &strval)
参数回调异常的便捷函数
void jevois::logSetEngine (Engine *e)
设置引擎，以便所有日志消息都转发到其串行端口
std::string jevois::getPythonExceptionString (boost::python::error_already_set &)
Python 异常转换为字符串，以便我们可以将回溯打印到我们的 serlog stream.
std::string jevois::getSysInfoCPU ()
获取 CPU 信息： frequency, thermal, load
std::string jevois::getSysInfoMem ()
Get memory info.
std::string jevois::getSysInfoVersion ()
Get O.S. version info.
Variables
int jevois::logLevel = LOG_INFO
当前日志级别
int jevois::traceLevel = 0
当前跟踪级别
Macro Definition Documentation
JEVOIS_ASSERT
#define JEVOIS_ASSERT(cond)
测试某事是否为真，如果不是，则发出 LFATAL
Definition at line 241 of file Log.H.
JEVOIS_TIMED_LOCK
#define JEVOIS_TIMED_LOCK(mtx)
辅助宏用于创建 timed_lock_guard 对象
在 std::timed_mutex mtx 上创建一个 timed_lock_guard，如果在超时之前无法锁定 mtx，则会抛出该异常。该保护程序将在销毁 时解锁互斥锁。
Definition at line 310 of file Log.H.
JEVOIS_TRACE
#define JEVOIS_TRACE(level)
Trace object.
像使用 std::lock_guard 一样使用它。在构造时发出一条 LDEBUG() 消息，在销毁时发出一条消息。通常，您会在每个要跟踪的 函数中调用 JEVOIS_TRACE 作为第一个命令。
Definition at line 279 of file Log.H.
LDEBUG
#define LDEBUG(msg)
方便用户打印出控制台或系统日志消息的宏，DEBUG 级别
此宏旨在与面向流的语法一起使用，用于作为参数传递给宏的所有内容。该语法一开始有点奇怪，但您很快就会习惯它。这允许在 日志中打印出任何定义了运算符 << 的数据类型（与 printf 样式的语法相反）。例如：
int x = 3; std::string str = "hello"; jevois::StepRange<int> rng(0, 5, 100);
LDEBUG("x=" << x << " and str=" << str << " and rng=" << rng);
Note
这是发出消息的首选方式。不要使用 printf，不要使用 cout<<`blah` 等。
Warning
LDEBUG()、LINFO() 和 LERROR() 中不允许使用换行符（'
' 和类似符号），因为这些可能会通过串行端口发送到 Arduino 等简单处理器，只需一个前缀（“DBG”、“INF”、“ERR”）后跟消息，即可轻松解析。如果您发送多行消息，JeVois-Inventor 可能无法运行。异常错误消息以及 LFATAL() 和 LTHROW() 中允许使用换行符，并且多行将作为几条连续消息发送。
根据设计，如果当前日志级别低于（高于）调试级别，则不会评估您的日志消息。这意味着您不必担心浪费 CPU 计算不会输出的消息； 例如：
LINFO("CPU-intensive function says: " << cpu_intensive_function());
如果当前日志级别为 LOG_ERR，则不会运行 CPU 密集型函数（它仍将运行一个 `if` 语句来检查当前日志级别）。这也意味着您永远 不应假设您的日志消息将被评估。例如：
@code
 int x = 42; LDEBUG(`x = ` << (x++)); // x 现在可能是 43 或 42，具体取决于当前日志级别...
Note
因为 LDEBUG() 可用于调试许多快速循环，包括通过使用 JEVOIS_TRACE(level)，所以只有在构建期间定义了 JEVOIS_LDEBUG_ENABLE 时才会编译它（通常，这是作为传递给 cmake 的选项完成的），否则它将被注释掉，这样就不会浪费 CPU。
Definition at line 158 of file Log.H.
LERROR
#define LERROR(msg)
方便用户打印控制台或系统日志消息的宏， ERROR level
使用语法与 LDEBUG(msg)
Definition at line 196 of file Log.H.
LFATAL
#define LFATAL(msg)
Convenience macro for users to print out console or syslog messages, FATAL level.
方便用户抛出 std::runtime_error 的便利宏，具有方便的消息格式
使用语法与 LDEBUG(msg)
Note
After printing the message, this also throws std::runtime_error
使用语法与 LDEBUG(msg) 相同。此函数不会向用户提供的错误消息添加任何内容。因此，这主要用于捕获异常并通 过 LFATAL() 发出合并错误消息的情况（可能添加更多上下文详细信息）。
Note
这会抛出 std::runtime_error
LINFO
#define LINFO(msg)
方便用户打印控制台或系统日志消息的宏，INFO 级别
Usage syntax is the same as for LDEBUG(msg)
Definition at line 179 of file Log.H.
PLDEBUG
#define PLDEBUG(msg)
与 LDEBUG 类似，但附加了 errno 和 strerror(errno)，用于某些系统调用失败时
使用语法与 LDEBUG(msg) 相同
Definition at line 166 of file Log.H.
PLERROR
#define PLERROR(msg)
与 LERROR 类似但附加 errno 和 strerror(errno)，用于某些系统调用失败时
使用语法与 LDEBUG(msg)
Definition at line 204 of file Log.H.
PLFATAL
#define PLFATAL(msg)
方便用户打印控制台或系统日志消息的宏，FATAL 级别
使用语法与 LDEBUG(msg)
Note
打印消息后，这也会引发 std::runtime_error
Definition at line 224 of file Log.H.
PLINFO
#define PLINFO(msg)
与 LINFO 类似但附加 errno 和 strerror(errno)，用于某些系统调用失败时
使用语法与 LDEBUG(msg)
Definition at line 187 of file Log.H.
Function Documentation
getPythonExceptionString()
std::string jevois::getPythonExceptionString (boost::python::error_already_set &)
Python 异常转换为字符串，以便我们可以将回溯打印到我们的 serlog stream.
This code inspired from: https://github.com/abingham/boost_python_exception/tree/master/src/boost_python_exception/auto_translation
您通常会在 catch(boost::python::error_already_set & e) { ... } 块内部使用它。
Definition at line 154 of file PythonException.C.
Referenced by jevois::PythonWrapper::pythonload(), jevois::GUIhelper::reportAndIgnoreException(), jevois::warnAndIgnoreException(), jevois::warnAndRethrowException(), and jevois::warnAndRethrowParamCallbackException().
getSysInfoCPU()
std::string jevois::getSysInfoCPU ()
获取 CPU 信息： frequency, thermal, load
Definition at line 24 of file SysInfo.C.
References jevois::getFileString(), and jevois::to_string().
Referenced by jevois::GUIhelper::drawSystem(), and jevois::Engine::parseCommand().
getSysInfoMem()
std::string jevois::getSysInfoMem ()
Get memory info.
Definition at line 66 of file SysInfo.C.
References jevois::getFileString().
Referenced by jevois::GUIhelper::drawSystem(), and jevois::Engine::parseCommand().
getSysInfoVersion()
std::string jevois::getSysInfoVersion ()
Get O.S. version info.
Definition at line 74 of file SysInfo.C.
References jevois::getFileString().
Referenced by jevois::GUIhelper::drawSystem(), and jevois::Engine::parseCommand().
logSetEngine()
void jevois::logSetEngine (Engine * e)
设置引擎，以便所有日志消息都转发到其串行端口
此功能不适用于一般用途，当用户设置其某个参数以启用将日志消息转发到串行端口时，引擎会在内部使用它。
Definition at line 143 of file Log.C.
Referenced by jevois::logEnd(), jevois::Engine::postInit(), and jevois::Engine::~Engine().
warnAndIgnoreException()
std::string jevois::warnAndIgnoreException (std::string const & prefix = ``)
便捷函数用于捕获异常、发出一些 LERROR（取决于类型）并忽略它
用户代码可以按如下方式使用此函数，记录一些引发的异常的踪迹，然后吞掉（忽略）该异常。请谨慎使用，吞掉异常通常会破 坏使用异常的整个逻辑。示例用法：
try { do_something_risky_and_we_dont_care_if_it_fails(); } catch (...) { jevois::warnAndIgnoreException(); }
请注意，如果有人想以其他方式报告它（例如，在 GUI 中或使用 drawErrorImage() 的视频帧中），则记录到控制台的消息也会 作为字符串返回。
Definition at line 235 of file Log.C.
References jevois::getPythonExceptionString(), LERROR, and jevois::split().
Referenced by jevois::Camera::abortStream(), jevois::GUIhelper::compileCommand(), jevois::Engine::foreachVideoMapping(), jevois::GUIhelper::headlessDisplay(), jevois::ImGuiBackendMALI::init(), jevois::GPUshader::load(), jevois::Engine::mainLoop(), jevois::Engine::postInit(), jevois::dnn::Pipeline::process(), jevois::Engine::runScriptFromFile(), jevois::Engine::sendSerial(), jevois::CameraDevice::streamOff(), jevois::Camera::streamOff(), jevois::Camera::streamOn(), jevois::Camera::~Camera(), jevois::CameraDevice::~CameraDevice(), jevois::Engine::~Engine(), jevois::Gadget::~Gadget(), jevois::ImGuiBackendMALI::~ImGuiBackendMALI(), and jevois::MovieOutput::~MovieOutput().
warnAndRethrowException()
void jevois::warnAndRethrowException (std::string const & prefix = ``)
便捷函数用于捕获异常、发出一些 LERROR（取决于类型）并重新抛出它
不会吞下异常的用户代码可以按如下方式使用此函数来记录一些被抛出的异常的踪迹：
try { do_something_risky(); } catch (...) { jevois::warnAndRethrowException(); }
Note
此函数抛出异常！因此，显然只有在 catch 块内使用它才有意义。
Definition at line 202 of file Log.C.
References jevois::getPythonExceptionString(), LERROR, and jevois::split().
Referenced by jevois::dnn::NetworkNPU::doprocess(), and jevois::dnn::Network::ready().
warnAndRethrowParamCallbackException()
void jevois::warnAndRethrowParamCallbackException (std::string const & descriptor, std::string const & strval)
参数回调异常的便捷函数
由 Parameter 内部使用，可能对其他人没那么有用，包含在 jevois 命名空间中，以避免必须将 boost::python 拉入 Parameter，这会将其拉入几乎所有内容并大大增加编译时间。
Note
此函数抛出！因此显然只有在 catch 块内使用它才有意义。
Definition at line 273 of file Log.C.
References jevois::getPythonExceptionString(), and LERROR.
Variable Documentation
logLevel
int jevois::logLevel = LOG_INFO
当前日志级别
通过改变此全局变量的值来设置日志级别。默认值为 LOG_INFO。
可能的日志值在 sys/syslog.h 中定义，这里我们只处理以下不同数量的消息：LOG_CRIT、LOG_ERR、LOG_INFO、LOG_DEBUG。
Definition at line 29 of file Log.C.
Referenced by main().
traceLevel
int jevois::traceLevel = 0
当前跟踪级别
级别越高，跟踪越详细。请注意，只有当 JEVOIS_TRACE_ENABLE 被指定为编译选项，并且跟踪消息在 LDEBUG 日志级别发出时， 这才会有效，因此在编译时还必须指定 JEVOIS_LDEBUG_ENABLE。
Definition at line 30 of file Log.C.