控制台访问实用程序
控制台相关的实用程序和帮助函数。
Functions
bool jevois::isInputDevice (int fd)
指示此 fd（应来自 /dev/input/eventX）是否是键盘、鼠标等
int jevois::getConsoleFd ()
获取控制台的文件描述符
int jevois::getActiveTTY ()
获取当前活动 tty
void jevois::muteKeyboard (int tty, int &kb_mode)
防止 keystrokes 到达 tty
void jevois::unMuteKeyboard (int tty, int kb_mode)
恢复给定 tty 的键盘模式
Function Documentation
getActiveTTY()
int jevois::getActiveTTY ()
获取当前活动 tty
Definition at line 121 of file Console.C.
References IS_CONSOLE.
Referenced by jevois::ImGuiBackendMALI::init(), and main().
getConsoleFd()
int jevois::getConsoleFd ()
获取控制台的文件描述符
Definition at line 85 of file Console.C.
References NELEMS.
Referenced by jevois::ImGuiBackendMALI::init(), and main().
isInputDevice()
bool jevois::isInputDevice (int fd)
指示此 fd（应来自 /dev/input/eventX）是否是键盘、鼠标等
受 SFML-rpi 启发
Definition at line 36 of file Console.C.
References NBITS, and test_bit.
Referenced by jevois::ImGuiBackendMALI::scanDevices().
muteKeyboard()
void jevois::muteKeyboard (int tty, int & kb_mode)
防止 keystrokes 到达 tty
Definition at line 103 of file Console.C.
References IS_CONSOLE, K_OFF, KDSKBMODE, and KDSKBMUTE.
Referenced by jevois::ImGuiBackendMALI::init().
unMuteKeyboard()
void jevois::unMuteKeyboard (int tty, int kb_mode)
恢复给定 tty 的键盘模式
使用 muteKeyboard() 返回的 kd_mode。
Definition at line 114 of file Console.C.
References KDSKBMODE, and KDSKBMUTE.
Referenced by main(), and jevois::ImGuiBackendMALI::~ImGuiBackendMALI().