Raw 零拷贝/内存映射视频图像和支持函数
支持图像的类和函数的主要目的是允许处理内存映射到硬件（相机或 USB 驱动程序）的图像缓冲区，而无需复制数据。还有许多其他库和框 架可用，它们定义了更完整的图像类和相关的图像处理和机器视觉功能。这里提供的函数允许您将原始图像缓冲区重新解释为 OpenCV cv::Mat 图像等，而无需复制图像像素数据。为了创建演示显示，还提供了将图像复制、粘贴、绘制、文本等简单复制到原始 YUYV 图像缓 冲区（通常从 USB 驱动程序获得，需要填充一些像素数据才能通过 USB 链路发送）的功能。
表示具有像素缓冲区的图像的类称为 RawImage，相机或 USB 硬件可直接访问该缓冲区（参见 VideoBuf）。为了避免再次定义像素类型（ 大多数与图像相关的库已经这样做了），我们在 RawImage 中只使用 Video4Linux2 提供的定义。
因此，对 RawImage 进行操作的函数主要有两个目的：1) 从 RawImage 中获取像素数据并将其转换为另一种格式（如 OpenCV），或从其 他格式转换为 RawImage；2) 允许简单绘制线条、圆形、矩形等，以便直接在 RawImage 缓冲区中进行简单的演示显示，并通过 USB 链 接发送。 Collaboration diagram for Raw 零拷贝/内存映射视频图像和支持函数:
Classes
class jevois::RawImage
来自 V4L2 Camera 和/或发送到 USB Gadget 的原始图像
Namespaces
 jevois::yuyv
辅助 YUYV 颜色
 jevois::rgb565
辅助 RGB565 颜色
Modules
Jpeg 相关的类和函数
Jpeg 类和函数，主要用于支持从相机捕获的原始未压缩图像通过 USB 发送 MJPEG 视频输出。
Enumerations
enum jevois::rawimage::Font {
jevois::rawimage::Font5x7,
jevois::rawimage::Font6x10,
jevois::rawimage::Font7x13,
jevois::rawimage::Font8x13bold,
jevois::rawimage::Font9x15bold,
jevois::rawimage::Font10x20,
jevois::rawimage::Font11x22,
jevois::rawimage::Font12x22,
jevois::rawimage::Font14x26,
jevois::rawimage::Font15x28,
jevois::rawimage::Font16x29,
jevois::rawimage::Font20x38
 }
可用于 writeText() 的字体
Functions
void convertYUYVtoRGBYL (unsigned int w, unsigned int h, unsigned char const *src, int *dstrg, int *dstby, int *dstlum, int thresh, int inputbits)
将 YUYV 转换为 RG、BY 和亮度，以供 jevoisbase 中的 Saliency 模块使用。供内部使用。
cv::Mat jevois::rawimage::cvImage (RawImage const &src)
从现有 RawImage 数据创建 OpenCV 图像，共享像素内存而不是复制它
cv::Mat jevois::rawimage::convertToCvBGR (RawImage const &src)
将 RawImage 转换为 OpenCV，从任何 RawImage 源像素执行颜色转换为 OpenCV BGR 字节
cv::Mat jevois::rawimage::convertToCvRGB (RawImage const &src)
将 RawImage 转换为 OpenCV，从任何 RawImage 源像素到 OpenCV RGB 字节进行颜色转换
cv::Mat jevois::rawimage::convertToCvRGBA (RawImage const &src)
将 RawImage 转换为 OpenCV，从任何 RawImage 源像素到 OpenCV RGB-A 字节进行颜色转换
void jevois::rawimage::byteSwap (RawImage &img)
交换 RawImage 中的字节对
void jevois::rawimage::paste (RawImage const &src, RawImage &dest, int dx, int dy)
将一张图像粘贴到另一张相同像素类型的图像中
void jevois::rawimage::pasteGreyToYUYV (cv::Mat const &src, RawImage &dest, int dx, int dy)
将灰度字节图像粘贴到 YUYV 图像中
void jevois::rawimage::pasteBGRtoYUYV (cv::Mat const &src, RawImage &dst, int dx, int dy)
将 BGR 字节图像粘贴到 YUYV 图像中
void jevois::rawimage::pasteRGBtoYUYV (cv::Mat const &src, RawImage &dst, int dx, int dy)
将 RGB 字节图像粘贴到 YUYV 图像中
void jevois::rawimage::roipaste (RawImage const &src, int x, int y, unsigned int w, unsigned int h, RawImage &dest, int dx, int dy)
将图像中的 ROI 粘贴到相同像素类型的另一个图像中
void jevois::rawimage::drawDisk (RawImage &img, int x, int y, unsigned int rad, unsigned int col)
在 YUYV 图像中绘制一个圆盘 disk
void jevois::rawimage::drawCircle (RawImage &img, int x, int y, unsigned int rad, unsigned int thick, unsigned int col)
在YUYV图像中绘制一个圆圈
bool jevois::rawimage::clipLine (int wxmin, int wymin, int wxmax, int wymax, int &x1, int &y1, int &x2, int &y2)
剪裁一条线以适合 viewport [wxmin...wxmax[ x [wymin...wymax]
void jevois::rawimage::drawLine (RawImage &img, int x1, int y1, int x2, int y2, unsigned int thick, unsigned int col)
在 YUYV 图像中绘制一条线
void jevois::rawimage::drawRect (RawImage &img, int x, int y, unsigned int w, unsigned int h, unsigned int thick, unsigned int col)
在 YUYV 图像中绘制一个矩形
void jevois::rawimage::drawRect (RawImage &img, int x, int y, unsigned int w, unsigned int h, unsigned int col)
在 YUYV 图像中绘制矩形
void jevois::rawimage::drawFilledRect (RawImage &img, int x, int y, unsigned int w, unsigned int h, unsigned int col)
在 YUYV 图像中绘制填充矩形
void jevois::rawimage::writeText (RawImage &img, std::string const &txt, int x, int y, unsigned int col, Font font=Font6x10)
在图像中写一些文字
void jevois::rawimage::writeText (RawImage &img, char const *txt, int x, int y, unsigned int col, Font font=Font6x10)
在图像中写一些文字
void jevois::rawimage::convertCvBGRtoRawImage (cv::Mat const &src, RawImage &dst, int quality)
将 BGR cv::Mat 转换为具有已分配像素和像素类型的 RawImage
void jevois::rawimage::convertCvRGBtoRawImage (cv::Mat const &src, RawImage &dst, int quality)
将 RGB cv::Mat 转换为具有已分配像素和像素类型的 RawImage
void jevois::rawimage::convertCvRGBAtoRawImage (cv::Mat const &src, RawImage &dst, int quality)
使用已分配的像素和像素类型将 RGBA cv::Mat 转换为 RawImage
void jevois::rawimage::convertCvGRAYtoRawImage (cv::Mat const &src, RawImage &dst, int quality)
使用已分配的像素和像素类型将灰色 cv::Mat 转换为 RawImage
void jevois::rawimage::hFlipYUYV (RawImage &img)
水平翻转 YUYV RawImage 同时保留颜色信息
void jevois::rawimage::convertCvRGBtoCvYUYV (cv::Mat const &src, cv::Mat &dst)
OpenCV 没有在 cvtColor() 中提供从 RGB 到 YUYV 的转换，因此此函数提供它
void jevois::rawimage::convertCvBGRtoCvYUYV (cv::Mat const &src, cv::Mat &dst)
OpenCV 没有在 cvtColor() 中提供从 RGB 到 YUYV 的转换，因此此函数提供它
void jevois::rawimage::convertCvGRAYtoCvYUYV (cv::Mat const &src, cv::Mat &dst)
OpenCV 没有在 cvtColor() 中提供从 RGB 到 YUYV 的转换，因此此函数提供它
void jevois::rawimage::convertCvRGBAtoCvYUYV (cv::Mat const &src, cv::Mat &dst)
OpenCV 没有在 cvtColor() 中提供从 RGB 到 YUYV 的转换，因此此函数提供它
cv::Mat jevois::rescaleCv (cv::Mat const &img, cv::Size const &newdims)
重新缩放 OpenCV 图像，选择正确的插值类型
Enumeration Type Documentation
Font
enum jevois::rawimage::Font
可用于 writeText() 的字体
Enumerator
Font5x7
Font6x10
Font7x13
Font8x13bold
Font9x15bold
Font10x20
Font11x22
Font12x22
Font14x26
Font15x28
Font16x29
Font20x38
Definition at line 146 of file RawImageOps.H.
Function Documentation
byteSwap()
void jevois::rawimage::byteSwap (jevois::RawImage & img)
交换 RawImage 中的字节对
这永远都不需要，除非是 RGB565 图像，主要用于内部调试，或者直接将 RGB565 相机图像（大端字节序）传递到 USB（使用 RGBP UVC 格式时假定为小端字节序）。此函数在为平台硬件编译时是 NEON 加速的。
Definition at line 368 of file RawImageOps.C.
References jevois::async(), jevois::RawImage::bytesize(), jevois::RawImage::bytesperpix(), jevois::RawImage::height, LFATAL, jevois::RawImage::pixelsw(), and jevois::RawImage::width.
clipLine()
bool jevois::rawimage::clipLine (int wxmin, int wymin, int wxmax, int wymax, int & x1, int & y1, int & x2, int & y2)
剪裁一条线以适合 viewport [wxmin...wxmax[ x [wymin...wymax]
这使用 Liang-Barsky 线剪裁算法。如果线完全在 viewport 之外（没有可绘制的内容），则返回 false。
Definition at line 533 of file RawImageOps.C.
Referenced by jevois::rawimage::drawLine().
convertCvBGRtoCvYUYV()
void jevois::rawimage::convertCvBGRtoCvYUYV (cv::Mat const & src, cv::Mat & dst)
OpenCV 没有在 cvtColor() 中提供从 RGB 到 YUYV 的转换，因此此函数提供它
Definition at line 1062 of file RawImageOps.C.
References jevois::cvtypestr(), and LFATAL.
convertCvBGRtoRawImage()
void jevois::rawimage::convertCvBGRtoRawImage (cv::Mat const & src, RawImage & dst, int quality)
将 BGR cv::Mat 转换为具有已分配像素和像素类型的 RawImage
这用于通过 USB 从内部计算的 opencv BGR 格式的结果输出视频帧。dst 应该已经有一个分配的像素缓冲区（通常，它应该从 USB gadget中获取），并且它的大小必须与 src 图像的大小相匹配。
支持的 dst 像素格式：
V4L2_PIX_FMT_YUYV
V4L2_PIX_FMT_GREY
V4L2_PIX_FMT_SRGGB8 (Bayer)
V4L2_PIX_FMT_RGB565
V4L2_PIX_FMT_MJPG
V4L2_PIX_FMT_BGR24
质量仅在 dst 为 MJPG 时使用，并且应介于 1 到 100 之间。
Definition at line 1302 of file RawImageOps.C.
References jevois::RawImage::bytesperpix(), jevois::compressBGRtoJpeg(), jevois::rawimage::cvImage(), jevois::cvtypestr(), jevois::fccstr(), jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, jevois::RawImage::pixelsw(), and jevois::RawImage::width.
Referenced by jevois::MovieInput::get(), jevois::MovieInput::get2(), jevois::OutputFrame::sendCvBGR(), and jevois::OutputFrame::sendScaledCvBGR().
convertCvGRAYtoCvYUYV()
void jevois::rawimage::convertCvGRAYtoCvYUYV (cv::Mat const & src, cv::Mat & dst)
OpenCV 没有在 cvtColor() 中提供从 RGB 到 YUYV 的转换，因此此函数提供它
Definition at line 1220 of file RawImageOps.C.
References jevois::cvtypestr(), and LFATAL.
convertCvGRAYtoRawImage()
void jevois::rawimage::convertCvGRAYtoRawImage (cv::Mat const & src, RawImage & dst, int quality)
使用已分配的像素和像素类型将灰色 cv::Mat 转换为 RawImage
这用于通过 USB 输出内部计算结果为 opencv 灰度格式的视频帧。dst 应该已经分配了一个像素缓冲区（通常，它应该从 USB 小工具中获 取），并且其大小必须与 src 图像的大小相匹配。
支持的 dst 像素格式：
V4L2_PIX_FMT_YUYV
V4L2_PIX_FMT_GREY
V4L2_PIX_FMT_SRGGB8 (Bayer)
V4L2_PIX_FMT_RGB565
V4L2_PIX_FMT_MJPG
V4L2_PIX_FMT_BGR24
质量仅在 dst 为 MJPG 时使用，并且应介于 1 到 100 之间。
Definition at line 1395 of file RawImageOps.C.
References jevois::RawImage::bytesperpix(), jevois::compressGRAYtoJpeg(), jevois::rawimage::cvImage(), jevois::cvtypestr(), jevois::fccstr(), jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, jevois::RawImage::pixelsw(), and jevois::RawImage::width.
Referenced by jevois::OutputFrame::sendCvGRAY(), and jevois::OutputFrame::sendScaledCvGRAY().
convertCvRGBAtoCvYUYV()
void jevois::rawimage::convertCvRGBAtoCvYUYV (cv::Mat const & src, cv::Mat & dst)
OpenCV 没有在 cvtColor() 中提供从 RGB 到 YUYV 的转换，因此此函数提供它
Definition at line 1292 of file RawImageOps.C.
References jevois::cvtypestr(), and LFATAL.
convertCvRGBAtoRawImage()
void jevois::rawimage::convertCvRGBAtoRawImage (cv::Mat const & src, RawImage & dst, int quality)
使用已分配的像素和像素类型将 RGBA cv::Mat 转换为 RawImage
这用于通过 USB 从内部计算的结果以 opencv RGB-A 格式（通常是 NEON 或 OpenGL 处理的首选格式）输出视频帧。 dst 应该已经 有一个分配的像素缓冲区（通常，它应该从 USB 小工具中获取），并且其大小必须与 src 图像的大小相匹配。
支持的 dst 像素格式：
V4L2_PIX_FMT_YUYV
V4L2_PIX_FMT_GREY
V4L2_PIX_FMT_SRGGB8 (Bayer)
V4L2_PIX_FMT_RGB565
V4L2_PIX_FMT_MJPG
V4L2_PIX_FMT_BGR24
质量仅在 dst 为 MJPG 时使用，并且应介于 1 到 100 之间。
Definition at line 1373 of file RawImageOps.C.
References jevois::compressRGBAtoJpeg(), jevois::rawimage::cvImage(), jevois::cvtypestr(), jevois::fccstr(), jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, and jevois::RawImage::width.
Referenced by jevois::OutputFrame::sendCvRGBA(), and jevois::OutputFrame::sendScaledCvRGBA().
convertCvRGBtoCvYUYV()
void jevois::rawimage::convertCvRGBtoCvYUYV (cv::Mat const & src, cv::Mat & dst)
OpenCV 没有在 cvtColor() 中提供从 RGB 到 YUYV 的转换，因此此函数提供它
Definition at line 1148 of file RawImageOps.C.
References jevois::cvtypestr(), and LFATAL.
convertCvRGBtoRawImage()
void jevois::rawimage::convertCvRGBtoRawImage (cv::Mat const & src, RawImage & dst, int quality)
将 RGB cv::Mat 转换为具有已分配像素和像素类型的 RawImage
这用于通过 USB 从内部计算的结果以 opencv BGR 格式输出视频帧。dst 应该已经有一个分配的像素缓冲区（通常，它应该从 USB gadget中获取），并且它的大小必须与 src 图像的大小相匹配。
支持的 dst 像素格式：
V4L2_PIX_FMT_YUYV
V4L2_PIX_FMT_GREY
V4L2_PIX_FMT_SRGGB8 (Bayer)
V4L2_PIX_FMT_RGB565
V4L2_PIX_FMT_MJPG
V4L2_PIX_FMT_BGR24
质量仅在 dst 为 MJPG 时使用，并且应介于 1 到 100 之间。
Definition at line 1325 of file RawImageOps.C.
References jevois::RawImage::bytesperpix(), jevois::compressRGBtoJpeg(), jevois::rawimage::cvImage(), jevois::cvtypestr(), jevois::fccstr(), jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, jevois::RawImage::pixelsw(), and jevois::RawImage::width.
Referenced by jevois::OutputFrame::sendCvRGB(), and jevois::OutputFrame::sendScaledCvRGB().
convertToCvBGR()
cv::Mat jevois::rawimage::convertToCvBGR (jevois::RawImage const & src)
将 RawImage 转换为 OpenCV，从任何 RawImage 源像素执行颜色转换为 OpenCV BGR 字节
由于历史原因，BGR 是 OpenCV 的 `native` 颜色格式，请检查您的算法是否需要 RGB 或 BGR，并使用适当的转换。
支持的 RawImage 像素格式：
V4L2_PIX_FMT_YUYV
V4L2_PIX_FMT_GREY
V4L2_PIX_FMT_SRGGB8 (Bayer)
V4L2_PIX_FMT_RGB565
V4L2_PIX_FMT_BGR24
Definition at line 282 of file RawImageOps.C.
References jevois::rawimage::cvImage(), jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, and jevois::RawImage::width.
Referenced by jevois::InputFrame::getCvBGR(), jevois::InputFrame::getCvBGRp(), jevois::dnn::PreProcessor::process(), and jevois::MovieOutput::send().
convertToCvRGB()
cv::Mat jevois::rawimage::convertToCvRGB (jevois::RawImage const & src)
将 RawImage 转换为 OpenCV，从任何 RawImage 源像素到 OpenCV RGB 字节进行颜色转换
由于历史原因，BGR 是 OpenCV 的 `native` 颜色格式，而不是此处创建的 RGB，请检查您的算法是否需要 RGB 或 BGR，并使用适当 的转换。
支持的 RawImage 像素格式：
V4L2_PIX_FMT_YUYV
V4L2_PIX_FMT_GREY
V4L2_PIX_FMT_SRGGB8 (Bayer)
V4L2_PIX_FMT_RGB565
V4L2_PIX_FMT_BGR24
Definition at line 307 of file RawImageOps.C.
References jevois::rawimage::cvImage(), jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, and jevois::RawImage::width.
Referenced by jevois::InputFrame::getCvRGB(), jevois::InputFrame::getCvRGBp(), and jevois::dnn::PreProcessor::process().
convertToCvRGBA()
cv::Mat jevois::rawimage::convertToCvRGBA (jevois::RawImage const & src)
将 RawImage 转换为 OpenCV，从任何 RawImage 源像素到 OpenCV RGB-A 字节进行颜色转换
OpenCV 本身很少使用 RGBA，但对许多 NEON 和 OpenGL (GPU) 算法很有用。对于这些算法，我们在这里仅使用 cv::Mat 作 为原始像素数据的便捷容器。
支持的 RawImage 像素格式：
V4L2_PIX_FMT_YUYV
V4L2_PIX_FMT_GREY
V4L2_PIX_FMT_SRGGB8 (Bayer)
V4L2_PIX_FMT_RGB565
V4L2_PIX_FMT_BGR24
Definition at line 332 of file RawImageOps.C.
References jevois::rawimage::cvImage(), jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, and jevois::RawImage::width.
Referenced by jevois::InputFrame::getCvRGBA(), and jevois::InputFrame::getCvRGBAp().
convertYUYVtoRGBYL()
void convertYUYVtoRGBYL (unsigned int w, unsigned int h, unsigned char const * src, int * dstrg, int * dstby, int * dstlum, int thresh, int inputbits)
将 YUYV 转换为 RG、BY 和亮度，以供 jevoisbase 中的 Saliency 模块使用。供内部使用。
Definition at line 89 of file ColorConversion.c.
References convertYUYVtoRGBYLinternal(), G, and h.
cvImage()
cv::Mat jevois::rawimage::cvImage (jevois::RawImage const & src)
从现有 RawImage 数据创建 OpenCV 图像，共享像素内存而不是复制它
像素数据不会被复制，只是指向，并且不会进行像素格式转换。您应该在 RawImage 之前销毁 cv::Mat，以避免您的 cv::Mat 最终导 致像素内存被释放。
Definition at line 31 of file RawImageOps.C.
References jevois::RawImage::buf, jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, jevois::v4l2BytesPerPix(), and jevois::RawImage::width.
Referenced by jevois::rawimage::convertBayerToYUYV(), jevois::rawimage::convertCvBGRtoRawImage(), jevois::rawimage::convertCvGRAYtoRawImage(), jevois::rawimage::convertCvRGBAtoRawImage(), jevois::rawimage::convertCvRGBtoRawImage(), jevois::rawimage::convertGreyToYUYV(), jevois::rawimage::convertToCvBGR(), jevois::rawimage::convertToCvGray(), jevois::rawimage::convertToCvRGB(), jevois::rawimage::convertToCvRGBA(), and jevois::dnn::PreProcessor::process().
drawCircle()
void jevois::rawimage::drawCircle (jevois::RawImage & img, int x, int y, unsigned int rad, unsigned int thick, unsigned int col)
在YUYV图像中绘制一个圆圈
Definition at line 483 of file RawImageOps.C.
References jevois::rawimage::drawDisk().
Referenced by jevois::dnn::PostProcessorYuNet::report().
drawDisk()
void jevois::rawimage::drawDisk (jevois::RawImage & img, int x, int y, unsigned int rad, unsigned int col)
在 YUYV 图像中绘制一个圆盘 disk
Definition at line 465 of file RawImageOps.C.
References jevois::RawImage::coordsOk(), jevois::RawImage::pixelsw(), and jevois::RawImage::width.
Referenced by jevois::rawimage::drawCircle(), jevois::drawErrorImage(), and jevois::rawimage::drawLine().
drawFilledRect()
void jevois::rawimage::drawFilledRect (jevois::RawImage & img, int x, int y, unsigned int w, unsigned int h, unsigned int col)
在 YUYV 图像中绘制填充矩形
这实际上并不灵活，并且仅针对速度进行了优化。col 将用于 YU 和 YV 像素。对于要求更高的绘图，请使用 openCV 函数。绘制的 像素从 (x,y) 包含到 (x+w-1,y+h-1) 包含。如果 w 或 h 为 0，则将其替换为 1。
Definition at line 646 of file RawImageOps.C.
References h, jevois::RawImage::height, jevois::RawImage::pixelsw(), and jevois::RawImage::width.
drawLine()
void jevois::rawimage::drawLine (jevois::RawImage & img, int x1, int y1, int x2, int y2, unsigned int thick, unsigned int col)
在 YUYV 图像中绘制一条线
Definition at line 564 of file RawImageOps.C.
References jevois::rawimage::clipLine(), jevois::rawimage::drawDisk(), h, jevois::RawImage::height, LFATAL, and jevois::RawImage::width.
Referenced by jevois::drawErrorImage(), jevois::rawimage::drawRect(), and jevois::dnn::PostProcessorYuNet::report().
drawRect() [1/2]
void jevois::rawimage::drawRect (jevois::RawImage & img, int x, int y, unsigned int w, unsigned int h, unsigned int col)
在 YUYV 图像中绘制矩形
这实际上并不灵活，并且仅针对速度进行了优化。col 将用于 YU 和 YV 像素。对于要求更高的绘图，请使用 openCV 函数。绘制的 像素从 (x,y) 包含到 (x+w-1,y+h-1) 包含。如果 w 或 h 为 0，则将其替换为 1。
Definition at line 624 of file RawImageOps.C.
References h, jevois::RawImage::height, jevois::RawImage::pixelsw(), and jevois::RawImage::width.
drawRect() [2/2]
void jevois::rawimage::drawRect (jevois::RawImage & img, int x, int y, unsigned int w, unsigned int h, unsigned int thick, unsigned int col)
在 YUYV 图像中绘制一个矩形
绘制的像素从 (x,y) 包含到 (x+w-1,y+h-1) 包含。如果 w 或 h 为 0，则用 1 替换。
Definition at line 607 of file RawImageOps.C.
References jevois::rawimage::drawLine(), and h.
Referenced by jevois::dnn::PostProcessorDetect::report(), jevois::dnn::PostProcessorYuNet::report(), and jevois::dnn::PreProcessor::sendreport().
hFlipYUYV()
void jevois::rawimage::hFlipYUYV (RawImage & img)
水平翻转 YUYV RawImage 同时保留颜色信息
此函数允许在 Mac 上使用 JeVois 和 PhotoBooth 应用程序，水平翻转图像（围绕垂直轴）。仅支持 YUYV 像素。您可能能够将 OpenCV 中的 cv::flip() 与其他像素类型一起使用。
Definition at line 1452 of file RawImageOps.C.
References jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, jevois::RawImage::pixelsw(), and jevois::RawImage::width.
paste()
void jevois::rawimage::paste (jevois::RawImage const & src, jevois::RawImage & dest, int dx, int dy)
将一张图像粘贴到另一张相同像素类型的图像中
为保持此功能快速运行，如果源图像不完全适合目标图像，或者两张图像的像素格式不同，则会抛出异常。
Definition at line 403 of file RawImageOps.C.
References jevois::RawImage::bytesperpix(), jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, jevois::RawImage::pixels(), jevois::RawImage::pixelsw(), and jevois::RawImage::width.
pasteBGRtoYUYV()
void jevois::rawimage::pasteBGRtoYUYV (cv::Mat const & src, jevois::RawImage & dst, int dx, int dy)
将 BGR 字节图像粘贴到 YUYV 图像中
Definition at line 1072 of file RawImageOps.C.
References jevois::RawImage::bytesperpix(), jevois::cvtypestr(), jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, jevois::RawImage::pixelsw(), and jevois::RawImage::width.
pasteGreyToYUYV()
void jevois::rawimage::pasteGreyToYUYV (cv::Mat const & src, jevois::RawImage & dest, int dx, int dy)
将灰度字节图像粘贴到 YUYV 图像中
Definition at line 448 of file RawImageOps.C.
References jevois::RawImage::bytesperpix(), jevois::RawImage::height, LFATAL, jevois::RawImage::pixelsw(), and jevois::RawImage::width.
pasteRGBtoYUYV()
void jevois::rawimage::pasteRGBtoYUYV (cv::Mat const & src, jevois::RawImage & dst, int dx, int dy)
将 RGB 字节图像粘贴到 YUYV 图像中
Definition at line 1158 of file RawImageOps.C.
References jevois::RawImage::bytesperpix(), jevois::cvtypestr(), jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, jevois::RawImage::pixelsw(), and jevois::RawImage::width.
rescaleCv()
cv::Mat jevois::rescaleCv (cv::Mat const & img, cv::Size const & newdims)
重新缩放 OpenCV 图像，选择正确的插值类型
Definition at line 1660 of file RawImageOps.C.
Referenced by jevois::ImGuiImage::load(), jevois::OutputFrame::sendScaledCvBGR(), jevois::OutputFrame::sendScaledCvGRAY(), jevois::OutputFrame::sendScaledCvRGB(), and jevois::OutputFrame::sendScaledCvRGBA().
roipaste()
void jevois::rawimage::roipaste (jevois::RawImage const & src, int x, int y, unsigned int w, unsigned int h, jevois::RawImage & dest, int dx, int dy)
将图像中的 ROI 粘贴到相同像素类型的另一个图像中
为了保持此功能的快速运行，如果源图像不完全适合目标图像或像素格式不同，则会抛出。
Definition at line 425 of file RawImageOps.C.
References jevois::RawImage::bytesperpix(), jevois::RawImage::fmt, h, jevois::RawImage::height, LFATAL, jevois::RawImage::pixels(), jevois::RawImage::pixelsw(), and jevois::RawImage::width.
writeText() [1/2]
void jevois::rawimage::writeText (jevois::RawImage & img, char const * txt, int x, int y, unsigned int col, Font font = Font6x10)
在图像中写一些文字
Definition at line 697 of file RawImageOps.C.
References jevois::RawImage::bytesperpix(), jevois::font::font10x20, jevois::rawimage::Font10x20, jevois::font::font11x22, jevois::rawimage::Font11x22, jevois::font::font12x22, jevois::rawimage::Font12x22, jevois::font::font14x26, jevois::rawimage::Font14x26, jevois::font::font15x28, jevois::rawimage::Font15x28, jevois::font::font16x29, jevois::rawimage::Font16x29, jevois::font::font20x38, jevois::rawimage::Font20x38, jevois::font::font5x7, jevois::rawimage::Font5x7, jevois::font::font6x10, jevois::rawimage::Font6x10, jevois::font::font7x13, jevois::rawimage::Font7x13, jevois::font::font8x13bold, jevois::rawimage::Font8x13bold, jevois::font::font9x15bold, jevois::rawimage::Font9x15bold, jevois::RawImage::height, LFATAL, jevois::RawImage::pixelsw(), and jevois::RawImage::width.
writeText() [2/2]
void jevois::rawimage::writeText (jevois::RawImage & img, std::string const & txt, int x, int y, unsigned int col, Font font = Font6x10)
在图像中写一些文字
Definition at line 690 of file RawImageOps.C.
Referenced by jevois::drawErrorImage(), jevois::rawimage::itext(), jevois::dnn::Pipeline::process(), jevois::dnn::PostProcessorClassify::report(), jevois::dnn::PostProcessorDetect::report(), jevois::dnn::PostProcessorYuNet::report(), and jevois::dnn::Pipeline::showInfo().