Python 支持函数
帮助程序促进与 Python 之间的数据传输
Functions
void jevois::python::setEngine (jevois::Engine *e)
初始化 Python、numpy，并允许 python 模块通过 JeVois Engine 发送串行输出
bool jevois::python::hasattr (boost::python::object &o, char const *name)
检查 boost::python::object 是否具有属性
template<class T >
boost::python::list jevois::python::pyVecToList (std::vector< T > const &v)
将 std::vector<T> 转换为 python 列表的辅助程序
template<class T >
std::vector< T > jevois::python::pyListToVec (boost::python::object const &lst)
将 python 列表（或任何可迭代对象）转换为 std::vector<T> 的辅助程序
template<typename T , size_t N>
std::array< T, N > jevois::python::tupleToArray (boost::python::object const &o)
辅助程序，将具有统一类型 T 元素的元组提取到 std::array 中
template<typename T , size_t N>
void jevois::python::tupleToArray (boost::python::object const &o, std::array< T, N > &arr, size_t minN=N)
辅助程序，将具有统一类型 T 元素的元组提取到 std::array 中
template<typename T >
T jevois::python::pyextract (boost::python::object const &o)
通用值提取，对于 python 知道如何提取的类型，传递给 boost::python::extract()
template<> cv::Scalar_< float > jevois::python::pyextract< cv::Scalar_< float > > (boost::python::object const &o)
cv::Scalar_<float> 的特化，从 1..4 个浮点值的元组中提取
template<> cv::Scalar_< int > jevois::python::pyextract< cv::Scalar_< int > > (boost::python::object const &o)
cv::Scalar_<int> 的特化，从 1..4 个 int 值的元组中提取
template<> cv::Point_< float > jevois::python::pyextract< cv::Point_< float > > (boost::python::object const &o)
cv::Point_<float> 的特化，从 2 个浮点值的元组中提取
template<> cv::Point_< int > jevois::python::pyextract< cv::Point_< int > > (boost::python::object const &o)
cv::Point_<int> 的特化，从 2 个 int 值的元组中提取
template<> cv::Size_< float > jevois::python::pyextract< cv::Size_< float > > (boost::python::object const &o)
cv::Size_<float> 的特化，从 2 个 float 值的元组中提取
template<> cv::Size_< int > jevois::python::pyextract< cv::Size_< int > > (boost::python::object const &o)
cv::Size_<int> 的特化，从 2 个 int 值的元组中提取
template<> ImColor jevois::python::pyextract< ImColor > (boost::python::object const &o)
ImColor 的特化，从 3..4 int 值的元组中提取（如果为 3 则 alpha=255）
template<typename T >
boost::python::object jevois::python::topyobj (T const &val)
将值转换为 python，传递到 python::object(val)
template<> boost::python::object jevois::python::topyobj (cv::Scalar_< float > const &val)
cv::Scalar<float> 的特化，返回一个有 4 个浮点元素的元组
template<> boost::python::object jevois::python::topyobj (cv::Scalar_< int > const &val)
cv::Scalar<int> 的特化，返回一个包含 4 个 int 元素的元组
template<> boost::python::object jevois::python::topyobj (cv::Point_< float > const &val)
cv::Point<float> 的特化，返回一个包含 2 个 float 元素的元组
template<> boost::python::object jevois::python::topyobj (cv::Point_< int > const &val)
cv::Point<int> 的特化，返回一个包含 2 个 int 元素的元组
template<> boost::python::object jevois::python::topyobj (cv::Size_< float > const &val)
cv::Size<float> 的特化，返回一个包含 2 个 float 元素的元组
template<> boost::python::object jevois::python::topyobj (cv::Size_< int > const &val)
对 cv::Size<int> 的特化，返回一个包含 2 个 int 元素的元组
template<> boost::python::object jevois::python::topyobj (ImColor const &val)
对 ImColor 的特化，返回一个包含 4 个 int 元素的元组
Function Documentation
hasattr()
bool jevois::python::hasattr (boost::python::object & o, char const * name)
检查 boost::python::object 是否具有属性
Definition at line 116 of file PythonSupport.C.
References o.
Referenced by jevois::dnn::NetworkPythonImpl::freeze(), jevois::dnn::PreProcessorPythonImpl::freeze(), jevois::dnn::PostProcessorPythonImpl::freeze(), jevois::dnn::NetworkPythonImpl::loadpy(), jevois::dnn::PostProcessorPythonImpl::loadpy(), jevois::dnn::PreProcessorPythonImpl::loadpy(), jevois::PythonModule::parseSerial(), jevois::PythonModule::postUninit(), jevois::PythonModule::preInit(), and jevois::PythonModule::supportedCommands().
pyextract()
template<typename T >
T jevois::python::pyextract (boost::python::object const & o)
通用值提取，对于 python 知道如何提取的类型，传递给 boost::python::extract()
pyextract< cv::Point_< float > >()
template<>
cv::Point_<float> jevois::python::pyextract< cv::Point_< float > > (boost::python::object const & o)
cv::Point_<float> 的特化，从 2 个浮点值的元组中提取
pyextract< cv::Point_< int > >()
template<>
cv::Point_<int> jevois::python::pyextract< cv::Point_< int > > (boost::python::object const & o)
cv::Point_<int> 的特化，从 2 个 int 值的元组中提取
pyextract< cv::Scalar_< float > >()
template<>
cv::Scalar_<float> jevois::python::pyextract< cv::Scalar_< float > > (boost::python::object const & o)
cv::Scalar_<float> 的特化，从 1..4 个浮点值的元组中提取
pyextract< cv::Scalar_< int > >()
template<>
cv::Scalar_<int> jevois::python::pyextract< cv::Scalar_< int > > (boost::python::object const & o)
cv::Scalar_<int> 的特化，从 1..4 个 int 值的元组中提取
pyextract< cv::Size_< float > >()
template<>
cv::Size_<float> jevois::python::pyextract< cv::Size_< float > > (boost::python::object const & o)
cv::Size_<float> 的特化，从 2 个 float 值的元组中提取
pyextract< cv::Size_< int > >()
template<>
cv::Size_<int> jevois::python::pyextract< cv::Size_< int > > (boost::python::object const & o)
cv::Size_<int> 的特化，从 2 个 int 值的元组中提取
pyextract< ImColor >()
template<>
ImColor jevois::python::pyextract< ImColor > (boost::python::object const & o)
ImColor 的特化，从 3..4 int 值的元组中提取（如果为 3 则 alpha=255）
pyListToVec()
template<class T >
std::vector<T> jevois::python::pyListToVec (boost::python::object const & lst)
将 python 列表（或任何可迭代对象）转换为 std::vector<T> 的辅助程序
pyVecToList()
template<class T >
boost::python::list jevois::python::pyVecToList (std::vector< T > const & v)
将 std::vector<T> 转换为 python 列表的辅助程序
Referenced by jevois::dnn::PreProcessorForPython::blobs(), jevois::dnn::NetworkPythonImpl::doprocess(), jevois::dnn::PostProcessorPythonImpl::process(), and jevois::dnn::PostProcessorDetectYOLOforPython::yolo().
setEngine()
void jevois::python::setEngine (jevois::Engine * e)
初始化 Python、numpy，并允许 python 模块通过 JeVois Engine 发送串行输出
此命令不适用于一般用途，只有 Engine 才应该使用它。
Definition at line 102 of file PythonSupport.C.
References jevois::python::engineForPythonModule.
Referenced by jevois::Engine::postInit().
topyobj() [1/8]
template<>
boost::python::object jevois::python::topyobj (cv::Point_< float > const & val)
cv::Point<float> 的特化，返回一个包含 2 个 float 元素的元组
topyobj() [2/8]
template<>
boost::python::object jevois::python::topyobj (cv::Point_< int > const & val)
cv::Point<int> 的特化，返回一个包含 2 个 int 元素的元组
topyobj() [3/8]
template<>
boost::python::object jevois::python::topyobj (cv::Scalar_< float > const & val)
cv::Scalar<float> 的特化，返回一个有 4 个浮点元素的元组
topyobj() [4/8]
template<>
boost::python::object jevois::python::topyobj (cv::Scalar_< int > const & val)
cv::Scalar<int> 的特化，返回一个包含 4 个 int 元素的元组
topyobj() [5/8]
template<>
boost::python::object jevois::python::topyobj (cv::Size_< float > const & val)
cv::Size<float> 的特化，返回一个包含 2 个 float 元素的元组
topyobj() [6/8]
template<>
boost::python::object jevois::python::topyobj (cv::Size_< int > const & val)
对 cv::Size<int> 的特化，返回一个包含 2 个 int 元素的元组
topyobj() [7/8]
template<>
boost::python::object jevois::python::topyobj (ImColor const & val)
对 ImColor 的特化，返回一个包含 4 个 int 元素的元组
topyobj() [8/8]
template<typename T >
boost::python::object jevois::python::topyobj (T const & val)
将值转换为 python，传递到 python::object(val)
tupleToArray() [1/2]
template<typename T , size_t N>
std::array<T, N> jevois::python::tupleToArray (boost::python::object const & o)
辅助程序，将具有统一类型 T 元素的元组提取到 std::array 中
tupleToArray() [2/2]
template<typename T , size_t N>
void jevois::python::tupleToArray (boost::python::object const & o, std::array< T, N > & arr, size_t minN = N)
辅助程序，将具有统一类型 T 元素的元组提取到 std::array 中
minN 是所需的元组元素的最小数量，允许部分元组。如果 minN<N，我们假定数组已使用默认值初始化，并且我们允许接收 小于 N 的元组，在这种情况下我们只分配数组的第一个元素。用于提取可以包含 1 到 4 个元素的 cv::Scalar 之类的东 西。