张量/神经处理网络
深度神经网络提供抽象的 Classes and utilities。提供与 OpenCV 后端（CPU、OpenCL）、张量处理单元（TPU）（例如 Coral Edge TPU）和神经处理单元（NPU）（例如 Amlogic A311D NPU）的接口。
Classes
class jevois::dnn::Network
表示神经网络的抽象类。
class jevois::dnn::NetworkHailo
在 Hailo8 神经加速器上运行的 DNN 神经网络的包装器
class jevois::dnn::NetworkNPU
在 Amlogic A311D NPU 加速器 (Verisilicon) 上运行的 DNN 神经网络的包装器
class jevois::dnn::NetworkONNX
围绕 ONNX-Runtime 神经网络的包装器
class jevois::dnn::NetworkOpenCV
围绕 OpenCV DNN 神经网络的包装器
class jevois::dnn::NetworkPython
通过 python 调用的 DNN 神经网络的包装器
class jevois::dnn::NetworkTPU
围绕 Coral TPU 神经网络的包装器
class jevois::dnn::Pipeline
神经处理管道
class jevois::dnn::PostProcessor
神经网络管道的后处理器
class jevois::dnn::PostProcessorClassify
神经网络管道的后处理器
class jevois::dnn::PostProcessorPython
神经网络管道的后处理器
class jevois::dnn::PostProcessorSegment
神经网络管道的后处理器
class jevois::dnn::PostProcessorStub
神经网络管道的后处理器
class jevois::dnn::PostProcessorYuNet
YuNet 人脸特征点检测器的后处理器
class jevois::dnn::PreProcessor
神经网络管道的预处理器
class jevois::dnn::PreProcessorBlob
神经网络管道的预处理器
class jevois::dnn::PreProcessorPython
用 python 编写的神经网络管道预处理器
Modules
用 python 编写的 DNN 相关处理器
除了用 C++ 编写 pre/net/post processors 之外，JeVois 还支持用 Python 编写。
Functions
std::map< int, std::string > jevois::dnn::readLabelsFile (std::string const &fname)
读取标签文件
std::string jevois::dnn::getLabel (std::map< int, std::string > const &labels, int id)
从 id 获取标签
int jevois::dnn::stringToRGBA (std::string const &label, unsigned char alpha=128)
根据标签名称计算颜色
void jevois::dnn::topK (float const *pfProb, float *pfMaxProb, uint32_t *pMaxClass, uint32_t outputCount, uint32_t topNum)
获取前 k 个条目及其索引
std::string jevois::dnn::shapestr (cv::Mat const &m)
从数据类型为 TYPE 的 n 维 cv::Mat 获取形式为 `nD AxBxC... TYPE` 的字符串
std::string jevois::dnn::shapestr (TfLiteTensor const *t)
从数据类型为 TYPE 的 n 维 TfLiteTensor 获取形式为 `nD AxBxC... TYPE` 的字符串
std::string jevois::dnn::shapestr (vsi_nn_tensor_attr_t const &attr)
从数据类型为 TYPE 的 n 维 NPU 张量中获取形式为 `nD AxBxC... TYPE` 的字符串
std::vector< size_t > jevois::dnn::strshape (std::string const &str)
从包含 AxBxC... 的字符串中获取 size_t 的向量
int jevois::dnn::tf2cv (TfLiteType t)
从 TensorFlow 数据类型转换为 OpenCV
vsi_nn_type_e jevois::dnn::tf2vsi (TfLiteType t)
从 TensorFlow 数据类型转换为 vsi_nn
int jevois::dnn::vsi2cv (vsi_nn_type_e t)
从NPU数据类型转换为 OpenCV
void jevois::dnn::clamp (cv::Rect &r, int width, int height)
将矩形限制在给定的图像宽度和高度内
void jevois::dnn::clamp (cv::Rect2f &r, float width, float height)
将矩形限制在给定的图像宽度和高度内
std::vector< vsi_nn_tensor_attr_t > jevois::dnn::parseTensorSpecs (std::string const &specs)
解析张量规范
cv::Mat jevois::dnn::attrmat (vsi_nn_tensor_attr_t const &attr, void *dataptr=nullptr)
从 attr 和可能的数据指针构造一个 cv::Mat。
std::vector< int > jevois::dnn::attrdims (vsi_nn_tensor_attr_t const &attr)
获取一个张量 dims 作为 int 向量，用于构造匹配的 cv::Mat
cv::Size jevois::dnn::attrsize (vsi_nn_tensor_attr_t const &attr)
以 cv::Size 格式获取张量的 (宽度, 高度) 大小，跳过其他维度
std::string jevois::dnn::attrstr (vsi_nn_tensor_attr_t const &attr)
获取描述张量规格的字符串，包括量化规格（shapestr() 未提供）
bool jevois::dnn::attrmatch (vsi_nn_tensor_attr_t const &attr, cv::Mat const &blob)
检查 cv::Mat blob 是否与 attr 的规范完全匹配
vsi_nn_tensor_attr_t jevois::dnn::tensorattr (TfLiteTensor const *t)
获取 TensorFlow Lite 张量的张量形状和类型属性
size_t jevois::dnn::softmax (float const *input, size_t const n, size_t const stride, float const fac, float *output, bool maxonly)
将 softmax 应用于浮点向量。
cv::Mat jevois::dnn::quantize (cv::Mat const &m, vsi_nn_tensor_attr_t const &attr)
根据 attr 中的量化规范从 float32 量化为定点
cv::Mat jevois::dnn::dequantize (cv::Mat const &m, vsi_nn_tensor_attr_t const &attr)
根据 attr 中的量化规范将输出反量化为 float32
size_t jevois::dnn::effectiveDims (cv::Mat const &m)
返回 cv::Mat 中非单位暗淡的数量
cv::Mat jevois::dnn::concatenate (std::vector< cv::Mat > const &tensors, int axis)
将多个张量连接成一个。
std::string jevois::dnn::shapestr (hailo_vstream_info_t const &vi)
从数据类型为 TYPE 的 n 维 Hailo 张量中获取形式为 `nD AxBxC... TYPE` 的字符串
vsi_nn_tensor_attr_t jevois::dnn::tensorattr (hailo_vstream_info_t const &vi)
获取 Hailo 张量的张量形状和类型属性
vsi_nn_type_e jevois::dnn::hailo2vsi (hailo_format_type_t t)
从 Hailo 数据类型转换为 vsi_nn
vsi_nn_type_e jevois::dnn::onnx2vsi (ONNXTensorElementDataType t)
从 ONNX-Runtime 数据类型转换为 vsi_nn
std::string jevois::dnn::shapestr (Ort::ConstTensorTypeAndShapeInfo const &ti)
从数据类型为 TYPE 的 n 维 ONNX 张量中获取形式为 `nD AxBxC... TYPE` 的字符串
vsi_nn_tensor_attr_t jevois::dnn::tensorattr (Ort::ConstTensorTypeAndShapeInfo const &ti)
获取 ONNX 运行时张量的张量形状和类型属性
Function Documentation
attrdims()
std::vector< int > jevois::dnn::attrdims (vsi_nn_tensor_attr_t const & attr)
获取一个张量 dims 作为 int 向量，用于构造匹配的 cv::Mat
Definition at line 478 of file Utils.C.
Referenced by jevois::dnn::attrmat(), jevois::dnn::NetworkHailo::load(), jevois::dnn::Network::process(), and jevois::dnn::quantize().
attrmat()
cv::Mat jevois::dnn::attrmat (vsi_nn_tensor_attr_t const & attr, void * dataptr = nullptr)
从 attr 和可能的数据指针构造一个 cv::Mat。
如果 dataptr 为 nullptr，将为 cv::Mat 分配新内存。调用者必须确保数据比 cv::Mat 更长寿，并负责最终释放数据。通 常，对于非空 dataptr，这仅用作临时 re-casting，例如，在 dequantizing 之前将接收到的张量 recast 为 Mat，然后忘 记该 Mat。
Definition at line 471 of file Utils.C.
References jevois::dnn::attrdims(), and jevois::dnn::vsi2cv().
Referenced by jevois::dnn::NetworkONNX::doprocess(), jevois::dnn::NetworkNPU::doprocess(), jevois::dnn::NetworkHailo::load(), and jevois::dnn::Network::process().
attrmatch()
bool jevois::dnn::attrmatch (vsi_nn_tensor_attr_t const & attr, cv::Mat const & blob)
检查 cv::Mat blob 是否与 attr 的规范完全匹配
Definition at line 704 of file Utils.C.
References jevois::dnn::vsi2cv().
Referenced by jevois::dnn::dequantize(), jevois::dnn::NetworkHailo::doprocess(), and jevois::dnn::NetworkNPU::doprocess().
attrsize()
cv::Size jevois::dnn::attrsize (vsi_nn_tensor_attr_t const & attr)
以 cv::Size 格式获取张量的 (宽度, 高度) 大小，跳过其他维度
Definition at line 487 of file Utils.C.
References jevois::dnn::attrstr().
Referenced by jevois::dnn::PreProcessor::blobsize(), and jevois::dnn::PreProcessorBlob::process().
attrstr()
std::string jevois::dnn::attrstr (vsi_nn_tensor_attr_t const & attr)
获取描述张量规格的字符串，包括量化规格（shapestr() 未提供）
Definition at line 512 of file Utils.C.
References jevois::to_string().
Referenced by jevois::dnn::attrsize(), jevois::dnn::NetworkHailo::doprocess(), jevois::dnn::NetworkONNX::doprocess(), jevois::dnn::NetworkNPU::doprocess(), jevois::dnn::NetworkTPU::inputShapes(), jevois::dnn::NetworkHailo::load(), jevois::dnn::NetworkTPU::outputShapes(), jevois::dnn::PreProcessorPythonImpl::process(), and jevois::dnn::PreProcessorBlob::process().
clamp() [1/2]
void jevois::dnn::clamp (cv::Rect & r, int width, int height)
将矩形限制在给定的图像宽度和高度内
Definition at line 367 of file Utils.C.
Referenced by jevois::dnn::PostProcessorDetect::process(), and jevois::dnn::PostProcessorYuNet::process().
clamp() [2/2]
void jevois::dnn::clamp (cv::Rect2f & r, float width, float height)
将矩形限制在给定的图像宽度和高度内
Definition at line 377 of file Utils.C.
concatenate()
cv::Mat jevois::dnn::concatenate (std::vector< cv::Mat > const & tensors, int axis)
将多个张量连接成一个。
对于第一个维度，Axis 可能从 0 开始为正（当从左到右读取 dims 时），对于最后一个维度，Axis 可能从 -1 开始为负。例 如，对于 10x20x30 张量，Axis 0 的大小为 10，也是 Axis -3，Axis 1 的大小为 20，也是 Axis -2，Axis 2 的大小为 30， 也是 Axis -1。输入张量必须都有相同的维度数、相同的像素类型，并且除要连接的维度之外的所有维度的大小必须匹配。
Definition at line 842 of file Utils.C.
References jevois::cvBytesPerPix(), jevois::cvtypestr(), and LFATAL.
dequantize()
cv::Mat jevois::dnn::dequantize (cv::Mat const & m, vsi_nn_tensor_attr_t const & attr)
根据 attr 中的量化规范将输出反量化为 float32
attr 应具有 m 的类型和量化细节，返回的张量为 float32
Definition at line 793 of file Utils.C.
References jevois::dnn::attrmatch(), LFATAL, and jevois::dnn::shapestr().
Referenced by jevois::dnn::NetworkHailo::doprocess(), and jevois::dnn::NetworkNPU::doprocess().
effectiveDims()
size_t jevois::dnn::effectiveDims (cv::Mat const & m)
返回 cv::Mat 中非单位暗淡的数量
例如，对于大小为 1x1x224x224 的 4D Mat，返回 2，因为它实际上是一个 224x224 的 2D 数组
Definition at line 832 of file Utils.C.
getLabel()
std::string jevois::dnn::getLabel (std::map< int, std::string > const & labels, int id)
从 id 获取标签
Definition at line 68 of file Utils.C.
References jevois::to_string().
Referenced by jevois::dnn::PostProcessorClassify::process(), and jevois::dnn::PostProcessorDetect::process().
hailo2vsi()
vsi_nn_type_e jevois::dnn::hailo2vsi (hailo_format_type_t t)
从 Hailo 数据类型转换为 vsi_nn
Definition at line 353 of file Utils.C.
References jevois::to_string().
Referenced by jevois::dnn::tensorattr().
onnx2vsi()
vsi_nn_type_e jevois::dnn::onnx2vsi (ONNXTensorElementDataType t)
从 ONNX-Runtime 数据类型转换为 vsi_nn
Definition at line 208 of file Utils.C.
References jevois::to_string().
Referenced by jevois::dnn::tensorattr().
parseTensorSpecs()
std::vector< vsi_nn_tensor_attr_t > jevois::dnn::parseTensorSpecs (std::string const & specs)
解析张量规范
Definition at line 387 of file Utils.C.
References jevois::split(), and jevois::dnn::strshape().
Referenced by jevois::dnn::NetworkPython::inputShapes(), jevois::dnn::NetworkTPU::inputShapes(), jevois::dnn::NetworkOpenCV::inputShapes(), jevois::dnn::NetworkNPU::inputShapes(), jevois::dnn::NetworkNPU::load(), jevois::dnn::Network::onParamChange(), jevois::dnn::NetworkPython::outputShapes(), jevois::dnn::NetworkOpenCV::outputShapes(), jevois::dnn::NetworkTPU::outputShapes(), and jevois::dnn::NetworkNPU::outputShapes().
quantize()
cv::Mat jevois::dnn::quantize (cv::Mat const & m, vsi_nn_tensor_attr_t const & attr)
根据 attr 中的量化规范从 float32 量化为定点
Definition at line 718 of file Utils.C.
References jevois::dnn::attrdims(), LFATAL, jevois::dnn::shapestr(), and jevois::dnn::vsi2cv().
Referenced by jevois::dnn::PreProcessorBlob::process().
readLabelsFile()
std::map< int, std::string > jevois::dnn::readLabelsFile (std::string const & fname)
读取标签文件
允许两种格式：每行一个类名，或每个文件一个类号后跟一个类名。
Definition at line 25 of file Utils.C.
References LERROR, LFATAL, LINFO, and jevois::replaceStringAll().
shapestr() [1/5]
std::string jevois::dnn::shapestr (cv::Mat const & m)
从数据类型为 TYPE 的 n 维 cv::Mat 获取形式为 `nD AxBxC... TYPE` 的字符串
Definition at line 105 of file Utils.C.
References jevois::cvtypestr(), and jevois::to_string().
Referenced by jevois::dnn::dequantize(), jevois::dnn::NetworkTPU::doprocess(), jevois::dnn::NetworkONNX::doprocess(), jevois::dnn::NetworkHailo::doprocess(), jevois::dnn::NetworkNPU::doprocess(), jevois::GUIhelper::drawPoly(), jevois::dnn::NetworkTPU::load(), jevois::dnn::NetworkONNX::load(), jevois::dnn::PostProcessorSegment::process(), jevois::dnn::PostProcessorDetect::process(), jevois::dnn::PreProcessorBlob::process(), jevois::dnn::Pipeline::process(), jevois::dnn::Network::process(), jevois::dnn::quantize(), jevois::dnn::PreProcessor::sendreport(), jevois::dnn::shapestr(), jevois::dnn::Pipeline::showDataPeekWindow(), and jevois::dnn::PostProcessorDetectYOLO::yolo().
shapestr() [2/5]
std::string jevois::dnn::shapestr (hailo_vstream_info_t const & vi)
从数据类型为 TYPE 的 n 维 Hailo 张量中获取形式为 `nD AxBxC... TYPE` 的字符串
Definition at line 252 of file Utils.C.
References jevois::dnn::shapestr(), and jevois::dnn::tensorattr().
shapestr() [3/5]
std::string jevois::dnn::shapestr (Ort::ConstTensorTypeAndShapeInfo const & ti)
从数据类型为 TYPE 的 n 维 ONNX 张量中获取形式为 `nD AxBxC... TYPE` 的字符串
Definition at line 174 of file Utils.C.
References jevois::to_string().
shapestr() [4/5]
std::string jevois::dnn::shapestr (TfLiteTensor const * t)
从数据类型为 TYPE 的 n 维 TfLiteTensor 获取形式为 `nD AxBxC... TYPE` 的字符串
Definition at line 115 of file Utils.C.
References jevois::to_string().
shapestr() [5/5]
std::string jevois::dnn::shapestr (vsi_nn_tensor_attr_t const & attr)
从数据类型为 TYPE 的 n 维 NPU 张量中获取形式为 `nD AxBxC... TYPE` 的字符串
Definition at line 144 of file Utils.C.
References jevois::to_string().
softmax()
size_t jevois::dnn::softmax (float const * input, size_t const n, size_t const stride, float const fac, float * output, bool maxonly)
将 softmax 应用于浮点向量。
n 是要处理的元素数量，stride 是数组中从一个元素到下一个元素的增量。因此数组的大小应为 n * stride。返回得分最高 的元素在 [0..n*stride] 中的索引。如果 maxonly 为 true，则仅输出 [returned index] 有效。
Definition at line 668 of file Utils.C.
References LFATAL.
Referenced by jevois::dnn::PostProcessorClassify::process().
stringToRGBA()
int jevois::dnn::stringToRGBA (std::string const & label, unsigned char alpha = 128)
根据标签名称计算颜色
Definition at line 76 of file Utils.C.
Referenced by jevois::dnn::PostProcessorDetect::report().
strshape()
std::vector< size_t > jevois::dnn::strshape (std::string const & str)
从包含 AxBxC... 的字符串中获取 size_t 的向量
Definition at line 277 of file Utils.C.
References jevois::split().
Referenced by jevois::dnn::parseTensorSpecs(), and jevois::dnn::Network::process().
tensorattr() [1/3]
vsi_nn_tensor_attr_t jevois::dnn::tensorattr (hailo_vstream_info_t const & vi)
获取 Hailo 张量的张量形状和类型属性
Definition at line 602 of file Utils.C.
References jevois::dnn::hailo2vsi(), and jevois::to_string().
tensorattr() [2/3]
vsi_nn_tensor_attr_t jevois::dnn::tensorattr (Ort::ConstTensorTypeAndShapeInfo const & ti)
获取 ONNX 运行时张量的张量形状和类型属性
Definition at line 234 of file Utils.C.
References jevois::dnn::onnx2vsi().
tensorattr() [3/3]
vsi_nn_tensor_attr_t jevois::dnn::tensorattr (TfLiteTensor const * t)
获取 TensorFlow Lite 张量的张量形状和类型属性
Definition at line 563 of file Utils.C.
References LFATAL, and jevois::dnn::tf2vsi().
Referenced by jevois::dnn::NetworkTPU::inputShapes(), jevois::dnn::NetworkONNX::load(), jevois::dnn::NetworkHailo::load(), jevois::dnn::NetworkTPU::outputShapes(), and jevois::dnn::shapestr().
tf2cv()
int jevois::dnn::tf2cv (TfLiteType t)
从 TensorFlow 数据类型转换为 OpenCV
Definition at line 286 of file Utils.C.
Referenced by jevois::dnn::NetworkTPU::doprocess().
tf2vsi()
vsi_nn_type_e jevois::dnn::tf2vsi (TfLiteType t)
从 TensorFlow 数据类型转换为 vsi_nn
Definition at line 330 of file Utils.C.
Referenced by jevois::dnn::tensorattr().
topK()
void jevois::dnn::topK (float const * pfProb, float * pfMaxProb, uint32_t * pMaxClass, uint32_t outputCount, uint32_t topNum)
获取前 k 个条目及其索引
Definition at line 85 of file Utils.C.
Referenced by jevois::dnn::PostProcessorClassify::process().
vsi2cv()
int jevois::dnn::vsi2cv (vsi_nn_type_e t)
从NPU数据类型转换为 OpenCV
Definition at line 308 of file Utils.C.
References jevois::to_string().
Referenced by jevois::dnn::attrmat(), jevois::dnn::attrmatch(), jevois::dnn::NetworkONNX::doprocess(), jevois::dnn::PreProcessorBlob::process(), and jevois::dnn::quantize().