src/Apps/jevois-camtest.C File Reference
#include <jevois/Core/Camera.H>
#include <jevois/Debug/Log.H>
#include <string.h>
#include <linux/videodev2.h>
#include <opencv2/core/core.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/imgcodecs.hpp>
#include <jevois/Util/Utils.H>
#include <sys/mman.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
Macros
#define USE_RAW_CAMERA
#define NB_BUFFER 4
Functions
int main (int argc, char const *argv[])
从相机抓取视频帧，并将它们作为 PNG 文件写入磁盘
Macro Definition Documentation
NB_BUFFER
#define NB_BUFFER 4
Definition at line 36 of file jevois-camtest.C.
USE_RAW_CAMERA
#define USE_RAW_CAMERA
Definition at line 33 of file jevois-camtest.C.
Function Documentation
main()
int main (int argc, char const * argv[])
从相机抓取视频帧，并将它们作为 PNG 文件写入磁盘
Definition at line 45 of file jevois-camtest.C.
References jevois::RawImage::buf, jevois::VideoMapping::cfmt, jevois::VideoMapping::cfps, jevois::VideoMapping::ch, jevois::VideoMapping::cw, jevois::Camera::done(), jevois::Camera::get(), jevois::RawImage::height, LFATAL, LINFO, jevois::logEnd(), jevois::logLevel, NB_BUFFER, jevois::Camera::setFormat(), jevois::Camera::streamOff(), jevois::Camera::streamOn(), jevois::to_string(), jevois::RawImage::width, and XIOCTL.