src/Apps/jevois-restore-console.C File Reference
#include <jevois/Util/Console.H>
#include <jevois/Debug/Log.H>
#include <linux/input.h>
#include <linux/kd.h>
#include <linux/keyboard.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <cctype>
Functions
int main (int, char const **)
在 jevoispro-daemon 剧烈崩溃后恢复控制台操作
Function Documentation
main()
int main (int , char const **)
在 jevoispro-daemon 剧烈崩溃后恢复控制台操作
Definition at line 32 of file jevois-restore-console.C.
References jevois::getActiveTTY(), jevois::getConsoleFd(), jevois::logEnd(), jevois::logLevel, and jevois::unMuteKeyboard().