src/Apps/jevois-module-param.C File Reference
#include <jevois/Debug/Log.H>
#include <jevois/Core/VideoMapping.H>
#include <fstream>
#include <sstream>
#include <iostream>
#include <memory>
Functions
int main (int argc, char const *argv[])
解析 videomappings.cfg 并输出要传递给 jevois 内核模块的字符串
Function Documentation
main()
int main (int argc, char const * argv[])
解析 videomappings.cfg 并输出要传递给 jevois 内核模块的字符串
创建这个小应用程序是为了通过使用完全相同的配置文件解析和排序代码（在 VideoMapping 中）来确保内核驱动程序和用户代码之间的 完美一致性。
Definition at line 28 of file jevois-module-param.C.
References jevois::VideoMapping::fpsToUvc(), JEVOIS_ENGINE_CONFIG_FILE, LFATAL, jevois::logEnd(), jevois::logLevel, and jevois::videoMappingsFromStream().