src/Apps/jevois-add-videomapping.C File Reference
#include <jevois/Debug/Log.H>
#include <jevois/Core/VideoMapping.H>
#include <jevois/Util/Utils.H>
#include <fstream>
#include <iostream>
#include <sstream>
Functions
int main (int argc, char const *argv[])
向 videomappings.cfg 添加新的映射并跳过重复项
Function Documentation
main()
int main (int argc, char const * argv[])
向 videomappings.cfg 添加新的映射并跳过重复项
Definition at line 28 of file jevois-add-videomapping.C.
References jevois::VideoMapping::hasSameSpecsAs(), JEVOIS_ENGINE_CONFIG_FILE, LFATAL, LINFO, jevois::logEnd(), jevois::logLevel, jevois::VideoMapping::modulename, jevois::VideoMapping::str(), jevois::VideoMapping::vendor, jevois::videoMappingsFromStream(), and jevois::VideoMapping::wdr.