jevois::rawimage Namespace Reference
用于 RawImage 转换、处理、绘制的函数
Enumerations
enum Font {
Font5x7,
Font6x10,
Font7x13,
Font8x13bold,
Font9x15bold,
Font10x20,
Font11x22,
Font12x22,
Font14x26,
Font15x28,
Font16x29,
Font20x38
 }
可用于 writeText() 的字体
Functions
cv::Mat cvImage (RawImage const &src)
从现有 RawImage 数据创建 OpenCV 图像，共享像素内存而不是复制它
cv::Mat convertToCvGray (RawImage const &src)
将 RawImage 转换为 OpenCV，从任何 RawImage 源像素执行颜色转换为 OpenCV 灰度字节
cv::Mat convertToCvBGR (RawImage const &src)
将 RawImage 转换为 OpenCV，从任何 RawImage 源像素执行颜色转换为 OpenCV BGR 字节
cv::Mat convertToCvRGB (RawImage const &src)
将 RawImage 转换为 OpenCV，从任何 RawImage 源像素到 OpenCV RGB 字节进行颜色转换
cv::Mat convertToCvRGBA (RawImage const &src)
将 RawImage 转换为 OpenCV，从任何 RawImage 源像素到 OpenCV RGB-A 字节进行颜色转换
void byteSwap (RawImage &img)
交换 RawImage 中的字节对
void paste (RawImage const &src, RawImage &dest, int dx, int dy)
将一张图像粘贴到另一张相同像素类型的图像中
void pasteGreyToYUYV (cv::Mat const &src, RawImage &dest, int dx, int dy)
将灰度字节图像粘贴到 YUYV 图像中
void pasteBGRtoYUYV (cv::Mat const &src, RawImage &dst, int dx, int dy)
将 BGR 字节图像粘贴到 YUYV 图像中
void pasteRGBtoYUYV (cv::Mat const &src, RawImage &dst, int dx, int dy)
将 RGB 字节图像粘贴到 YUYV 图像中
void roipaste (RawImage const &src, int x, int y, unsigned int w, unsigned int h, RawImage &dest, int dx, int dy)
将图像中的 ROI 粘贴到相同像素类型的另一个图像中
void drawDisk (RawImage &img, int x, int y, unsigned int rad, unsigned int col)
在 YUYV 图像中绘制一个圆盘 disk
void drawCircle (RawImage &img, int x, int y, unsigned int rad, unsigned int thick, unsigned int col)
在YUYV图像中绘制一个圆圈
bool clipLine (int wxmin, int wymin, int wxmax, int wymax, int &x1, int &y1, int &x2, int &y2)
剪裁一条线以适合 viewport [wxmin...wxmax[ x [wymin...wymax]
void drawLine (RawImage &img, int x1, int y1, int x2, int y2, unsigned int thick, unsigned int col)
在 YUYV 图像中绘制一条线
void drawRect (RawImage &img, int x, int y, unsigned int w, unsigned int h, unsigned int thick, unsigned int col)
在 YUYV 图像中绘制一个矩形
void drawRect (RawImage &img, int x, int y, unsigned int w, unsigned int h, unsigned int col)
在 YUYV 图像中绘制矩形
void drawFilledRect (RawImage &img, int x, int y, unsigned int w, unsigned int h, unsigned int col)
在 YUYV 图像中绘制填充矩形
void writeText (RawImage &img, std::string const &txt, int x, int y, unsigned int col, Font font=Font6x10)
在图像中写一些文字
void writeText (RawImage &img, char const *txt, int x, int y, unsigned int col, Font font=Font6x10)
在图像中写一些文字
int itext (RawImage &img, std::string const &txt, int y=3, unsigned int col=jevois::yuyv::White, Font font=Font6x10)
在图像中简写一些文本，x = 3 并返回下一个 y 位置
int itext (RawImage &img, char const *txt, int y=3, unsigned int col=jevois::yuyv::White, Font font=Font6x10)
在图像中简写一些文本，x = 3 并返回下一个 y 位置
void convertCvBGRtoRawImage (cv::Mat const &src, RawImage &dst, int quality)
将 BGR cv::Mat 转换为具有已分配像素和像素类型的 RawImage
void convertCvRGBtoRawImage (cv::Mat const &src, RawImage &dst, int quality)
将 RGB cv::Mat 转换为具有已分配像素和像素类型的 RawImage
void convertCvRGBAtoRawImage (cv::Mat const &src, RawImage &dst, int quality)
使用已分配的像素和像素类型将 RGBA cv::Mat 转换为 RawImage
void convertCvGRAYtoRawImage (cv::Mat const &src, RawImage &dst, int quality)
使用已分配的像素和像素类型将灰色 cv::Mat 转换为 RawImage
void unpackCvRGBAtoGrayRawImage (cv::Mat const &src, RawImage &dst)
将 RGBA cv::Mat 分割成 4 倍高的灰色 RawImage，其中已分配像素
void hFlipYUYV (RawImage &img)
水平翻转 YUYV RawImage 同时保留颜色信息
void convertCvRGBtoCvYUYV (cv::Mat const &src, cv::Mat &dst)
OpenCV 没有在 cvtColor() 中提供从 RGB 到 YUYV 的转换，因此此函数提供它
void convertCvBGRtoCvYUYV (cv::Mat const &src, cv::Mat &dst)
OpenCV 没有在 cvtColor() 中提供从 RGB 到 YUYV 的转换，因此此函数提供它
void convertCvGRAYtoCvYUYV (cv::Mat const &src, cv::Mat &dst)
OpenCV 没有在 cvtColor() 中提供从 RGB 到 YUYV 的转换，因此此函数提供它
void convertCvRGBAtoCvYUYV (cv::Mat const &src, cv::Mat &dst)
OpenCV 没有在 cvtColor() 中提供从 RGB 到 YUYV 的转换，因此此函数提供它
void convertBayerToYUYV (RawImage const &src, RawImage &dst)
从 Bayer 转换为 YUYV，仅供 Camera 类内部使用
void convertGreyToYUYV (RawImage const &src, RawImage &dst)
从灰色（单色）转换为 YUYV，仅供 Camera 类内部使用
Function Documentation
convertBayerToYUYV()
void jevois::rawimage::convertBayerToYUYV (RawImage const & src, RawImage & dst)
从 Bayer 转换为 YUYV，仅供 Camera 类内部使用
Definition at line 1629 of file RawImageOps.C.
References cvImage(), jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, jevois::RawImage::pixelsw(), and jevois::RawImage::width.
Referenced by jevois::CameraDevice::get().
convertGreyToYUYV()
void jevois::rawimage::convertGreyToYUYV (RawImage const & src, RawImage & dst)
从灰色（单色）转换为 YUYV，仅供 Camera 类内部使用
Definition at line 1649 of file RawImageOps.C.
References cvImage(), jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, and jevois::RawImage::width.
Referenced by jevois::CameraDevice::get().
convertToCvGray()
cv::Mat jevois::rawimage::convertToCvGray (jevois::RawImage const & src)
将 RawImage 转换为 OpenCV，从任何 RawImage 源像素执行颜色转换为 OpenCV 灰度字节
Definition at line 246 of file RawImageOps.C.
References cvImage(), jevois::RawImage::fmt, jevois::RawImage::height, LFATAL, and jevois::RawImage::width.
Referenced by jevois::InputFrame::getCvGRAY(), and jevois::InputFrame::getCvGRAYp().
itext() [1/2]
int jevois::rawimage::itext (RawImage & img, char const * txt, int y = 3, unsigned int col = jevois::yuyv::White, Font font = Font6x10)
在图像中简写一些文本，x = 3 并返回下一个 y 位置
Definition at line 780 of file RawImageOps.C.
References Font10x20, Font11x22, Font12x22, Font14x26, Font15x28, Font16x29, Font20x38, Font5x7, Font6x10, Font7x13, Font8x13bold, Font9x15bold, LFATAL, and writeText().
itext() [2/2]
int jevois::rawimage::itext (RawImage & img, std::string const & txt, int y = 3, unsigned int col = jevois::yuyv::White, Font font = Font6x10)
在图像中简写一些文本，x = 3 并返回下一个 y 位置
Definition at line 774 of file RawImageOps.C.
Referenced by jevois::GUIhelper::itext().
unpackCvRGBAtoGrayRawImage()
void jevois::rawimage::unpackCvRGBAtoGrayRawImage (cv::Mat const & src, RawImage & dst)
将 RGBA cv::Mat 分割成 4 倍高的灰色 RawImage，其中已分配像素
Definition at line 1348 of file RawImageOps.C.
References jevois::async(), jevois::cvtypestr(), jevois::RawImage::fmt, h, jevois::RawImage::height, LFATAL, jevois::RawImage::pixelsw(), and jevois::RawImage::width.