jevois Namespace Reference
所有 JeVois 类和函数的主命名空间
有关更多详细信息，请参阅 主题。
Namespaces
 coords
用于将坐标从相机分辨率转换为标准坐标的辅助函数的命名空间
 details
Details that do not affect users of JeVois code.
 dnn
深度神经网络
 font
Fonts available for drawing text strings into RawImage.
 python
Python 相关的帮助程序和函数
 rawimage
用于 RawImage 转换、处理、绘制的函数
 rgb565
辅助 RGB565 颜色
 shader
OpenGL shaders for video rendering.
 yuyv
辅助 YUYV 颜色
Classes
class BoundedBuffer
线程安全同步生产者/消费者队列
class Camera
JeVois camera driver class - 从 Video4Linux 相机传感器抓取帧
class CameraCalibration
用于相机校准的辅助类，允许某些模块计算物体的 3D 位置
class CameraDevice
附件类，用于保存与 V4L2 相机设备相关的所有数据
class ChatBox
A simple helper class for a chat box rendered in ImGui.
class Component
模型层次结构的组成部分。
struct DMPdata
DMP 数据（数字运动处理器）
class DynamicLoader
用于打开共享对象 (.so) 文件并加载其中包含的函数的类
class DynamicParameter
运行时添加到组件的动态参数
struct EditorItem
Helper class to represent a GUIeditor file in a pull-down menu.
class Engine
JeVois processing engine - 从相机传感器获取图像，对其进行处理，并通过 USB 发送结果。
class Gadget
JeVois 小工具驱动程序 - 向通过 USB 连接的主机计算机公开 uvcvideo 接口
class GPUimage
Class to hold a GPUtexture, GPUprogram, and other data associated with rendering an image in OpenGL.
class GPUprogram
Simple class to load and compile some OpenGL-ES program.
class GPUshader
Simple class to load and compile some OpenGL-ES shader code.
class GPUtexture
Simple class to hold an OpenGL texture.
class GPUtextureDmaBuf
Simple class to hold an OpenGL texture with in-GPU pixel format conversion and DMABUF acceleration.
class GUIconsole
Simple console with coloring and completion.
class GUIeditor
Editor panel for JeVois-Pro GUI.
class GUIhelper
Helper class to assist modules in creating graphical and GUI elements.
class GUIhelperPython
包装 GUIhelper 以供 Python 使用
class GUIserial
Simple class to monitor a serial port in the JeVois-Pro GUI.
class ICM20948
TDK InvenSense ICM-20948 9DOF IMU 高级驱动程序
class ImGuiBackend
Backend for ImGui on JeVois-Pro.
class ImGuiBackendMALI
BackendMALI for ImGui on JeVois-Pro.
class ImGuiImage
Wrapper for an image that can be rendered into ImGui.
class IMU
ICM20948 惯性测量单元 (IMU) 的抽象接口
struct IMUdata
IMU 数据
class IMUi2c
具有与摄像头传感器共享的 I2C 接口的 IMU，例如 JeVois-A33 AR0135 摄像头传感器板上的 ICM20948
struct IMUrawData
原始 IMU 数据
class IMUspi
具有 SPI 接口的 IMU，例如 JeVois-Pro IMX290 摄像头传感器板上的 ICM20948 IMU
class InputFrame
原始相机输入帧周围的异常安全包装器
class InputFramePython
包装 Python 使用的 InputFrame
class JpegCompressor
turbojpeg 压缩器的简单单例包装器
class Log
Logger 类
class Manager
组件对象层次结构的管理器
class Module
视觉处理模块的虚基类
class MovieInput
class MovieOutput
使用 OpenCV 视频编码将视频输出到电影文件
struct ObjDetect
一个用于存储对象检测结果的简单结构
struct ObjReco
一个用于存储对象识别结果的简单结构
class OutputFrame
围绕要通过 USB 发送的原始图像的异常安全包装器
class OutputFramePython
Python 使用的 OutputFrame 包装器
class Parameter< Param, Tail ... >
附加到组件的一组参数。
class ParameterBase
Base class for Parameter.
struct ParameterCategory
多个 ParameterDef 定义可以属于的类别
class ParameterCore
Component 的可变参数，核心类
class ParameterDef
参数定义
class ParameterDefBase
参数定义的基类
class ParameterRegistry
与组件相关的所有参数的简单注册表
class ParameterSummary
ParameterSummary 提供有关参数的摘要
class Profiler
简单的 profiler 类
class PythonModule
包装器模块允许用户开发用 Python 编写的新模块
class PythonParameter
python 中 jevois 参数的包装器
class PythonWrapper
辅助类，用于从 C++ 运行 Python 代码
class Range
通用 Range 类
class RawImage
来自 V4L2 Camera 和/或发送到 USB Gadget 的原始图像
class Semaphore
一个简单的信号量
class Serial
串行端口接口
class Singleton
一个通用的 singleton 类，用于强制一个对象的单个实例
class StdioInterface
基于字符串的用户界面，在主机上使用的简单终端输入/输出
class StdModule
支持标准化串行消息的模块的基类
class StepRange
具有 step 的通用 range 类
class ThreadPool
具有 CPU 亲和力的线程池
class timed_lock_guard
在 std::timed_mutex 上获取锁对象，或在等待 1 秒后 LFATAL
class Timer
简单计时器类
class TimerOne
简单的一次性计时器类
class UserInterface
基于字符串的用户界面的抽象基类
class ValidValuesSpecBase
用于为类型指定一组有效值的基类
class ValidValuesSpecList
有限列表有效值规范，构造时列出的所有内容均有效，其他任何内容均无效
class ValidValuesSpecNone
Open/None 有效值规范，T 可以采用的任何值都有效
class ValidValuesSpecRange
基于范围的有效值规范，包含边界
class ValidValuesSpecRegex
基于正则表达式的有效值规范，与正则表达式匹配的所有内容均被视为有效
class ValidValuesSpecStepRange
基于 StepRange 的有效值规范，包含边界
class VideoBuf
V4L2 视频缓冲区，保存在 shared_ptr 中
class VideoBuffers
V4L2 视频帧（相机或小工具）的缓冲区集合，带有与 MMAP 区域挂钩的钩子
class VideoDisplayBackend
Backend for VideoDisplay on JeVois-Pro.
class VideoDisplayBackendMALI
Backend for VideoDisplay on JeVois-Pro host using MALI.
class VideoDisplayGL
视频输出到本地屏幕
class VideoDisplayGUI
使用基本 GUI 将视频输出到本地屏幕
class VideoInput
视频输入的基类，将派生为 Camera 和 MovieInput
struct VideoMapping
用于保存处理 Engine 的视频映射定义的简单结构
class VideoOutput
视频输出的基类。Gadget、MovieOutput、VideoDisplay 和 VideoOutputNone 均从其派生
class VideoOutputNone
class Watchdog
简单的看门狗类
Typedefs
using OptGUIhelper = GUIhelper
Enumerations
enum EditorSaveAction
Helper enum for actions to execute after saving a config file.
enum BlockingBehavior { BlockingBehavior::Block,
BlockingBehavior::Throw
 }
尝试无法立即完成的操作时的行为
Functions
template<typename T >
void paramValToString (T const &val, std::string &result)
将 T 转换为字符串，供 jevois::Parameter 使用
template<> void paramValToString< unsigned char > (unsigned char const &val, std::string &result)
将 T 转换为机器可读的字符串，专门将无符号字符转换为数字，而不是字符
template<typename T >
void paramStringToVal (std::string const &valstring, T &result)
从字符串到 T 的机器可读转换，用于 jevois::Parameter
template<typename Q >
void paramValToString (std::vector< Q > const &val, std::string &result)
机器可读的字符串输出，用于 ​​jevois::Parameter：输出 [Element1, Element2, ...]
template<typename Q >
void paramStringToVal (std::string const &valstring, std::vector< Q > &result)
来自字符串的机器可读输入，用于 jevois::Parameter：读取 [Element1, Element2, ...]
template<typename F , typename S >
void paramValToString (std::pair< F, S > const &val, std::string &result)
机器可读的输出为字符串，用于 jevois::Parameter: 输出 first second
template<typename F , typename S >
void paramStringToVal (std::string const &valstring, std::pair< F, S > &result)
来自字符串的机器可读输入，用于 jevois::Parameter：读取 first second
template<typename T >
void paramValToString (cv::Point_< T > const &val, std::string &result)
机器可读的输出为字符串，用于 jevois::Parameter: 输出 x y
template<typename T >
void paramStringToVal (std::string const &valstring, cv::Point_< T > &result)
来自字符串的机器可读输入，用于 jevois::Parameter：读取 x y
template<typename T >
void paramValToString (cv::Size_< T > const &val, std::string &result)
机器可读的输出为字符串，用于 jevois::Parameter: 输出 width height
template<typename T >
void paramStringToVal (std::string const &valstring, cv::Size_< T > &result)
来自字符串的机器可读输入，用于 jevois::Parameter：读取 width height
template<typename T >
void paramValToString (cv::Scalar_< T > const &val, std::string &result)
机器可读的输出为字符串，用于 jevois::Parameter: 输出 r g b a
template<typename T >
void paramStringToVal (std::string const &valstring, cv::Scalar_< T > &result)
来自字符串的机器可读输入，用于 jevois::Parameter：读取 r g b a 或子集模板
template<> void paramValToString< ImColor > (ImColor const &val, std::string &result)
机器可读输出为字符串，用于 jevois::Parameter: 输出 R G B A，每个 0..255
template<> void paramStringToVal< ImColor > (std::string const &valstring, ImColor &result)
来自字符串的机器可读输入，用于 jevois::Parameter：读取 R G B A，每个 0..255
template<typename K , typename V >
void paramValToString (std::map< K, V > const &val, std::string &result)
机器可读输出到字符串，用于 jevois::Parameter：输出 [Key1:Value1, Key2:Value2, ...]
template<typename K , typename V >
void paramStringToVal (std::string const &valstring, std::map< K, V > &result)
来自字符串的机器可读输入，用于 jevois::Parameter：读取 [Key1:Value1, Key2:Value2, ...]
template<> void paramValToString< bool > (bool const &val, std::string &result)
将 bool 转换为机器可读的字符串，以便在 jevois::Parameter 中使用；
template<> void paramStringToVal< bool > (std::string const &valstring, bool &result)
从字符串到布尔值的机器可读转换，用于 jevois::Parameter
template<> void paramValToString< std::string > (std::string const &val, std::string &result)
机器可读的字符串到字符串的转换，用于 jevois::Parameter
template<> void paramStringToVal< std::string > (std::string const &valstring, std::string &result)
机器可读的字符串到字符串的转换，用于 jevois::Parameter
JEVOIS_DEFINE_ENUM_CLASS (CameraSensor,(any)(imx290)(os08a10)(ar0234))
不同传感器型号的枚举
JEVOIS_DEFINE_ENUM_CLASS (CameraLens,(standard)(custom1)(custom2)(custom3)(custom4)(custom5))
bool sensorSupportsFormat (CameraSensor s, VideoMapping const &m)
检查传感器是否支持给定的分辨率和帧速率
bool sensorHasIMU (CameraSensor s)
检查传感器是否有 IMU（惯性测量单元）
void sensorPrepareSetFormat (CameraSensor s, VideoMapping const &m, unsigned int &capw, unsigned int &caph, int &preset)
加载传感器预设（仅限 JeVois-Pro）并返回原生传感器抓取尺寸（裁剪和/或缩放时）
size_t DMPpacketSize (unsigned short ctl1, unsigned short ctl2)
辅助函数根据选项确定 DMP 数据包大小
std::vector< VideoMapping > videoMappingsFromStream (CameraSensor s, std::istream &is, size_t &defidx, bool checkso, bool hasgui)
解析配置文件中的所有映射，并指出哪一个是默认的
void warnAndRethrowException (std::string const &prefix=``)
便捷函数用于捕获异常、发出一些 LERROR（取决于类型）并重新抛出它
std::string warnAndIgnoreException (std::string const &prefix=``)
便捷函数用于捕获异常、发出一些 LERROR（取决于类型）并忽略它
void warnAndRethrowParamCallbackException (std::string const &descriptor, std::string const &strval)
参数回调异常的便捷函数
void drawErrorImage (std::string const &errmsg, RawImage &videoerrimg)
将错误消息显示到 RawImage 中
void logSetEngine (Engine *e)
设置引擎，以便所有日志消息都转发到其串行端口
void logEnd ()
终止日志服务
std::string getPythonExceptionString (boost::python::error_already_set &)
Python 异常转换为字符串，以便我们可以将回溯打印到我们的 serlog stream.
std::string getSysInfoCPU ()
获取 CPU 信息： frequency, thermal, load
std::string getSysInfoMem ()
Get memory info.
std::string getSysInfoVersion ()
Get O.S. version info.
size_t getNumInstalledTPUs ()
获取此系统上存在的 Coral TPU 数量
size_t getNumInstalledVPUs ()
获取此系统上存在的 Myriad-X VPU 数量
size_t getNumInstalledNPUs ()
获取此系统上存在的 JeVois-Pro NPU 数量
size_t getNumInstalledSPUs ()
获取此系统上存在的 Hailo8 SPU 数量
int getFanSpeed ()
获取风扇速度百分比，仅在 JeVois-Pro 平台上有意义，其他所有平台均返回 0
std::string opengl_error (int err)
Function to write OpenGL errors in clear witout requiring GLUT.
void convertYUYVtoYUV422 (unsigned char const *src, int width, int height, unsigned char *dst)
辅助从打包的 YUYV 转换为平面 YUV422
unsigned long compressBGRtoJpeg (unsigned char const *src, int width, int height, unsigned char *dst, int quality=75)
将原始像素缓冲区压缩为 jpeg
void compressBGRtoJpeg (cv::Mat const &src, RawImage &dst, int quality=75)
将 BGR cv::Mat 压缩为输出 JPEG jevois::RawImage
unsigned long compressRGBtoJpeg (unsigned char const *src, int width, int height, unsigned char *dst, int quality=75)
将原始像素缓冲区压缩为 jpeg
void compressRGBtoJpeg (cv::Mat const &src, RawImage &dst, int quality=75)
将 RGB cv::Mat 压缩为输出 JPEG jevois::RawImage
unsigned long compressRGBAtoJpeg (unsigned char const *src, int width, int height, unsigned char *dst, int quality=75)
将原始像素缓冲区压缩为 jpeg
void compressRGBAtoJpeg (cv::Mat const &src, RawImage &dst, int quality=75)
将 RGBA cv::Mat 压缩为输出 JPEG jevois::RawImage
unsigned long compressGRAYtoJpeg (unsigned char const *src, int width, int height, unsigned char *dst, int quality=75)
将原始像素缓冲区压缩为 jpeg
void compressGRAYtoJpeg (cv::Mat const &src, RawImage &dst, int quality=75)
将 Gray cv::Mat 压缩为输出 JPEG jevois::RawImage
cv::Mat rescaleCv (cv::Mat const &img, cv::Size const &newdims)
重新缩放 OpenCV 图像，选择正确的插值类型
template<class Function , class... Args>
std::future< std::invoke_result_t< std::decay_t< Function >, std::decay_t< Args >... > > async (Function &&f, Args &&... args)
使用线程池异步执行
template<class Function , class... Args>
std::future< std::invoke_result_t< std::decay_t< Function >, std::decay_t< Args >... > > async_little (Function &&f, Args &&... args)
使用线程池异步执行
template<typename T >
std::vector< T > joinall (std::vector< std::future< T >> &fvec, bool multiline=true)
从多个异步线程收集结果，这些线程都返回 T 结果
void joinall (std::vector< std::future< void >> &fvec, bool multiline=true)
从多个异步线程收集结果，这些线程都返回 T 结果
bool isInputDevice (int fd)
指示此 fd（应来自 /dev/input/eventX）是否是键盘、鼠标等
int getConsoleFd ()
获取控制台的文件描述符
int getActiveTTY ()
获取当前活动 tty
void muteKeyboard (int tty, int &kb_mode)
防止 keystrokes 到达 tty
void unMuteKeyboard (int tty, int kb_mode)
恢复给定 tty 的键盘模式
std::string demangle (std::string const &mangledName)
Demangle a mangled name.
std::string demangle (char const *mangledName)
Demangle a mangled name.
template<typename T >
std::string demangledName ()
Get the demangled type name of type T.
template<> std::string demangledName< std::string > ()
对 std::string 进行特例化以避免得到丑陋的名称
std::string fccstr (unsigned int fcc)
将 V4L2 four-cc 代码（V4L2_PIX_FMT_...）转换为 4 字符字符串
std::string cvtypestr (unsigned int cvtype)
将 cv::Mat::type() 代码转换为字符串（例如 CV_8UC1、CV_32SC3 等）
unsigned int cvBytesPerPix (unsigned int cvtype)
返回给定 OpenCV 像素类型每像素的字节数
unsigned int strfcc (std::string const &str)
将 JeVois 视频格式字符串转换为 V4L2 four-cc 代码 (V4L2_PIX_FMT_...)
unsigned int v4l2BytesPerPix (unsigned int fcc)
返回给定 V4L2_PIX_FMT_ 每像素的字节数...
unsigned int v4l2ImageSize (unsigned int fcc, unsigned int width, unsigned int height)
返回给定 V4L2_PIX_FMT_... 的图像大小（以字节为单位）, width, height
unsigned int blackColor (unsigned int fcc)
返回对应于给定视频格式的黑色的值
unsigned int whiteColor (unsigned int fcc)
返回对应于给定视频格式的白色的值
void applyLetterBox (unsigned int &imw, unsigned int &imh, unsigned int const winw, unsigned int const winh, bool noalias)
应用 letterbox 调整大小以使图像适合窗口
std::vector< std::string > split (std::string const &input, std::string const &regex=`\\s+`)
使用正则表达式将字符串拆分为 tokens 向量以指定要拆分的内容；默认正则表达式按空格拆分
std::string join (std::vector< std::string > const &strings, std::string const &delimiter)
将 tokens 向量连接成字符串
bool stringStartsWith (std::string const &str, std::string const &prefix)
如果 str 以 prefix 开头，则返回 true（包括两个字符串相等的情况）
std::string replaceWhitespace (std::string const &str, char rep='_')
用下划线（默认）或其他字符替换字符串中的空格字符
std::string strip (std::string const &str)
从字符串末尾去除空格（包括 CR、LF、tabs 等）
std::string extractString (std::string const &str, std::string const &startsep, std::string const &endsep)
提取两个分隔符之间的字符串部分
size_t replaceStringFirst (std::string &str, std::string const &from, std::string const &to)
将 'from' 的第一个实例替换为 'to'
size_t replaceStringAll (std::string &str, std::string const &from, std::string const &to)
将所有 'from' 实例替换为 'to'
std::string replaceAll (std::string const &str, std::string const &from, std::string const &to)
将所有 'from' 实例替换为 'to'
std::string tolower (std::string const &str)
Convert string to lowercase.
std::filesystem::path absolutePath (std::filesystem::path const &root, std::filesystem::path const &path)
根据两个路径计算绝对路径
std::string sformat (char const *fmt,...) __attribute__((format(__printf__
使用 printf 样式参数创建字符串
template<typename T >
std::string T from_string (std::string const &str)
从字符串转换为类型
template<typename T >
std::string to_string (T const &val)
从字符串转换为类型，适用于整数类型的版本
template<typename dest_type , typename source_type >
dest_type clamped_convert (source_type source)
Clamped numerical conversion.
void flushcache ()
刷新缓存，有时在 turbo 模式下运行相机时可能会有用
std::string system (std::string const &cmd, bool errtoo=true)
执行命令并将 stdout 输出抓取到字符串
std::string secs2str (double secs)
报告以秒为单位的持续时间，单位可变（ns、us、ms 或 s），精度为小数点后 2 位
std::string secs2str (std::vector< double > secs)
报告以秒为单位给出的 avg+/-std 持续时间，单位为变量（ns、us、ms 或 s），带有 1 个小数点
void secs2str (std::ostringstream &ss, double secs)
报告以秒为单位的持续时间（ns、us、ms 或 s）
std::string num2str (double n)
报告一个具有可变乘数（K、M、G、T、P、E、Z、Y）的数字，精度为小数点后 2 位
void num2str (std::ostringstream &ss, double n)
报告具有可变乘数 (K、M、G、T、P、E、Z、Y) 的数字
std::string getFileString (char const *fname, int skip=0)
从文件中读取一行并将其作为字符串返回
Variables
int logLevel = LOG_INFO
当前日志级别
int traceLevel = 0
当前跟踪级别
Typedef Documentation
OptGUIhelper
using jevois::OptGUIhelper = typedef GUIhelper
Definition at line 25 of file GUIhelper.H.
Enumeration Type Documentation
EditorSaveAction
enum EditorSaveAction [related]
Helper enum for actions to execute after saving a config file.
Definition at line 34 of file GUIeditor.H.
Function Documentation
async()
template<class Function , class... Args>
std::future<std::invoke_result_t<std::decay_t<Function>, std::decay_t<Args>...> > jevois::async (Function && f, Args &&... args)
使用线程池异步执行
Referenced by jevois::rawimage::byteSwap(), jevois::GUIhelper::compileCommand(), jevois::dnn::NetworkHailo::doprocess(), jevois::MovieOutput::MovieOutput(), jevois::dnn::Pipeline::process(), jevois::dnn::Network::ready(), jevois::rawimage::unpackCvRGBAtoGrayRawImage(), and jevois::dnn::PostProcessorDetectYOLO::yolo().
async_little()
template<class Function , class... Args>
std::future<std::invoke_result_t<std::decay_t<Function>, std::decay_t<Args>...> > jevois::async_little (Function && f, Args &&... args)
使用线程池异步执行
Referenced by jevois::CameraDevice::CameraDevice(), jevois::GUIhelper::drawSystem(), jevois::Engine::Engine(), and jevois::Watchdog::Watchdog().
drawErrorImage()
void jevois::drawErrorImage (std::string const & errmsg, jevois::RawImage & videoerrimg)
将错误消息显示到 RawImage 中
错误消息应由一个字符串组成，其中多行可能由 \n 字符分隔，例如 warnAndIgnoreException() 返回的字符串。该消息将写入 图像中，该图像应该是有效的（）。这对于显示通过 USB 发送的视频流中的模块异常很有用。
Definition at line 299 of file Log.C.
References jevois::RawImage::clear(), jevois::rawimage::drawDisk(), jevois::rawimage::drawLine(), jevois::RawImage::fmt, jevois::rawimage::Font10x20, jevois::rawimage::Font14x26, jevois::rawimage::Font6x10, jevois::rawimage::Font7x13, jevois::RawImage::height, LERROR, split(), jevois::RawImage::valid(), whiteColor(), jevois::RawImage::width, and jevois::rawimage::writeText().
getFanSpeed()
int jevois::getFanSpeed ()
获取风扇速度百分比，仅在 JeVois-Pro 平台上有意义，其他所有平台均返回 0
Definition at line 153 of file SysInfo.C.
References getFileString().
Referenced by jevois::GUIhelper::drawSystem().
getNumInstalledNPUs()
size_t jevois::getNumInstalledNPUs ()
获取此系统上存在的 JeVois-Pro NPU 数量
Definition at line 127 of file SysInfo.C.
Referenced by jevois::GUIhelper::drawSystem(), and jevois::dnn::Pipeline::Pipeline().
getNumInstalledSPUs()
size_t jevois::getNumInstalledSPUs ()
获取此系统上存在的 Hailo8 SPU 数量
Definition at line 138 of file SysInfo.C.
References getFileString(), and to_string().
Referenced by jevois::GUIhelper::drawSystem(), and jevois::dnn::Pipeline::Pipeline().
getNumInstalledTPUs()
size_t jevois::getNumInstalledTPUs ()
获取此系统上存在的 Coral TPU 数量
Definition at line 87 of file SysInfo.C.
References getFileString(), system(), and to_string().
Referenced by jevois::GUIhelper::drawSystem(), and jevois::dnn::Pipeline::Pipeline().
getNumInstalledVPUs()
size_t jevois::getNumInstalledVPUs ()
获取此系统上存在的 Myriad-X VPU 数量
Definition at line 112 of file SysInfo.C.
References system().
Referenced by jevois::GUIhelper::drawSystem(), and jevois::dnn::Pipeline::Pipeline().
logEnd()
void jevois::logEnd ()
终止日志服务
您必须在准备结束程序时调用此方法，以停止记录器线程。否则，ThreadPool 将卡在一个正在运行的线程上，并且永远不会退出。
Definition at line 144 of file Log.C.
References logSetEngine().
Referenced by main().
opengl_error()
std::string jevois::opengl_error (int err) [inline]
Function to write OpenGL errors in clear witout requiring GLUT.
Definition at line 60 of file OpenGL.H.
videoMappingsFromStream()
std::vector<VideoMapping> jevois::videoMappingsFromStream (CameraSensor s, std::istream & is, size_t & defidx, bool checkso, bool hasgui)
解析配置文件中的所有映射，并指出哪一个是默认的
文件的内容已排序，以便生成的向量按以下顺序排列：1) 格式 fcc，然后是 2) 分辨率（从大到小，先看 x），以及 3) 帧速率 （从高到低）。
相机格式字段可以有冒号分隔的前缀，用于指定 WDR（宽动态范围）相机捕获模式和/或当相机输入暗淡与传感器原生暗淡不匹配 时的裁剪与重新缩放行为（仅对 JeVois-Pro 有效）。
输出宽度和高度可以是绝对的，也可以是相对于相机宽度和高度（如果前缀为 + 或 - 符号）。
如果输出格式重复，每增加一个重复，帧速率就会降低 1fps。这是因为我们需要向主机提供不同的视频格式，以便用户可以选择 他们想要的格式。例如：
YUYV 320 240 60.0 YUYV 320 240 60.0 JeVois SaveVideo
YUYV 320 240 60.0 YUYV 320 240 60.0 VendorX MyModule
YUYV 320 240 60.0 YUYV 320 240 60.0 VendorY MyModule
YUYV 320 240 60.0 YUYV 320 240 60.0 VendorZ MyModule
将被消除歧义为：
YUYV 320 240 60.0 YUYV 320 240 60.0 JeVois SaveVideo
YUYV 320 240 59.0 YUYV 320 240 60.0 VendorX MyModule
YUYV 320 240 58.0 YUYV 320 240 60.0 VendorY MyModule
YUYV 320 240 57.0 YUYV 320 240 60.0 VendorZ MyModule
并且在 guvcview 或主机上运行的类似程序中，这 4 个映射将可用，因为它们对应 4 个不同的帧速率。建议您在 JeVois 命 令行界面中发出 listmapping 命令以确认在进行任何调整后在运行时使用的最终映射；有关详细信息，请参阅 命令行界面用户指南 。
defidx 是结果映射向量中默认格式的索引。如果指定了多个默认格式，则以第一个为准。
有关如何组织 videomappings.cfg 的说明，请参阅 视频模式和映射用户指南
Referenced by main().