jevois::IMUdata Struct Reference
#include <jevois/Core/IMUdata.H>
IMU 数据
Definition at line 65 of file IMUdata.H.
Public Member Functions
IMUdata (IMUrawData const &rd, double arange, double grange)
从原始数据读数构造
float & ax ()
const float & ax () const
float & ay ()
const float & ay () const
float & az ()
const float & az () const
float & gx ()
const float & gx () const
float & gy ()
const float & gy () const
float & gz ()
const float & gz () const
float & temp ()
const float & temp () const
float & mx ()
const float & mx () const
float & my ()
const float & my () const
float & mz ()
const float & mz () const
Public Attributes
float v [10]
The values: ax, ay, az, gy, gy, gz, temp, mx, my, mz.
bool magovf
如果磁力计溢出则为 True
Constructor & Destructor Documentation
IMUdata()
jevois::IMUdata::IMUdata (jevois::IMUrawData const & rd, double arange, double grange)
从原始数据读数构造
Definition at line 287 of file IMUdata.C.
References jevois::IMUrawData::ax(), jevois::IMUrawData::ay(), jevois::IMUrawData::az(), jevois::IMUrawData::gx(), jevois::IMUrawData::gy(), jevois::IMUrawData::gz(), jevois::IMUrawData::mst2(), jevois::IMUrawData::mx(), jevois::IMUrawData::my(), jevois::IMUrawData::mz(), and jevois::IMUrawData::temp().
Member Function Documentation
ax() [1/2]
float& jevois::IMUdata::ax () [inline]
Definition at line 73 of file IMUdata.H.
References v.
ax() [2/2]
const float& jevois::IMUdata::ax () const [inline]
Definition at line 74 of file IMUdata.H.
References v.
ay() [1/2]
float& jevois::IMUdata::ay () [inline]
Definition at line 75 of file IMUdata.H.
References v.
ay() [2/2]
const float& jevois::IMUdata::ay () const [inline]
Definition at line 76 of file IMUdata.H.
References v.
az() [1/2]
float& jevois::IMUdata::az () [inline]
Definition at line 77 of file IMUdata.H.
References v.
az() [2/2]
const float& jevois::IMUdata::az () const [inline]
Definition at line 78 of file IMUdata.H.
References v.
gx() [1/2]
float& jevois::IMUdata::gx () [inline]
Definition at line 79 of file IMUdata.H.
References v.
gx() [2/2]
const float& jevois::IMUdata::gx () const [inline]
Definition at line 80 of file IMUdata.H.
References v.
gy() [1/2]
float& jevois::IMUdata::gy () [inline]
Definition at line 81 of file IMUdata.H.
References v.
gy() [2/2]
const float& jevois::IMUdata::gy () const [inline]
Definition at line 82 of file IMUdata.H.
References v.
gz() [1/2]
float& jevois::IMUdata::gz () [inline]
Definition at line 83 of file IMUdata.H.
References v.
gz() [2/2]
const float& jevois::IMUdata::gz () const [inline]
Definition at line 84 of file IMUdata.H.
References v.
mx() [1/2]
float& jevois::IMUdata::mx () [inline]
Definition at line 87 of file IMUdata.H.
References v.
mx() [2/2]
const float& jevois::IMUdata::mx () const [inline]
Definition at line 88 of file IMUdata.H.
References v.
my() [1/2]
float& jevois::IMUdata::my () [inline]
Definition at line 89 of file IMUdata.H.
References v.
my() [2/2]
const float& jevois::IMUdata::my () const [inline]
Definition at line 90 of file IMUdata.H.
References v.
mz() [1/2]
float& jevois::IMUdata::mz () [inline]
Definition at line 91 of file IMUdata.H.
References v.
mz() [2/2]
const float& jevois::IMUdata::mz () const [inline]
Definition at line 92 of file IMUdata.H.
References v.
temp() [1/2]
float& jevois::IMUdata::temp () [inline]
Definition at line 85 of file IMUdata.H.
References v.
temp() [2/2]
const float& jevois::IMUdata::temp () const [inline]
Definition at line 86 of file IMUdata.H.
References v.
Member Data Documentation
magovf
bool jevois::IMUdata::magovf
如果磁力计溢出则为 True
Definition at line 71 of file IMUdata.H.
v
float jevois::IMUdata::v[10]
The values: ax, ay, az, gy, gy, gz, temp, mx, my, mz.
Definition at line 70 of file IMUdata.H.
Referenced by ax(), ay(), az(), gx(), gy(), gz(), mx(), my(), mz(), and temp().
The documentation for this struct was generated from the following files:
include/jevois/Core/IMUdata.H
src/jevois/Core/IMUdata.C