jevois::IMUrawData Struct Reference
#include <jevois/Core/IMUdata.H>
原始 IMU 数据
这些是来自传感器的原始测量值。请注意，它们未缩放，因此其含义取决于所选传感器的比例（例如，加速度计为 +/-2g 或 +/-16g）。使用 IMUdata 进行缩放测量。
Definition at line 34 of file IMUdata.H.
Public Member Functions
short & ax ()
const short & ax () const
short & ay ()
const short & ay () const
short & az ()
const short & az () const
short & gx ()
const short & gx () const
short & gy ()
const short & gy () const
short & gz ()
const short & gz () const
short & temp ()
const short & temp () const
short & mx ()
const short & mx () const
short & my ()
const short & my () const
short & mz ()
const short & mz () const
short & mst2 ()
const short & mst2 () const
Public Attributes
short v [11]
The values: ax, ay, az, gy, gy, gz, temp, mx, my, mz, mst2.
Member Function Documentation
ax() [1/2]
short& jevois::IMUrawData::ax () [inline]
Definition at line 38 of file IMUdata.H.
References v.
Referenced by jevois::ICM20948::getRaw(), and jevois::IMUdata::IMUdata().
ax() [2/2]
const short& jevois::IMUrawData::ax () const [inline]
Definition at line 39 of file IMUdata.H.
References v.
ay() [1/2]
short& jevois::IMUrawData::ay () [inline]
Definition at line 40 of file IMUdata.H.
References v.
Referenced by jevois::ICM20948::getRaw(), and jevois::IMUdata::IMUdata().
ay() [2/2]
const short& jevois::IMUrawData::ay () const [inline]
Definition at line 41 of file IMUdata.H.
References v.
az() [1/2]
short& jevois::IMUrawData::az () [inline]
Definition at line 42 of file IMUdata.H.
References v.
Referenced by jevois::ICM20948::getRaw(), and jevois::IMUdata::IMUdata().
az() [2/2]
const short& jevois::IMUrawData::az () const [inline]
Definition at line 43 of file IMUdata.H.
References v.
gx() [1/2]
short& jevois::IMUrawData::gx () [inline]
Definition at line 44 of file IMUdata.H.
References v.
Referenced by jevois::ICM20948::getRaw(), and jevois::IMUdata::IMUdata().
gx() [2/2]
const short& jevois::IMUrawData::gx () const [inline]
Definition at line 45 of file IMUdata.H.
References v.
gy() [1/2]
short& jevois::IMUrawData::gy () [inline]
Definition at line 46 of file IMUdata.H.
References v.
Referenced by jevois::ICM20948::getRaw(), and jevois::IMUdata::IMUdata().
gy() [2/2]
const short& jevois::IMUrawData::gy () const [inline]
Definition at line 47 of file IMUdata.H.
References v.
gz() [1/2]
short& jevois::IMUrawData::gz () [inline]
Definition at line 48 of file IMUdata.H.
References v.
Referenced by jevois::ICM20948::getRaw(), and jevois::IMUdata::IMUdata().
gz() [2/2]
const short& jevois::IMUrawData::gz () const [inline]
Definition at line 49 of file IMUdata.H.
References v.
mst2() [1/2]
short& jevois::IMUrawData::mst2 () [inline]
Definition at line 58 of file IMUdata.H.
References v.
Referenced by jevois::ICM20948::getRaw(), and jevois::IMUdata::IMUdata().
mst2() [2/2]
const short& jevois::IMUrawData::mst2 () const [inline]
Definition at line 59 of file IMUdata.H.
References v.
mx() [1/2]
short& jevois::IMUrawData::mx () [inline]
Definition at line 52 of file IMUdata.H.
References v.
Referenced by jevois::ICM20948::getRaw(), and jevois::IMUdata::IMUdata().
mx() [2/2]
const short& jevois::IMUrawData::mx () const [inline]
Definition at line 53 of file IMUdata.H.
References v.
my() [1/2]
short& jevois::IMUrawData::my () [inline]
Definition at line 54 of file IMUdata.H.
References v.
Referenced by jevois::ICM20948::getRaw(), and jevois::IMUdata::IMUdata().
my() [2/2]
const short& jevois::IMUrawData::my () const [inline]
Definition at line 55 of file IMUdata.H.
References v.
mz() [1/2]
short& jevois::IMUrawData::mz () [inline]
Definition at line 56 of file IMUdata.H.
References v.
Referenced by jevois::ICM20948::getRaw(), and jevois::IMUdata::IMUdata().
mz() [2/2]
const short& jevois::IMUrawData::mz () const [inline]
Definition at line 57 of file IMUdata.H.
References v.
temp() [1/2]
short& jevois::IMUrawData::temp () [inline]
Definition at line 50 of file IMUdata.H.
References v.
Referenced by jevois::ICM20948::getRaw(), and jevois::IMUdata::IMUdata().
temp() [2/2]
const short& jevois::IMUrawData::temp () const [inline]
Definition at line 51 of file IMUdata.H.
References v.
Member Data Documentation
v
short jevois::IMUrawData::v[11]
The values: ax, ay, az, gy, gy, gz, temp, mx, my, mz, mst2.
Definition at line 36 of file IMUdata.H.
Referenced by ax(), ay(), az(), jevois::ICM20948::getRaw(), gx(), gy(), gz(), mst2(), mx(), my(), mz(), and temp().
The documentation for this struct was generated from the following file:
include/jevois/Core/IMUdata.H